thesofproject/sof-test

tools/sof-boot-once.sh

builtin for fix typo  
relative path to add folder without start with '.'

Bugfix: tools/sof-boot-once.sh builtin & relative path

---

tools/tplgtool.py

Output fields 'rate', 'channel' and 'dev' for PCM is inherited from previous topology reader tool, and is deprecated now. Remove these fields for clarity.
we will never use these fields in the future, and before add new features to this tool, we ensure the code is clean.

tools: remove deprecated output fields for PCM

---

env-check.sh

Since the binary tplgreader is replaced by tplgtool.py, we don't need gcc as prerequisit
any more. Remove gcc check for clarity

env_check: remove gcc check in env_check.sh

---

env-check.sh

sed command for group check process output error
have more "'" in display command line,
it will cause this command couldn't work by directory paste

env_check: fix sed command output error

---

test-case/verify-ucm-config.sh

This patch add the case of verifying the ucm configuration files.
This patch doesn't support UCMv2. And UCMv2 verifying patch will be
submitted after DUT has supported UCMv2.
Signed-off-by: Libin Yang <libin.yang@linux.intel.com>

test-case: add verify-ucm-config.sh

---

tools/sof-tplgreader.py

Since the binary tplgreader is replaced by tplgtool.py
remove binary  tplgreader check refer code

tools/sof-tplgreader: cleanup useless code

---

tools/kmod/sof_remove.sh

Add snd_soc_cml_rt1011_rt5682 module removal support for CML with rt1011 and rt5682 codecs.

kmod_scripts: add support for snd_soc_cml_rt1011_rt5682

---

case-lib/pipeline.sh
test-case/verify-pcm-list.sh
test-case/verify-tplg-binary.sh

the root reason: when load command the WD (workdir) is $PWD,
from ssh the WD is $HOME
When have the same name TPLG file on the WD which is relative path
it can be detect, and verify the test case for this TPLG
now modify to load from TPLG_ROOT for the same name TPLG is 1st option
On the other hand convert the relative path TPLG to absolute path
So when review case log can finger out which TPLG verify by test-case

Bug fix: dectect error TPLG file in verify-pcm-list

---

case-lib/hijack.sh
case-lib/logging_ctl.sh

Current we support the test-case scripot load other test-case script
to finish the test-case, but from the test-case output information
the current script output will mix with sub-test-case script
Now add the 'Sub-Test' flag to the sub-test-case
when end-user catch the terminal output without confuse
for the script process
it will be helpful for maintenance the script

Feature add: modify dlog* message output to more clean up

---

tools/sof-dump-status.py

1. Check with sound/pci/hda/hda_intel.c#L2471
Add mappin '0x160c' to 'bdw'
2. Verify on BDW platform fix miss 'modules'
keyword problem in lspci command

Bug fix: sof-dump-status miss pci id '0x160c'

---

tools/sof-process-state.sh

Some commands or processes require some preparation time. At this
time, ps status will be 'uninterruptible sleep (usually IO)', this
is a normal status for us.

tools: add 'PS_STATE=D' as normal state

---

case-lib/lib.sh

Add func_lib_get_random go get random value
$# == 2: $1 is max, $2 is min
so the random value will in [ min - max ]
$# == 1: $1 is max
so the random value will in [ 0 - max ]
Other:
get $RANDOM which define by bash, this value will in [ 0 - 32767 ]

Feature add: Add random function in case-lib/lib.sh

---

tools/sof-tplgreader.py
tools/tplgtool.py

Refine tplgtool and tplgreader:
- make some methods of TplgFormatter public and static, for outside program to call
- refine tplgreader with TplgFormatter's public methods, rather than initialize a instance of TplgFormatter
- fix a grammer error of print

tools: make some methods in tplgtool.py static and public

---

test-case/check-suspend-resume.sh

Add new test Case for the suspend resume

Test Case: Add check suspend resume test

---

test-case/check-signal-stop-start.sh

This script intends to test stop/start aplay/arecord on each pipeline.

test: add stop/start pipeline test

---

tools/kmod/sof_remove.sh

new module added, needs to be listed in sof_remove.sh

tools: kmod: add support for soundwire_generic_allocation

---

test-case/check-capture.sh
test-case/check-playback.sh

Previously, we only test the first supported format for playback and capture pipeline. this patch add a command line to iterate all support formats for playback and capture pipeline.
Tested on GLK, Passed.

add a command line to iterate all supported formats for pipelines

---

test-case/check-runtime-pm-status.sh

convert sleep 5s to sleep ${delay} which is parameter of script

Bugfix: add delay option for check-runtime-pm-status

---

tools/sof-kernel-log-check.sh

After patch: thesofproject/linux#1676 merged
add "error: status" and "error: cl_dsp_init" into ignore string
to avoid catch DPS reset which can be ignored

Bug fix: sof-kernel-log-check DSP reset

---

tools/sof-kernel-log-check.sh

refef issue: https://github.com/thesofproject/sof-test/issues/43
Catch DSP reset with keyword "failed"

tools: fix sof-kernel-log-check catch DSP reset

---

test-case/verify-firmware-presence.sh
tools/sof-dump-status.py

Since linux 5.5.0-rc2, FW signed with comminuty key is moved to '/lib/firmware/intel/sof/community'.
fix path for verify-firmware-presence.sh

test-case: fix FW path for verify-firmware-presence.sh

---

test-case/check-capture.sh
test-case/check-playback.sh

Only need to dump the HW params info. Remove verbose for
aplay/arecord.

test-case: remove verbose log for playback/capture

---

case-lib/hijack.sh
case-lib/lib.sh

1. move restore function after kill child process to avoid kill
pulseaudio again
2. add delay check for restore pulseaudio to confirm restore success
3. add nohup for restore pulseaudio to avoid pulseaudio killed
by ssh lost connect
fix issue #54 

case-lib: bugfix #54 for pulseaudio restore logic

---

test-case/manual/check-pulseaudio.md

PulseAudio is currently tested in manual fashion. Adding manual testing
description. For Ubuntu, Setting->Sound is used to check or change
pulseaudio input/output devices.

test case: manual pulseaudio test case

---

test-case/check-signal-stop-start.sh
test-case/check-xrun-injection.sh

If aplay or arecord is failed, no need to proceed to test.
Exit early to report for failure.

test-case: check return value of aplay or arecord

---

case-lib/opt.sh

* test will now report as `FAIL` after a problem processing parameters occurs as
well as when user wants to view help menu via `-h` flag

case-lib/opt.sh: Change exit code when calling func_opt_dump_help

---

case-lib/hijack.sh
case-lib/lib.sh

record current PID as lock file
from dlog* refer keyword to ignore sub-test case
when load exit will clean up the lock file for current PID

[RFC] case-lib: add lock of sof-test

---

tools/sof-tplgreader.py

Currently, we use rate_min in tplg as rate for aplay and arecord,
but for some platforms, the value of rate_min is 0, and thus
aplay and arecord will report error.
This patch use rate_min as rate for aplay and arecord if it is not
zero, otherwise, use rate_max

tools: fix rate error on some platform

---

case-lib/config.sh

For some platforms, wov pipeline is present as a capture pipeline,
this will cause some test cases failed.
This patch add DMIC16k to TPLG_BLOCK_LST, thus we can ignore wov
pipeline in test cases.
I checked all the tplgs, and wov pipeline names are unified to "DMIC16k".
@xiulipan @Bin-QA this patch will cause the  DMIC16kHz pipelines on some platforms left untested. we may need a discussion here

case-lib: add DMIC16k to TPLG_BLOCK_LST

---

test-case/check-kmod-load-unload.sh
tools/sof-dump-status.py

On some platforms, after module insertion, it will take
sometime for dsp to become suspended. If sleep time is too
short, we will remove module when dsp is active, this causes
error.
This patch checks dsp status before module removal.

test-case: check dsp status before module removal

---

test-case/check-capture.sh
test-case/check-kmod-load-unload-after-playback.sh
test-case/check-pause-resume.sh
test-case/check-playback.sh
test-case/check-runtime-pm-status.sh
test-case/check-signal-stop-start.sh
test-case/check-suspend-resume-with-audio.sh
test-case/check-xrun-injection.sh
test-case/multiple-pipeline-capture.sh
test-case/multiple-pipeline-playback.sh
test-case/test-speaker.sh
test-case/volume-basic-test.sh
tools/sof-tplgreader.py

1. split both type pipeline into playback and capture pipelines
2.  remove "both" in test cases
@Bin-QA Wubin will modify the simultaneous-playback-capture.sh test case, and add logic to extract "both" type pipeline.
***DO NOT MERGE BEFORE PR #10 ***

sof-test: split both type pipeline into playback and capture

---

test-case/simultaneous-playback-capture.sh

hot fix for when target tplg miss 'both' type pipeline
will load all pipeline in the case execute

test case: simultaneous-playback-capture fix miss 'both'

---

test-case/check-kmod-load-unload-after-playback.sh

fix issue #89
refind the LOG_ROOT to let each sub case write log to the different
log folder

test case: check-kmod-load-unload-after-playback fix confuse log name

---

tools/kmod/sof_insert.sh

if `insert_modlue snd_soc_rt5677` is absent, we will get "rmmod: ERROR: Module snd_soc_rt5677 is not currently loaded" on helios.
This patch fix the issue above.

kmod: fix snd_soc_rt5677 is not currently loaded error

---

case-lib/hijack.sh
case-lib/lib.sh

1. Add pid detect to avoid perpare case
abnormal exit without lock clean
2. follow Liam suggest change from 'skip' => 'Incomplete'
Add new exit status:3 for 'Incomplete'

case-lib: fix sof-test.lock refer problem

---

case-lib/hijack.sh

sometime OS will reset the kern.log file
it will let DMESG_LOG_START_LINE value is 0
fix issue: #106 

case-lib: hijack exit() to add dmesg catch

---

case-lib/logging_ctl.sh

fix when give 'LOG_ROOT' without create the folder
test-case will miss the LOG_ROOT to write some thing

case-lib: logging_ctl force create log_root

---

case-lib/lib.sh
test-case/check-capture.sh
test-case/check-pause-resume.sh
test-case/check-playback.sh
test-case/check-runtime-pm-status.sh
test-case/check-signal-stop-start.sh
test-case/check-suspend-resume-with-audio.sh
test-case/check-xrun-injection.sh
test-case/test-speaker.sh
tools/sof-tplgreader.py

this PR include 2 patch
1. add 'snd' which mapping /dev/snd/pcm* in sof-tplgreader
2. add lsof check to confirm resource is not lock by other process
it can catch error like this : `aplay: main:788: audio open error: Device or resource busy`

add lsof device file check when aplay/arecord/speaker failed

---

case-lib/lib.sh

when pulseaudio configure without keyword 'autospawn'
try to disable pulseaudio will failed

case-lib: fix pulseaudio disable problem

---

case-lib/hijack.sh
case-lib/lib.sh
case-lib/pipeline.sh

check the log for lib.sh, hijack.sh and pipeline.sh, refine some of the log to eliminate ambiguity and unclear expression.

case-lib: improve log readability

---

case-lib/hijack.sh
case-lib/lib.sh

If pulseaudio not restored within timeout after disabled, information of successful pulseaudio restoration still output to user.
This patch adds more log of pulseaudio manipulation, and tag pulseaudio related test case failed if pulseaudio not restored as expect.

case-lib: refine pulseaudo enable/disable logic

---

tools/sof-get-default-tplg.sh

kernel v5.5 uses "Topology", previous versions use "topology"

use case-insensitive grep for "topology"

---

case-lib/lib.sh

All sound device files are character device, we
should use -c to test these files.

case-lib: use -c to test sound device file

---

test-case/check-pause-release-suspend-resume.sh

The manual instructions for this test should be kept with the test itself for
reference should problems arise and the test needs to be made manual again for a
period of time.

test-case: add manual instructions to pause-suspend-resume-release test

---

tools/sof-kernel-dump.sh

Root cause is reset PATH in lib.sh, direct load sof-kernel-dump
skip reset PATH step, so miss sof-get-kernel-line in the PATH

tools: fix direct load sof-kernel-dump.sh miss sof-get-kenrel-line.sh

---

test-case/check-runtime-pm-double-active.sh

Before and after runtime pm state transition, check aplay or arecord is
working. The delay is chose from range of 3 to 15 seconds. When the delay
is long enough to have 'suspended' state, then check for the state as well.
Add capture pipeline support for runtime pm test
aplay/arecord can be used by setting -m option. Add scanning dmesg before
switching pipeline.
For reviewers, initially I wanted to merge this two test cases with new input parameter, but it bacame too ugly to read. One more loop and multiple checking mode etc.

test-case: check aplay/arecord before and after runtime pm

---

tools/kmod/sof_insert.sh
tools/kmod/sof_remove.sh

This patch fixed https://github.com/thesofproject/sof-test/issues/146

kmod: remove snd_soc_rt1308 before removing snd_soc_rt6231

---

tools/kmod/sof_remove.sh

This needs to be removed before removing soundwire_intel
https://sof-ci.01.org/linuxpr/PR1940/build3399/devicetest/ICL_RVP_HDA/check-kmod-load-unload.sh/check-kmod-load-unload.sh.txt
Removing soundwire_intel
rmmod: ERROR: Module soundwire_intel is in use by: snd_intel_dspcfg

kmod: sof_remove: remove snd_intel_dspcfg

---

test-case/check-sof-logger.sh

Use bash -c to run sof-logger command to avoid redirect
issue of hijacked sudo.
The output size of 'du -k' is block size, and block size
for firmware log header is 4.

test-case: fix log redirect issue of check-sof-logger.sh

---

tools/sof-kernel-log-check.sh

Some of the items in ignore_str is deprecated, and some new are needed. This patch do a clean up on ignore_str according to current kernel and sof status.

tools: clean up ignore_str for sof-kernel-log-check.sh

---

case-lib/lib.sh

parameter should format as: max, min; max; empty
older older is: min, max; max; empty

case-lib: fix error parameter order of func_lib_get_random

---

test-case/verify-ucm-config.sh

After updating in alsa-lib to support UCMv2, uc_mgr_scan_master_configs()
in alsa-lib/src/ucm/parser.c will check ALSA_CONFIG_UCM2_VAR. If system
doesn't support ucm2, it won't setup this environment variable. Then it will
setup:
snprintf(filename, sizeof(filename), "%s/ucm2", snd_config_topdir());
as the config file folder. And the folder definitely doesn't exist.
A solution to skip the folder checking is use option -C to assign the
cardname manually by:
alsaucm -c $cardname open $cardname
Signed-off-by: Libin Yang <libin.yang@intel.com>

verify-ucm-config: assign cardname in option when open card

---

tools/sof-kernel-log-check.sh

As 'ACPI scan error' and 'hda_sdw_acpi_scan failed'
error messages are fixed in the kernel, these two
errors are not seen on platform without soundwire.
Revert with git introduces conflict, use this commit
to do the revert.

tools: revert 7752b6b5 and 813566fc for ignore _str

---

test-case/check-kmod-load-unload.sh

Previously, we didn't check dmesg log after module insertion, so test case may passed even there is error in dmesg after module insertion. This patch fixes that condition.

test-case: add kernel log check after module insertion

---

tools/kmod/sof_remove.sh

For platforms with only snd_soc_rt1308_sdw,
the snd_soc_rt1308 module will escape the check
of 'if lsmod | grep "$MODULE" &> /dev/null'.
Removing not existed snd_soc_rt1308 causes error.
This patch does a full match with grep, and thus
avoids the error condition.

kmod: fix snd_soc_rt1308 not loaded error

---

tools/sof-tplgreader.py

This patch fix a pga and eq assignment error, and enhance pipeline filtering feature. Now we can filter pipeline with specific component.
@fredoh9 Some usage listed below:
- all pipelines: `sof-tplgreader.py tplg-path -f "type:playback,capture"`
- capture pipelines with PGA:  `sof-tplgreader.py tplg-path -f "type:capture" "pga:any"`
- playback pipelines with EQ:  `sof-tplgreader.py tplg-path -f "type:playback" "eq:any"`
- all pipelines with PGA:  `sof-tplgreader.py tplg-path -f "pga:any"`
- all pipelines with PGA and EQ:  `sof-tplgreader.py tplg-path -f "pga:any" "eq:any" `

tools: pipeline filtering feature enhancement

---

tools/kmod/sof_insert.sh
tools/kmod/sof_remove.sh

add snd_soc_rt5682_sdw support in kmod test.

kmod: add snd_soc_rt5682_sdw support

---

case-lib/lib.sh
case-lib/logging_ctl.sh
case-lib/opt.sh
tools/sof-boot-once.sh
tools/sof-kernel-dump.sh

2 patch:
1. fix typo of tools
2. remove 'cd' change work directory to avoid some script miss problem
fix issue #163

case-lib: remove 'cd' from case-lib

---

test-case/check-sof-logger.sh

1. fix some test case sequence let sof-logger just dump
HEAD which size is 4K by 'du' command
2. fix detect error keyword overkill to avoid sof-logger
dump really error of sof
3. refine case quit process

test-case: check-sof-logger to fix issue of log file

---

case-lib/config.sh
case-lib/hijack.sh
case-lib/lib.sh

Pulseaudio may be started by many other applications,
which will cause some of the test cases failed.
This patch renames pulseaudio in func_lib_disable_pulseaudio
and rename it back in func_lib_restore_pulseaudio

case-lib: rename pulseaudio before disabling it

---

test-case/check-kmod-load-unload.sh

As the kernel has made its log less verbose, the key
word 'firmware boot complete' we use is not in the
less verbose log now. So remove the check of this
keyword.
Instead, add verify-sof-firmware-load.sh subtest
to check if firmware is loaded successfully after
module insertion.
tested on mantis, glk, PASSED

 test-case: add firmware load subtest for kmod test

---

case-lib/hijack.sh

add double quote to prevent globbing and word splitting.

case-lib: fix the syntax error

---

case-lib/hijack.sh
case-lib/lib.sh
case-lib/pipeline.sh
test-case/check-signal-stop-start.sh
test-case/check-xrun-injection.sh
test-case/simultaneous-playback-capture.sh
test-case/verify-pcm-list.sh
test-case/verify-tplg-binary.sh
test-case/volume-basic-test.sh

PR test specify topology like this: TPLG=sof-cml-rt1011-rt5682.tplg, under this condition, the tplgtool.py can not find the topology we specified, thus, we will get "Failed to generate topology graph" error.
This patch add a function to get topology path, and use it everywhere it can be used to replace old ugly code.

case-lib: misc fix on topology path

---

case-lib/hijack.sh
env-check.sh

As we always see "failed to generated graph" error message, this patch does two things:
- add python3-graphviz to env-check.sh
- add debug information for graph generation

sof-test: misc fix for graph generation

---

case-lib/hijack.sh
tools/tplgtool.py

We may lost debug message if we redirect stdout of tplgtool.py to /dev/null.
```
tplgtool.py -d graph -D $LOG_ROOT $tplg_path > /dev/null
```
As above call of tplgtool.py output nothing but error message, remove the redirection. without the error message, we may get confused in PR test result.
```
2020-04-10 02:37:53 UTC [REMOTE_INFO] Graph of /lib/firmware/intel/sof-tplg/sof-hda-generic-4ch.tplg will be generated to /home/ubuntu/sof-test/logs/check-playback/2020-04-10-10:37:15-29086
2020-04-10 02:37:53 UTC [REMOTE_ERROR] Failed to generate topology graph
2020-04-10 02:37:54 UTC [REMOTE_INFO] Test Result: PASS!
```
This patch helps to tell us why topology graph is failed to generate.

case-lib: remove I/O redirection for tplgtool.py

---

test-case/check-sof-logger.sh

use file content keyword instead of file size detect to judgment data
file already dumped

test-case: check-sof-logger use file content instead of size of file

---

.travis.yml
tools/shellcheck-gitrange.bash

Travis passes $TRAVIS_COMMIT_RANGE to new shellcheck-gitrange.bash
Runs shellcheck only on files changed by the PR.

CI: travis: new shellcheck-gitrange.bash

---

tools/kmod/sof_remove.sh

When multiclient changes are merged, snd_sof_ipc_test is first client
module to test ipc flood test. 2nd client is snf_sof_probes whilch support
Probe feature. The client modules need to be removed before snd_sof.

kmod: sof_remove.sh: add snd_sof_ipc_test, snd_sof_probes support

---

tools/kmod/sof_remove.sh

kmod: update wm8804 machine driver name

---

case-lib/hijack.sh

Generating graph in hijacked exit is not a good
solution to this feature. This patch reverts #166.
As auto revert is not possible after so many PR
merged, this patch remove the graph generation
code in hijacked exit.

case-lib: remove topology graph generation code

---

test-case/check-capture.sh
test-case/check-playback.sh

Previously, We will save dmesg per pipeline,
this not necessary, an overall log collection
at the end of test case is good enough.
more log files will add a lot of complexity to show in the web.
Here, the Per pipeline log are all empty. 
https://sof-ci.01.org/linuxpr/PR1971/build3638/devicetest/CFL_RVP_HDA/check-playback-3times/

test-case: don't save dmesg per pipeline

---

case-lib/pipeline.sh

Previously, to support "-f filter1 filter2" parameter, we use while to iterate all filter items.
For now, the pipeline filter is only a single string, we don't need a loop here.

case-lib: refine pipeline filter for pipeline.sh

---

test-case/check-runtime-pm-double-active.sh
test-case/check-runtime-pm-status.sh

when load sof-kernel-log-check it should check the return value
fix case:
check-runtime-pm-status.sh
check-runtime-pm-double-active.sh

test-case: check-runtime-pm-* miss verify kernel check result

---

case-lib/pipeline.sh

In pipeline.sh, we should make variable cmd local,
because this variable name is also used in some
test cases.

case-lib: make variable local to avoid impact on test cases

---

test-case/check-capture.sh
test-case/check-pause-resume.sh
test-case/check-playback.sh

with this patch, QA can run test case on specified single pipeline rather than iterate all pipelines

test-case: add support for testing on specified pipeline

---

env-check.sh

1. fix python3 package check in the wrong way
older check by 'which', the new check by
'python3 -c "import package"'
2. fix shellcheck for func_check_pkg

env-check: add python3 package check

---

.travis.yml
tools/shellcheck-gitrange.bash

$TRAVIS_COMMIT_RANGE contains triple dots,
e.g. "origin/master...HEAD". This is great for git diff but unsuitable
for git log. Convert any triple dots to double dots before passing to
git log (don't change the argument for git diff --name-only).
Also use a more verbose git log command and --no-pager instead of the
gross '|cat ': the sanity check was reporting issues but always
reporting success.
Fixes: faadb20a8548 ("CI: travis: new shellcheck-gitrange.bash")

tools/shellcheck: git log ${TRAVIS_COMMIT_RANGE/.../..}

---

test-case/multiple-pause-resume.sh

There should be a 'space' between function
and its arguments

test-case: fix a bash grammer error

---

tools/sof-get-kernel-line.sh

system will store '0x0' into /var/log/kern.log file,
it normally when system hang/something
For Ubuntu 18.04: it happend at line end
For Ubuntu 19.10: it happend at line begin
So for Ubuntu 19.10 with 'grep' command,
it will been catched after line number
This issue will cause the command of pipeline
couldn't format the string
This patch to fix the '0x0' after line number

tools: sof-get-kernel-line remove 0x0 in grep result

---

tools/sof-dump-status.py

when target DUT have multiple PCI device
query from intel id list couldn't find target pci id
this patch to fix out of intel PCI device

tools: sof-dump-status add 'know' for pci hw_name

---

case-lib/hijack.sh
case-lib/lib.sh
case-lib/logging_ctl.sh
case-lib/opt.sh
case-lib/pipeline.sh

Update for fix shell check error for case-lib/*
expect case-lib/config.sh file

fix shell check error for case-lib/*

---

tools/kmod/sof_insert.sh
tools/kmod/sof_remove.sh

rt5682 i2c driver is spilt from rt5682 codec driver.
Signed-off-by: Bard Liao <yung-chuan.liao@linux.intel.com>
The kernel change is https://github.com/bardliao/linux/commit/a50067d4f3c1d60d3fa07584aa6a0f897c1ac5b6

kmod: update rt5682_i2c codec driver name

---

case-lib/hijack.sh

use 'trap' command hijack exit command instead of function
'exit' which perpare for 'set -e'

case-lib: hijack.sh use trap to hijack exit command

---

case-lib/hijack.sh

direct to `trap 'func' exit` command
will load the exit code of exit command
use `trap 'func $?' exit` to passdown exit code
to the function

case-lib: hijack.sh fix trap exit command

---

tools/kmod/sof_remove.sh

add snd_soc_sof_da7219_max98373 support for JSL with da7219
and max98373 codecs.

kmod: add support for snd_soc_sof_da7219_max98373

---

tools/shellcheck-gitrange.bash

Add '-x' option for shellcheck to fix SC1090 error

tools/shellcheck-gitrange.bash to add '-x' option

---

tools/sof-dump-status.py

The platform name of PCI ID 0x4dc8 should be "jsl".

tools: fix a PCI ID to platform name map error

---

tools/sof-kernel-log-check.sh

Each ignore item should have a reason. This helps us
to trace every ignore item.
This patch split ignore_str into ignore items, and provide
descirption on why each item is ignored.

[Wait Test Result]tools: split ignore_str and give reason for each ignore item

---

tools/sof-tplgreader.py
tools/tplgtool.py

- enhance pipeline searching logic to support complex graph search
- add support for filterg KWD pipeline
- add support for filtering pipeline with ASRC
Usage: 
- get KWD pipeline: `sof-tplgreader.py -f "kpbm" tplg-name`
- get all pipelines: `sof-tplgreader.py tplg-name` or `sof-tplgreader.py -f "type:any" tplg-name`
- get pipelines with eq: `sof-tplgreader.py -f "eq" tplg-name` or `sof-tplgreader.py -f "eq:any" tplg-name`
- get playback pipelines: `sof-tplgreader.py -f "type:playback" tplg-name`
- get capture pipelines exclude KWD pipeline: `sof-tplgreader.py -f "type:capture" tplg-name`  KWD pipeline is hidden, current test case cannot handle it.
- get pipelines without eq: `sof-tplgreader.py -f "~eq" tplg-name`
- get pipelines with PGA but without eq: `sof-tplgreader.py -f "pga & ~eq" …

tools: pipeline filtering enhancement

---

case-lib/lib.sh

commit b8d6a278d1f0 added -x to the shellcheck call, use it.

case-lib/lib.sh: remove disable=SC1091 thanks to shellcheck -x

---

tools/sof-tplgreader.py
tools/tplgtool.py

This patch adds support for DSM and ECHO REFERENCE
pipelines filtering.
To support this complex feature, this patch also add
cap name in the pipeline's info, which is used to help
to correctly match PCM.

tools: DSM and ECHO REFERENCE pipelines filtering

---

tools/sof-tplgreader.py

Pipeline ID acquired from binary topology
is a string, we should sort pipeline by
numerical ID.
This patch converts string ID to numerical
ID when sorting pipeline.
Fixes: #284

tools: sort pipeline by numerical ID

---

tools/tplgtool.py

Previously, topology graph is drawn per pipeline,
so there will be duplicated links on component like
mixer.
This patch records components' links, and only links
conponents not previouly linked.
Fixes: #282

tools: fix duplicated link in topology graph

---

tools/sof-kernel-log-check.sh

When scan errors in kernel log in sof-kernel-log-check.sh, current code filter "sof-audio" first then check for error. This will limit scanning logs and not scalable. Below $project_key is nothing but "sof-audio".
```
err_str="error|failed|timed out|panic|oops"
project_key="sof-audio"
if [ "$ignore_str" ]; then
err=$(eval $cmd|grep 'Call Trace' -A5 -B3)$(eval $cmd | grep $project_key | grep -E "$err_str"|grep -vE "$ignore_str")
else
err=$(eval $cmd|grep 'Call Trace' -A5 -B3)$(eval $cmd | grep $project_key | grep -E "$err_str")
fi
```
We should remove this limitation. If we see unrelated error, we can add it to ignoring error list. This is first step toward this approach. I ran first test on APL, CML Helios, ICL RVP. If no objection is raised, I will scan logs for all supported platforms …

Remove sof-audio before scanning dmesg for error and Ignore known issues

---

env-check.sh

Check sof-dyndbg.conf available in the system, give optional warning and
print short usage of dyndbg for SOF modules.

env-check: add sof-dyndbg.conf file check

---

case-lib/hijack.sh

Once DSP hangs, sof-logger will exit early before
we explicitly kill it. Test case will exit due to
the failure of killing sof-logger if we have 'set -e'
in the case.
This patch makes the kill of sof-logger always return
true.

case-lib: fix case exit early caused by sof-logger

---

test-case/check-fw-echo-reference.sh

There's no point running shellcheck and disable every warning without
any attempt to fix them or explain why they're disabled.
Most of the warnings that were disabled don't even exist!
Let's keep the 2 warnings that actually exist as reminders of real bugs
that should be fixed eventually.
This brings down the number of "shellcheck disable" for the _entire
sof-test repo_ from 17 down to 4.

check-fw-echo-reference.sh: remove 13 abusive 'shellcheck disable'

---

test-case/run-all-tests.sh

If user specifies TPLG in env, we will get a wrong
topology path in run-all-tests.sh. So test case which
requires topology path will fail.
This patch adds usage and command option parser, and
fix TPLG path issue by checking and reexporting TPLG env.
Fixes: #308

test-case: fix TPLG path issue and refine run-all-tests

---

case-lib/hijack.sh

Example:
```
06:03:34 UTC [WARNING] No sof-logger found
06:03:34 UTC [INFO] no source file, use /dev/zero as dummy playback source
06:03:34 UTC [ERROR] No available topology for pipeline export
06:03:34 UTC [ERROR] Starting func_exit_handler(), exit status=1, FUNCNAME stack:
06:03:34 UTC [ERROR]    die()  @  ./test-case/../case-lib/lib.sh
06:03:34 UTC [ERROR]    func_pipeline_export()  @  sof-test/case-lib/pipeline.sh:11
06:03:34 UTC [ERROR]    main()  @  ./test-case/check-playback.sh:71
06:03:34 UTC [WARNING] No sof-logger found
06:03:35 UTC [ERROR] sof-logger was already dead
06:03:36 UTC [INFO] Test Result: FAIL!
```

hijack.sh: print a call trace on every failure

---

test-case/run-all-tests.sh

Sample output (with artificially modified testlist):
```
PASS: tplg-binary;
FAIL: firmware-presence; sof-logger; firmware-load;
test end with 3 failed tests
```
Or:
```
PASS: firmware-presence; firmware-load; tplg-binary;
test end with 0 failed tests
```
We should not keep investing in this script but rather find and re-use
some existing test runner instead. For instance git has an impressive
test runner for tests in shell script. On the other hand, 6 extra lines
of code is very little additional technical debt for a short summary of
which tests passed and failed. This saves grepping a very long test log
- even worse - scrolling up and down and missing failures.

run-all-tests.sh: print results at the end of the (long!) output

---

case-lib/opt.sh

Also fix "$@" -> "$*" bug in commented out debug statement

opt.sh: show option arguments when one of them is wrong

---

tools/sof-kernel-log-check.sh

First commit is for Intel(R) Management Engine Interface(mei) errors
2nd commit is for DELL touchpad i2c errors
Both are not 100% reproducible but fairly easy to reproduce.

Ignore non-audio errors on CML Mantis

---

test-case/check-capture.sh
test-case/check-playback.sh
test-case/verify-firmware-presence.sh
test-case/verify-pcm-list.sh
test-case/verify-tplg-binary.sh

Now that we have commit 1aef6b9a18e7 ("print a call trace on every
failure") any premature exit is easy to locate even if doesn't print any
error.
Incremental progress towards issue #312 "add set -e to all
tests". Provides some decent coverage of case-lib/*.sh routines while
carefully avoiding any big disruption.
Will also help detect failures to start the logger when combined with
some other, incoming work.

Add set -e to 5 basic tests

---

test-case/verify-sof-firmware-load.sh

Switch to journalctl --dmesg which is slower because it gets the log
from boot which means it works.
Also remove the useless and confusing eval and the useless [ ]
test. Switch one grep to grep -q to avoid generating a massive string
and cap the other two to just 12 lines (enough to see some repetition if
any)
This was tricky to reproduce because it required some indirection script
like run-all-tests.sh.
Good reminder to gradually get rid of dmesg everywhere.

verify-sof-firmware-load: stop using dmesg; ring buffers can expire

---

case-lib/lib.sh

When running a kmod-load-unload test locally on a Ubuntu 20.04 machine, it couldn't re-start pulseaudio, the reason was, that the script was trying to start the command in the form '   pulseaudio -D' i.e. with several spaces in front of the executable name and that didn't work. Whereas just using the line as obtained from "ps" output works.
I'm not sure how reliable this solution is. But it also boils down to whether we should use `ps` output to re-start pulseaudio or just use `pulseaudio --start`. Maybe the latter would be more reliable.

fix pulseaudio re-start command line

---

tools/wavetool.py

The command line variable is made global in 4f989221,
we don't need to pass any sub-parameters from command
line to functions, we can use them directly.

wavetool: don't pass cmd line parameters to function

---

tools/sof-tplgreader.py

Previous version of sof-tplgreader.py will block echo
reference capture pipeline if we both sepcify
'-f echo:any' and  '-b'.
This patch refine block feature for above issue.

tools: fix pipeline block feature for echo reference

---

tools/sof-kernel-log-check.sh

Ignore non-audio related errors in GLK Bobba DA7219.
fixes: https://github.com/thesofproject/sof-test/issues/348

tools: ignore GLK i2c SRM failed to lock errors

---

test-case/check-keyword-detection.sh

The only warning left 'frequency appears unused' seems legit.

check-keyword-detection.sh: fix 5 trivial shellcheck warnings

---

test-case/check-keyword-detection.sh

The comma separator is missing when updating the config
blob, which will cause errors when writing it back.

test-case: fix the missing separator in config blob and remove the unused parameter

---

case-lib/pipeline.sh

The "No available topology ..." info is misleading,
this patch makes it clearer.
Fixes: #232

pipeline: fix misleading pipeline exporting info

---

test-case/run-all-tests.sh

Use pwd to resolve relative paths that can be broken by symbolic links.

run-all-tests.sh: add $mydir to allow invoking from anywhere

---

test-case/verify-sof-firmware-load.sh

verify-sof-firmware-load: fix the last shellcheck warnings and more specific grep

---

tools/sof-kernel-log-check.sh

Re-submitting the first part of #354 . This only updates the `ignore_str` filters and does not have any actual code change.

ignore_str filter updates from Pierre

---

tools/sof-kernel-log-check.sh

On ICL, the info "sof-audio-pci 0000:00:1f.3:
status = 0x00000000 panic = 0x00000000" causes
test failure because we detect the word "panic".
This patch ignores this pattern.

tools: ignore false error message for ICL

---

case-lib/lib.sh

Needed to (manually and locally) test our overly complex error handling framework, see for instance PR #354

case-lib/lib.sh: add new fake_kern_error()

---

test-case/verify-sof-firmware-load.sh

Dump last 50 lines from journalctl to check why the test fail.
Add debug logs to check why the case failed

[test]verify-sof-firmware-load: add debug logs for fail case

---

case-lib/hijack.sh

On my system sudo fails to use cached credentials when invoked from
"expect" for some unknown reason. Rather than debugging this, let's
replace the 9 lines long `expect` test with a much simpler one-line "sudo
--non-interactive" test which works perfectly.

hijack.sh: fix sudo test for cached credentials or NOPASSWD

---

tools/sof-kernel-log-check.sh

2 commits. The main one:
Fixes ac415de ("tools: ignore a false error message with 'panic'")
which was ignoring way too many errors. See previous PR and long source
code comment.
Generally speaking, ignoring errors ("green failures") is extremely
dangerous and should be as narrow as possible.
More specifically here, not even knowing which platforms experience the
issue and what code they print is is really not going to help fix it.

@marc-hb sof-kernel-log-check: narrower ignore_str for ICL reboot issue

---

test-case/check-kmod-load-unload.sh

No functional change for now, not even a minor bug fix.

check-kmod-load-unload: fix all shellcheck warnings

---

case-lib/hijack.sh
case-lib/lib.sh

2 commits, see commit messages.
Green failures episode "the logger"
Incomplete fix for #297 , more coming.

Stop ignoring various logger failures

---

case-lib/lib.sh

See long comment in the function header.
Also remove very bad SUDO_PASSWD suggestion from the error message and
replace it with less insecure NOPASSWD and cache credentials
suggestions.

Make func_lib_check_sudo() a warning cause sudo() message is better

---

case-lib/hijack.sh

hijack.sh: don't fail yet when sof-logger resists kill -INT

---

test-case/multiple-pipeline-capture.sh
test-case/multiple-pipeline-playback.sh

The commit 84f5895 wrongly remove the code logic to
acquire pipeline count from multi-pipeline-playback/
capture test cases. This leads to the 'max_count' used
in these scripts being empty, as no pipeline is actually
tested, the test cases will always pass.
This patch adds the pipeline count acquisition logic back.

test-case: add missing pipeline count acquisition logic

---

tools/sof-kernel-log-check.sh

sof-kernel-log-check: ignore an ime_me error on CML_RVP_SDW

---

tools/kmod/sof_remove.sh

Modules need to be removed for kmod remove/insert tests to pass

kmod: add support for SoundWire SDCA 0.6 codecs

---

case-lib/hijack.sh

Commit 61271a3a03aa ("logger: stop discarding all error messages and fix
the cleanup code") made two mistakes:
1. It used the -INT signal which doesn't always work. This broke most
tests.
2. It then misused exit_failure=2 where 2 means Not Applicable. This
turned most broken tests to green.
Rushed commit a2669ff6591a ("hijack.sh: don't fail yet when sof-logger
resists kill -INT") then downgraded all this to warning to get the tests
passing again. However it didn't deal with the real issue: stopping the
logger on the first try. Switching to TERM does it and will hopefully
close https://github.com/thesofproject/sof/issues/3433

hijack.sh: switch first attempt to stop the logger from -INT to -TERM

---

tools/sof-kernel-log-check.sh

For old kernels like 5.8.10, we can still get boot fail logs in old style.
Add them into ignore list in sof-kernel-log-check

Add old ignore pattern for sof-kernel-log-check

---

test-case/verify-sof-firmware-load.sh

We can still see issue with verify-sof-firmware-load. Add more
debug logs to help root cause the issue.

test-case: add more debug logs for verify-sof-firmware-load

---

test-case/check-pause-resume.sh
test-case/check-reboot.sh
test-case/check-suspend-resume-with-audio.sh
test-case/check-suspend-resume.sh
test-case/multiple-pause-resume.sh
test-case/verify-kernel-module-load-probe.sh
test-case/verify-sof-firmware-load.sh

Fixes: #312
Signed-off-by: RuiqingX <ruiqingx.zhang@intel.com>

test-case: add set -e to 7 function test

---

case-lib/opt.sh

opt.sh: don't print a backtrace after the usage message

---

tools/kmod/sof_remove.sh

Need to remove snd_sof_intel_client first and snd_sof_client
before snd_sof.
Ancillary Bus need sof_snd_intel_client to remove before sof_snd.
https://sof-ci.01.org/linuxpr/PR2264/build4588/devicetest/

kmod: remove sof_snd_intel_client

---

case-lib/opt.sh

Why lose a good error message like this one!?
```
getopt: invalid option -- 'u'
```
Never, ever discard stderr.

opt.sh: don't discard getopt stderr

---

case-lib/opt.sh

We don't need "bc" to reverse a boolean, $((! )) does it just fine.
@plbossart reported that bc is not installed on Debian by default.

opt.sh: remove dependency on "bc"

---

tools/sof-kernel-log-check.sh

The audio PCI ID on CML Mantis is 8086:9dc8, which is
defined as CNL in linux kernel.
The ignore_str used to apply to CML should also be
applied to CNL platforms.

sof-kernel-log-check: extend ignore_str for CNL platforms

---

tools/sof-kernel-log-check.sh

Fixes: #396
Signed-off-by: RuiqingX <ruiqingx.zhang@intel.com>

sof-kernel-log-check: ignore i2c error for DELL CML HDA laptop + i915 Type-C error

---

tools/kmod/sof_remove.sh

When legacy drivers are built and driver run-time selection, the
sof_remove.sh script fails since a number of modules are in use. These
drivers are actually not doing anything since their probe failed, but
the modules are still loaded.
Remove them explicitly so that the script correctly handles
dependencies.

kmod: remove legacy drivers if loaded

---

tools/sof-kernel-log-check.sh

This is needed on CHT devices
BugLink: https://github.com/thesofproject/sof-test/issues/431

sof-kernel-log-check: ignore USB hub issues

---

tools/sof-kernel-log-check.sh

Commit f764b59 ignore an ime error, and the similiar
ime error is observed again, but with a different PCI ID,
we need to ignore both.
Check daily report #473 / #457 suspend-resume test case for the error.

sof-kernel-log-check: ignore an ime error for CML and ICL

---

tools/sof-dump-status.py

This patch keeps PCI ids in sof-dump-status.py and https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/sof/sof-pci-dev.c aligned

sof-dump-status: add TGL-H audio PCI ID

---

test-case/check-keyword-detection.sh

During the test, we found that KWD capture volume is a little
bit high. The volume will affect the THDN value and leads WOV
test fails occasionally. Lower the volume to make the WOV test
more stable.

test: adjust the vloume for KWD capture

---

test-case/verify-sof-firmware-load.sh

With previous logs, we can norrow down the empty sof version info is related with
kern.log. Add debug logs to kern.log to help us root cause the issue.

test-case: add kern.log debug logs in verify-sof-firmware-load

---

env-check.sh

This PR improve env-check.sh:
- add check for sof-logger, sof-ctl and sof-*.ldc
- add check for python3-numpy and python3-scipy
- fix some shellcheck warnings

env-check: add check for more required files and python packages

---

case-lib/lib.sh

The SOF card is renamed in linux kernel,
our regular expression for old nameing style
only works under SoundWire and HDAudio. But
SOF card information in /proc/asound/cards
still contains 'sof-[a-z]' pattern.
This patch updates the regular expression for
acquiring SOF card ID.
Fixes: #420

lib.sh: fix SOF card ID acquisition logic

---

tools/sof-kernel-log-check.sh

This allows removing "eval" and some quoting headaches.
Also fix the last shellcheck warnings

sof-kernel-log-check.sh: change sed -n $begin,\$p to tail -n +$begin 

---

case-lib/config.sh

Media playback pipeline test is blocked in the
early stage of SOF development, maybe because it
caused a lot of trouble.
But as the SOF evolves, we don't have a reason to
continue blocking the test on media playback pipeline
any more.

config.sh: enable media playback pipeline test

---

tools/wavetool.py

For current WoV setup, the THD+N of a captured wave
without any distortion may be lower than -75dB, lower
the default threshold to make WoV test pass.

wavetool: lower default threshold for WoV test case

---

tools/sof-kernel-log-check.sh

This error is reported in suspend/resume test.
Signed-off-by: Bard Liao <yung-chuan.liao@linux.intel.com>

sof-kernel-log-check: ignore ACPI error for Dell TGL SDW laptop

---

test-case/check-alsabat.sh

There is error hanlder to upload the failure wav files in this test case.
set -e will skip them
And our lib could not handle the return value 23 from alsabat failure.
Fix https://github.com/thesofproject/sof-test/issues/441

test-case: check-alsabat: remove set -e

---

test-case/check-suspend-resume-with-audio.sh

Never discard stderr unless you don't want to find bugs. Who knows this
could help with https://github.com/thesofproject/linux/issues/2433?
This makes no output difference when the test is passing so not sure
what the point was. Maybe it was a failed attempt to silence the shell's
"Killed" message? Also adding a new dlogi() to make it clear this
"Killed" message is not a failure.

check-suspend-resume-with-audio: don't discard stderr

---

case-lib/config.sh

Still not sure config.sh is very useful but that's a different topic.

case-lib/config.sh: fix last shellcheck warning in case-lib/*.sh

---

tools/kmod/sof_remove.sh

Now SST driver is enabled alongside with SOF drvier. Need to
remove the SST drivers as well.
Fix: #458

tools: kmod: remove snd_soc_skl

---

test-case/check-volume-levels.sh
test-case/run-all-tests.sh
tools/check_volume_levels.m

This patch adds a shell script that measures volume levels
to compute gains when executed with a nocodec topology where
SSP ports are connected to play -> capture loopback.
The measured gains are compared against test procedure and
error is issued if the gains deviate more than tolerance.
Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>

Test-case: Add check volume levels

---

tools/sof-kernel-log-check.sh

Now the DSP reset failur is seen on more platform. Move this filter out     of platform.

sof-kernel-log-check.sh: move the DSP reset filter out of platform filter

---

env-check.sh

It was not very useful to tell the user that some files lack execute
permission without saying which ones. Especially not useful when the
files missing execute permission are irrelevant files like foo.sh~
backup files. This is also simplifies the code.
Also rephrase the error messages and offer a simpler chmod fix

env-check.sh: show which file(s) lack exec permissions. Other cleanups

---

case-lib/opt.sh

Add missed newline for the default value in help usage
output.
fix: #461

lib: opts: fix format in help

---

tools/sof-dump-status.py

lspci returns different prefixes on different devices, always add the
leading "0000" if not already provided by lspci
BugLink: https://github.com/thesofproject/sof-test/issues/464

sof-dump-status: fix lspci output parsing for PCI devices.

---

tools/sof-kernel-log-check.sh

Move CML specific mei_me error filters to platform specific
section and cover all three typical errors mei_me emits on
these devices.
Example CI run where error is seen in logs:
https://sof-ci.01.org/linuxpr/PR2518/build4747/devicetest/
BugLink: https://github.com/thesofproject/sof-test/issues/389

sof-kernel-log-check.sh: finetune mei_me known error filtering

---

tools/sof-kernel-log-check.sh

sof-kernel-log-check.sh: add (long) ignore_str guidelines

---

tools/sof-kernel-log-check.sh

This error appeared in V5.10-rc1, discard it for now.

sof-kernel-log-check: filter out DRM error

---

case-lib/lib.sh

Auxiliary devices in SOF feature is introduced in
thesofproject/linux#2501, which adds a new sof-probes
card in /proc/asound/cards. Old SOF card number
acquisition cannot work any more due to this change.
This patch excludes the sof-probes card with a grep.

lib.sh: revise card number acquisition code

---

test-case/check-audio-equalizer.sh
test-case/check-capture.sh
test-case/check-fw-echo-reference.sh
test-case/check-keyword-detection.sh
test-case/check-kmod-load-unload-after-playback.sh
test-case/check-pause-resume.sh
test-case/check-playback.sh
test-case/check-runtime-pm-double-active.sh
test-case/check-runtime-pm-status.sh
test-case/check-signal-stop-start.sh
test-case/check-smart-amplifier.sh
test-case/check-suspend-resume-with-audio.sh
test-case/check-xrun-injection.sh
test-case/multiple-pause-resume.sh
test-case/multiple-pipeline-capture.sh
test-case/multiple-pipeline-playback.sh
test-case/simultaneous-playback-capture.sh
test-case/test-speaker.sh
test-case/volume-basic-test.sh

If a shell function takes a variable as its argument,
and the variable is empty, then the argument will
degrade to nothing in the function.
This patch adds quotes to function arguments to avoid
argument degrading.

test-case: add quotes to function arguments for func_export_pipeline

---

tools/sof-kernel-log-check.sh

This is unrelated to SOF, add to filters.
BugLink: https://github.com/thesofproject/sof-test/issues/482

sof-kernel-log-check: filter out USB 3.1 suspend/resume issues

---

case-lib/lib.sh

See #312 for more details.
This bug was neither painting failures green nor successes red but it
was at least interrupting the tests before manual error messages could
get printed.

lib.sh: make func_lib_lsof_error_dump() compatible with set -e

---

tools/tplgtool.py
tools/wavetool.py

This breaks the "file" command on Ubuntu 2018 which stops Travis from
looking at these files.
Should probably be #!/usr/bin/env python3 but that's for another day.

tools: remove spurious space from # !/usr/bin/python3 shebang

---

tools/sof-dump-status.py

Add PCI ID for the AlderLake-S platform.
change from  https://github.com/thesofproject/linux/pull/2550

tools: sof-dump-status: add PCI ID for ADL-S

---

case-lib/config.sh
case-lib/lib.sh
test-case/check-capture.sh
test-case/check-fw-echo-reference.sh
test-case/check-ipc-flood.sh
test-case/check-keyword-detection.sh
test-case/check-kmod-load-unload.sh
test-case/check-pause-release-suspend-resume.sh
test-case/check-pause-resume.sh
test-case/check-playback.sh
test-case/check-runtime-pm-double-active.sh
test-case/check-runtime-pm-status.sh
test-case/check-signal-stop-start.sh
test-case/check-smart-amplifier.sh
test-case/check-suspend-resume-with-audio.sh
test-case/check-suspend-resume.sh
test-case/check-xrun-injection.sh
test-case/multiple-pause-resume.sh
test-case/multiple-pipeline-capture.sh
test-case/multiple-pipeline-playback.sh
test-case/simultaneous-playback-capture.sh
test-case/test-speaker.sh
test-case/volume-basic-test.sh

What we need is to set a checkpoint for kernel log to let
us start check kernel. Rename last_line to a more generic
name checkpoint.

lib: rename last_line to checkpoint

---

test-case/multiple-pipeline-capture.sh

Only on a test failure.
Sample output:
```
15248 aplay -D hw:0,0 -c 2 -r 48000 -f S16_LE /dev/zero -q
15209 arecord -D hw:0,1 -c 2 -r 48000 -f S16_LE /dev/null -q
15218 arecord -D hw:0,2 -c 2 -r 16000 -f S16_LE /dev/null -q
15228 arecord -D hw:0,0 -c 2 -r 48000 -f S16_LE /dev/null -q
```

multiple-pipeline-capture: show aplay/record processes left on fail

---

test-case/multiple-pipeline-playback.sh

Display PID of aplay/arecord on failure.
I was so thrilled to see https://github.com/thesofproject/sof-test/pull/507. Missed playback test need same fix.

multiple-pipeline-playback.sh: show aplay/arecord processes left on fail

---

test-case/check-kmod-load-unload.sh

The output of sub-case verify-sof-firmware-load.sh
gives hints on why test case failed, should not hide
its output.

kmod-load-reload: don't hide FW load check logs

---

case-lib/hijack.sh

We must always print some 'Test Result' otherwise some callers will time
out, see alsabat example in
https://sof-ci.01.org/linuxpr/PR2501/build4685/devicetest/
Fixes: #441

func_exit_handler: print 'Test Result: FAIL!' for unknown exit codes

---

test-case/multiple-pipeline-capture.sh

Notably remove top-level "expr" because "expr 0" is surprisingly a
failure and expr is antiquited anyway (SC2003)
Also add a dlogi() before killing so no one mistakes the deaths of aplay
and arecord for failures.
Progress towards #312.

multiple-pipeline: fix set -e compatibility and add it

---

tools/sof-kernel-log-check.sh

Third party NOHZ tick-stop error causes a false
failure on CML_RVP_SDW, ignore this false failure.
Fixes: #505

sof-kernel-log-check: ignore NOHZ tick-stop error

---

tools/sof-kernel-log-check.sh

latest test result got DSP reset failure with random status and panic value
sof-audio-pci 0000:00:0e.0: status = 0xecc00301 panic = 0x00000000
update the regex for this.

sof-kernel-log-check.sh: update the regex for DSP reset fails random logs

---

README.md
case-lib/lib.sh
test-case/check-capture.sh
test-case/check-playback.sh
test-case/multiple-pipeline-capture.sh

"All problems in computer science can be solved by another level of
indirection"
First step towards #489
Default `SOF_ALSA_OPTS` to `--fatal-errors`, can be overriden with:
```
SOF_ALSA_OPTS="" ./scripts/run-all-tests.sh
```

New aplay_opts() and arecord_opts() to change flags across all tests

---

tools/sof-get-default-tplg.sh

sof-get-default-tplg: quote $tplg_file, last shellcheck warning

---

case-lib/pipeline.sh

As we discussed in https://github.com/thesofproject/sof-test/issues/504, let fail the case if no pipeline found from proc.
BTW, if no pipeline found from proc, we must have some serious P1 issues.

pipeline.sh: fail if no pipeline found from proc

---

test-case/multiple-pipeline-capture.sh

Fixes 202507fe0c71 ("multiple-pipeline: fix set -e compatibility and add
it") that didn't pay attention to the fact that sof-process-state.sh
returns 2 when there is no process match and broke the test when there
are only aplay or only arecord commands but not both at the same time.
This regression was observed (among others) at:
https://sof-ci.01.org/linuxpr/PR2565/build4887/devicetest/?model=APL_UP2_NOCODEC&testcase=multiple-pipeline-capture
Also fixes more minor set -e compatibility issues.
I missed the failure in
https://sof-ci.01.org/softestpr/PR497/build372/devicetest/?model=APL_UP2_NOCODEC&testcase=multiple-pipeline-capture
because it was reported as "N/A" and not FAIL because Jenkins interprets
an exit status '2' as N/A. I should have paid more attention.
Signed-off-by: Marc …

multiple-pipeline-capture.sh: fix recent set -e related regression

---

tools/kmod/sof_insert.sh
tools/kmod/sof_remove.sh

max98373_i2c driver is spilt from max98373 codec driver.

kmod: add max98373_i2c codec driver name

---

test-case/check-alsabat.sh

... as opposed to assuming that any -q output is an error message.

check-alsabat: use aplay/arecord exit status in precheck

---

test-case/multiple-pipeline-capture.sh
test-case/multiple-pipeline-playback.sh

While making recent changes to multiple-pipeline-capture.sh I had
vaguely noticed some similarities with multiple-pipeline-playback.sh but
I had naively not realized that they were both an exact copy/paste of
each other except for a couple lines. This commit make -playback catch
up with recent -capture enhancements. It also makes them nearly
identical again which is the first step before (painful) deduplication.

Make multiple-pipeline-playback 99% identical to -capture again

---

case-lib/lib.sh
test-case/check-ipc-flood.sh
test-case/check-pause-resume.sh
test-case/check-runtime-pm-double-active.sh
test-case/check-runtime-pm-status.sh
test-case/check-suspend-resume-with-audio.sh
test-case/check-suspend-resume.sh
test-case/multiple-pause-resume.sh
test-case/multiple-pipeline-capture.sh
test-case/multiple-pipeline-playback.sh
test-case/simultaneous-playback-capture.sh
test-case/verify-sof-firmware-load.sh
tools/sof-get-default-tplg.sh
tools/sof-kernel-log-check.sh

- dmesg usage clean up
- journalctl replacement
- new error log ignore list‘
TODO:
kernel log dump and some test case dmesg usage.

journalctl patchset version 5

---

test-case/multiple-pipeline-capture.sh

As suggested by Chao in #521
Also remove no-op exit $? on the last line.

multiple-pipeline-capture: simplify func_error_exit()

---

test-case/multiple-pipeline-playback.sh

This was apparently missed in #529
Together with #523 this makes it identical to multiple-pipeline-capture.sh
again.

multiple-pipeline-playback: remove dmesg -C call

---

case-lib/lib.sh

This wasn't really a problem as long as sof-kernel-log-check.sh was
reading /var/log/kernel.log, which just changed in PR #529

fake_kern_error: add missing \n when writing to /dev/kmsg

---

tools/sof-kernel-log-check.sh

In ACPI related error logs, missed escaping for '(' and ')'

tools: sof-kernel-log-check: fix bracket in ACPI errors

---

tools/sof-process-state.sh

... because its normal output is typically discarded.
This would have avoided regression 202507fe0c71 / #497 fixed by #521.
This could help with other multi pipelines issues.
Also add a documentation header so not everyone has to read the entire
code.
Also add a warning about the massive copy/paste across
multiple-pipeline-playback and multiple-pipeline-capture (these are the
heaviest sof-process-state users).

sof-process-state: print errors on stderr

---

tools/sof-kernel-log-check.sh

Add one more DRM error message to the list of ignored errors.

kernel: add a string to ignore

---

tools/sof-kernel-log-check.sh

use if then else fi to replace wrong usage of condition check with
&& and ||

tools: sof-kernel-log-check: fix wrong usage of condition check

---

test-case/multiple-pipeline.sh

pidof ignores processes in uninterruptable sleep by default, probably
because sending them signals is futile. pidof has a -z option but it's
just simpler to use "ps".
Also de-duplicate code into new ps_checks() function
Fixes: #472
Any aplay or arecord process can be in uninterruptable sleep when doing
I/O but the easiest way to reproduce is to wait a few seconds and let the
DSP go to sleep.

multiple-pipeline: replace pidof->ps to catch uninterruptible sleep

---

tools/sof-kernel-log-check.sh

Bus clash detected is an valid error log.
Signed-off-by: Bard Liao <yung-chuan.liao@linux.intel.com>

tools: sof-kernel-log-check: remove Bus clash detected

---

tools/sof-kernel-log-check.sh

Include case-lib/lib.sh and use journalctl_cmd() wrapper instead

sof-kernel-log-check: drop $journalctlflag duplicating journalctl_cmd()

---

tools/sof-kernel-log-check.sh

'.' is single charactor. Template string doesn't need error number
to have.
Still test will be failed due to this errors without this fix.
```
[   28.970627] kernel: usb 3-10: device descriptor read/64, error -71
[   29.193611] kernel: usb 3-10: device descriptor read/64, error -71
[   29.526684] kernel: usb 3-10: device descriptor read/64, error -71
[   29.746289] kernel: usb 3-10: device descriptor read/64, error -71
[   30.887534] kernel: usb 3-10: device not accepting address 13, error -71
[   31.415512] kernel: usb 3-10: device not accepting address 14, error -71
```

sof-kernel-log-check: fix to filter out USB3.1 suspend/resume error

---

tools/sof-kernel-log-check.sh

After using journalctl, third-party error message
which doesn't contain predefined keywords will be
collected, too. Ignore a USB error on TGL in this
patch.

sof-kernel-log-check: ignore a usb error on TGL

---

tools/sof-kernel-log-check.sh

Remove the ending '.+' to avoid shadowing of preceeding
filter string.
Fixes: b5138778
suggested by @marc-hb , thanks

sof-kernel-log-check: refine filter string for USB error

---

tools/sof-kernel-log-check.sh

Helios reported some usb errors, and caused false
failure.
This patch revises ignore_str to also ignore the usb
errors on Helios.
Fixes: #567

sof-kernel-log-check: revise ignore_str for usb errors

---

test-case/check-suspend-resume-with-audio.sh

This patch makes it possible for running suspend-
resume-with-audio test case on specified pipelines
rather than iterating all pipelines.
acceptable options for -P:
- `id:0`   pipeline with id 0
- `id:0,2`    pipelines with id 0 or 2
- `pga:any`  pipelines with pga
- `eq:any`  pipelines with eq
- `asrc:any`  pipelines with asrc

test-case: enable running case on specified pipelines

---

case-lib/opt.sh
test-case/check-alsabat.sh
test-case/check-audio-equalizer.sh
test-case/check-capture.sh
test-case/check-fw-echo-reference.sh
test-case/check-ipc-flood.sh
test-case/check-keyword-detection.sh
test-case/check-kmod-load-unload-after-playback.sh
test-case/check-kmod-load-unload.sh
test-case/check-pause-release-suspend-resume.sh
test-case/check-pause-resume.sh
test-case/check-playback.sh
test-case/check-reboot.sh
test-case/check-runtime-pm-double-active.sh
test-case/check-runtime-pm-status.sh
test-case/check-signal-stop-start.sh
test-case/check-smart-amplifier.sh
test-case/check-suspend-resume-with-audio.sh
test-case/check-suspend-resume.sh
test-case/check-volume-levels.sh
test-case/check-xrun-injection.sh
test-case/multiple-pause-resume.sh
test-case/multiple-pipeline.sh
test-case/simultaneous-playback-capture.sh
test-case/test-speaker.sh
test-case/verify-pcm-list.sh
test-case/verify-tplg-binary.sh
test-case/volume-basic-test.sh

This PR renames two variable names used to define script command line options, `OPT_OPT_lst` to `OPT_NAME`, `OPT_DESC_lst` to `OPT_DESC`
No functional change, only repo wide search and replace. check discussion https://github.com/thesofproject/sof-test/issues

sof-test: rename OPT_OPT_lst and OPT_DESC_lst

---

tools/waveio.py

Currently, quality test for S24_LE is not covered,
because we are not able to read wave file of this
special format.
This patch adds an IO library for standard PCM
wave file.
Also, a light-weight format converter is implemented
in waveio.py.

tools: add waveio.py for wave file IO

---

case-lib/opt.sh

In our design, a line starts with '##' is regarded as
case documentation, we should also remove the leading
space together with '##'.
And also fix a typo in this commit.

opt.sh: remove leading space form case documentation

---

tools/kmod/sof_insert.sh
tools/kmod/sof_remove.sh

ACPI drivers were reworked, sof-acpi-dev is now a helper and no longer
the top-level. The modules were renamed, but old names kept for now,
so this change should have no functional impact.

kmod: sof-remove.sh: change ACPI dependency orders

---

case-lib/opt.sh
test-case/check-alsabat.sh
test-case/check-audio-equalizer.sh
test-case/check-capture.sh
test-case/check-fw-echo-reference.sh
test-case/check-ipc-flood.sh
test-case/check-keyword-detection.sh
test-case/check-kmod-load-unload-after-playback.sh
test-case/check-kmod-load-unload.sh
test-case/check-pause-release-suspend-resume.sh
test-case/check-pause-resume.sh
test-case/check-playback.sh
test-case/check-reboot.sh
test-case/check-runtime-pm-double-active.sh
test-case/check-runtime-pm-status.sh
test-case/check-signal-stop-start.sh
test-case/check-smart-amplifier.sh
test-case/check-suspend-resume-with-audio.sh
test-case/check-suspend-resume.sh
test-case/check-volume-levels.sh
test-case/check-xrun-injection.sh
test-case/multiple-pause-resume.sh
test-case/multiple-pipeline.sh
test-case/simultaneous-playback-capture.sh
test-case/test-speaker.sh
test-case/verify-pcm-list.sh
test-case/verify-tplg-binary.sh
test-case/volume-basic-test.sh

This PR renames two variable names used to define script command line options, OPT_PARM_lst to OPT_HAS_ARG, OPT_VALUE_lst to OPT_ARG
No functional change, only repo wide search and replace. check discussion https://github.com/thesofproject/sof-test/issues

sof-test: rename OPT_PARM_lst and OPT_VALUE_lst

---

case-lib/lib.sh
test-case/check-userspace-cardinfo.sh
test-case/check-userspace-paplay.sh
test-case/check-userspace-parecord.sh
tools/pactlinfo.py

a lot of changes have been made from the first version. And we have a full talk about the implementation. So open a new thread based on @marc-hb  's suggestion. The old version can be found: https://github.com/thesofproject/sof-test/pull/363
This patchset includes:
check-userspace-cardinfo: check pulseaudio can parse the ucm correctly and exports the correct card
check-userspace-paplay: go through all the active sinks and play on it if port is available 
check-userspace-parecord: go through all the active sources and record on it if port is available

add User space test cases (version2)

---

test-case/multiple-pipeline.sh

Running all pipelines in parallel can be completed
by specifying a very bigger pipeline count to -c option,
but it is too indirect.
This patch adds support for running all pipelines in
parallel with '-f a' option

multiple-pipeline: run all pipelines with -f a option

---

case-lib/lib.sh

The fake_kern_error need to test with not only sof related issues.
before fix:
[683402.712924] sof-audio-pci 0000:66:66.6: asix 3-12.1:1.0 enx000ec668ad2a: Failed to read reg index 0x0000: -113 >/dev/kmsg
after fix:
[683541.396907] asix 3-12.1:1.0 enx000ec668ad2a: Failed to write reg index 0x0000: -113 >/dev/kmsg

lib: remove the fake kernel device prefix

---

.github/workflows/pull_request.yml

Because the Ubuntu package index is out of date on github
https://github.com/actions/virtual-environments/issues/1757#issuecomment-765238242
Should be much faster than apt-update

[skip ci] .github/ actions: temporary python3-pil installation hack

---

case-lib/opt.sh

1. move common option definition to a function, common options can be define here(eg, help, and tplg). TODO, call this in script explicitly(rather than in opt.sh), or some options may be hidden.
2. split  function in_func_create_tmpbash to _fill_opt_vars and _validate_and_format_cmd_line for better code structure.
3. fix unclear comments and add more comments

opt.sh: refine option definition and overriding

---

.github/workflows/pull_request.yml

This GitHub action is designed for PR only.
It could not run on push.
Fix strange GitHub action on PR merge push
https://github.com/thesofproject/sof-test/runs/1774851099?check_suite_focus=true

CI: run pull_request.yml action only on PR

---

tools/kmod/sof_remove.sh

Even when idle, pulseaudio uses modules "non-deterministically". So even
on success show when it is running cause it could make this script fail
the next time.

sof_remove.sh: show pulseaudio on exit if it is running

---

tools/kmod/sof_remove.sh

From pierre-louis.bossart@linux.intel.com in PR #589
PR https://github.com/thesofproject/linux/pull/2683 introduces a
dependency change. There is still one case there a module is used
differently before and after this PR, and renaming isn't really an
option.
This patch suggests a temporary workaround where we try to remove a
module (with errors disabled), and if it doesn't work we keep going.
In practice the snd_sof_hda_common module is made mostly of helper
routines and tables, without any PCI stuff, so there is a limited risk
of issues.

kmod: unload snd_sof_intel_hda_common early, work around dep. changes

---

tools/tplgtool.py

Remove try..catch block, and let exceptions raise
up for debug purpose.
Signed-off-by: Chao Song <chao.song@intel.com>

tplgtool.py: print exception detail for debug

---

tools/sof-kernel-log-check.sh

move all iwlwifi related filter rules history into one place
and filter out all iwlwifi releated error kernel logs

tools: sof-kernel-log-check: filter out iwlwifi related error logs

---

test-case/volume-basic-test.sh

PGA name could be in uppercase or lowercase. Especially topology2 change
makes pga name in lowercase.

volume-basic-test.sh: search PGA name without case sensitive

---

case-lib/user.sh
test-case/verify-bootsequence.sh

This test case will check the UCM2 codec initialization setting
on the tested cards.
Signed-off-by: Libin Yang <libin.yang@intel.com>

userspace: add verify-ucm-bootsequence

---

tools/sof-kernel-log-check.sh

WHL UP Extreme has this errors while doing suspend/resume, need to fix
regular expression to ignore this.
[ 6876.560685] usb 1-8: device not accepting address 11, error -71
[ 6877.088731] usb 1-8: device not accepting address 12, error -71
This works with previous error pattern,
[ 1905.017875] kernel: usb 1-2.4: device not accepting address 4, error -71
Signed-off-by: Fred Oh <fred.oh@intel.com>
fixes: https://github.com/thesofproject/sof-test/issues/606

sof-kernel-log-check: fix a ignore_str for usb errors

---

tools/sof-kernel-log-check.sh

Found in TGLH_0A5E_SDW,
kernel: asix 3-3.1:1.0 enx000ec65356e1: asix_rx_fixup() Bad Header Length 0x0, offset 4
Signed-off-by: Fred Oh <fred.oh@intel.com>
fixes: https://github.com/thesofproject/sof-test/issues/622

sof-kernel-log-check: update ignore_str for asix errors

---

tools/kmod/sof_remove.sh

When pulseaudio is running display not just the warning but this too:
```
skipping snd_compress, not loaded
skipping snd_pcm, not loaded
553 /usr/bin/pulseaudio --daemonize=no --log-target=journal
ERROR: sof_remove.sh fails semi-randomly when pulseaudio is running
UNIT               LOAD   ACTIVE   SUB     DESCRIPTION
pulseaudio.service loaded active   running Sound Service
pulseaudio.socket  masked inactive dead    pulseaudio.socket
```
This points the user towards a root-cause.
Also remove obsolete `builtin exit`

kmod/sof_remove: show systemctl units when pulseaudio is running

---

case-lib/lib.sh

If DMI info is missing and the card long name is replaced with
the card name set in the machine driver, there will be 2 lines
like this:
0 [sofhdadsp      ]: sof-hda-dsp - sof-hda-dsp
sof-hda-dsp
And the test would pick up the card ID from the second line and
result in a failure.
So, ignore lines that dont start with a number to avoid this.
Signed-off-by: Ranjani Sridharan <ranjani.sridharan@linux.intel.com>

lib: pick up card ID only from the line that starts with a number

---

.github/workflows/pull_request.yml

Because Ubuntu VMs on github have a package index that is out of date by
design:
https://github.com/actions/virtual-environments/issues/ 1757

[skip ci] .github: apt-get -y update

---

tools/sof-kernel-log-check.sh

sof-test is unusable on Up Extreme due to various IGB messages.
Filter out all messages since they seem to have no functional impact.
BugLink: https://github.com/thesofproject/sof-test/issues/617

sof-kernel-log-check: filter out IGB messages

---

tools/kmod/sof_remove.sh

nocodec is a card, should be removed before sof core.
FIXME: This may break on previous versions, let's see.

kmod: sof_remove: reorder dependencies with nocodec

---

tools/sof-kernel-log-check.sh

Across the board failures in system/resume tests introduced in
v5.12-rc5
Test results at https://sof-ci.01.org/linuxpr/PR2812/build5534/devicetest/

sof-kernel-log-check: filter out USB issues on suspend/resume

---

case-lib/config.sh
case-lib/pipeline.sh

The i915 driver sometimes is not ready on a new platform,
sof-test will fail because broken HDMI pipelines are
present.
This patch adds support for no HDMI mode, once we are
under no HDMI mode, HDMI pipelines will be filtered
out, thus sof-test can run normally.
This patch has to be used with the change here: https://github.com/thesofproject/sof-test/pull/642

case-lib: add support for no HDMI mode

---

test-case/verify-pcm-list.sh
tools/sof-dump-status.py

Add support for ADL-P in tools/sof-dump-status.py since it is a new platform.
Also fix some 'set -e incompatibilities' in test-cases/verify-pcm-list.sh to avoid silent exit.

sof-dump-status : Add ADL platform info  ;  verify-pcm-list : fix 'set -e' incompatibility   

---

case-lib/config.sh
case-lib/lib.sh
test-case/check-capture.sh
test-case/check-fw-echo-reference.sh
test-case/check-ipc-flood.sh
test-case/check-keyword-detection.sh
test-case/check-kmod-load-unload.sh
test-case/check-pause-release-suspend-resume.sh
test-case/check-pause-resume.sh
test-case/check-playback.sh
test-case/check-runtime-pm-double-active.sh
test-case/check-runtime-pm-status.sh
test-case/check-signal-stop-start.sh
test-case/check-smart-amplifier.sh
test-case/check-suspend-resume-with-audio.sh
test-case/check-suspend-resume.sh
test-case/check-xrun-injection.sh
test-case/multiple-pause-resume.sh
test-case/multiple-pipeline.sh
test-case/simultaneous-playback-capture.sh
test-case/test-speaker.sh
test-case/volume-basic-test.sh

The sof-framework will add a 5-second test interval
between two test cases. This patch makes the kernel
check point include this test interval to avoid log loss.
And also rename func_lib_setup_kernel_check_point
to setup_kernel_check_point, because the prefix
doesn't provide much information.
As PR #639 makes very big change, I am going to split it to several relatively small PRs, this is the first one.

sof-test: include test interval in kernel check point

---

tools/sof-kernel-log-check.sh

'.-.+:' can cover various digit of asix version. Fixed missing '\'
for special character '(' and ')' also.
related issues: https://github.com/thesofproject/sof-test/issues/622, https://github.com/thesofproject/sof-test/issues/565

sof-kernel-log-check: update the filter for asix errors

---

tools/kmod/sof_insert.sh
tools/kmod/sof_remove.sh

3 commits, most visible one: kmod/tools: tabulate log output
Sample new output:
```
SKIP	snd_hda_codec_realtek  	not loaded
SKIP	snd_hda_codec_generic  	not loaded
RMMOD	snd_soc_acpi
SKIP	snd_hda_ext_core  	not loaded
RMMOD	snd_intel_dspcfg
SKIP	soundwire_intel_init  	not loaded
SKIP	soundwire_intel  	not loaded
SKIP	soundwire_cadence  	not loaded
SKIP	soundwire_generic_allocation  	not loaded
SKIP	regmap_sdw  	not loaded
SKIP	regmap_sdw_mbq  	not loaded
SKIP	soundwire_bus  	not loaded
RMMOD	snd_soc_core
SKIP	snd_hda_codec  	not loaded
SKIP	snd_hda_core  	not loaded
RMMOD	snd_hwdep
SKIP	snd_compress  	not loaded
RMMOD	snd_pcm
SKIP    	snd_sof_pci_intel_tng 	not in tree
SKIP    	snd_sof_pci_intel_apl 	not in tree
SKIP    	snd_sof_pci_intel_cnl 	not in tree
SKIP    	snd_sof_pci_intel_icl …
```

kmod/tools: tabulate log output, stricter lsmod | grep

---

case-lib/hijack.sh
case-lib/lib.sh
test-case/check-alsabat.sh
test-case/check-ipc-flood.sh
test-case/check-kmod-load-unload-after-playback.sh
test-case/check-pause-resume.sh
test-case/check-reboot.sh
test-case/check-sof-logger.sh
test-case/check-suspend-resume-with-audio.sh
test-case/check-userspace-cardinfo.sh
test-case/check-userspace-paplay.sh
test-case/check-userspace-parecord.sh
test-case/simultaneous-playback-capture.sh
test-case/verify-bootsequence.sh
test-case/verify-firmware-presence.sh
test-case/verify-kernel-module-load-probe.sh
test-case/verify-pcm-list.sh
test-case/verify-sof-firmware-load.sh
test-case/verify-tplg-binary.sh
test-case/verify-ucm-config.sh
test-case/volume-basic-test.sh
tools/sof-kernel-log-check.sh

Previously, we will use /var/log/kern.log for log collcetion.
At the beginning of a test, we set up DMESG_LOG_START_LINE,
and at the end of the test, we collect kernel log from the
exact point we set up.
However, /var/log/kern.log is not exist on other distro. This
patch discards the existing log collection mechanism, and use
journalctl for log collection.
The changes include:
- lib.sh: remove implicit setup of DMESG_LOG_START_LINE
- hijack.sh: use journalctl to replace /var/log/kern.log
for log collection.
- test-case: test case fix as we need explicitly set up
kernel check point for journalctl.

sof-test: use journalctl for log collection

---

test-case/check-suspend-resume.sh

After some kernel update, we start to observe a timeout
issue on several JF devices. As we are not going to fix
the kernel, this workaround is applied.
Accroding to the solution in this patch, the device may
get into sleep before netcat can send out messages, this
maybe related to network issue in the kernel, or network
route is too long between JF and SH, etc. In this patch,
we add a 1-second sleep to wait a stable connection before
running rtcwake.
Workaround: #650

check-suspend-resume: sleep 1s before rtcwake iteration

---

test-case/check-keyword-detection.sh

Previously, the call of func_pipeline_export is
earlier than setup_kernel_check_point, if we have
failure in export pipeline, the kernel check point
will not be properly set up. So bring kernel check
point set up earlier.

check-kwd: set up kernel check point earlier

---

test-case/check-runtime-pm-status.sh

runtime PM is not supported on BDW and BYT platforms, so we need
to set the kernel check point before the runtime PM support check
or the kernel check point will not be properly set up and cause
runtime PM check TIMEOUT on unsupported platforms.
Signed-off-by: Zhang Keqiao <keqiao.zhang@intel.com>

check-pm: set the kernel check point before runtime PM support check

---

.github/workflows/pull_request.yml

Funny how no one missed shellcheck and pylint...

[SKIP CI] .github: unhardcode from "master" branch that does not exist anymore

---

case-lib/lib.sh

Fixes:
```
In case-lib/lib.sh line 69:
KERNEL_CHECKPOINT=$(($(date +%s)
- $SOF_TEST_INTERVAL))
^----------------^ SC2004: $/${} is unnecessary on arithmetic variables.
```
This new warning was introduced in commit b4716c9fab29 where it was
drowned in other warnings in other files.

lib.sh: don't use $ in KERNEL_CHECKPOINT arithmetic

---

case-lib/lib.sh

No need to spam all the terminals.
From "man journalctl" and syslog before that:
```
"emerg" (0), "alert" (1), "crit" (2), "err" (3), "warning" (4),
"notice" (5), "info" (6), "debug" (7)
```

fake_kern_error(): downgrade priority from level 0 to level 3 (error)

---

.github/workflows/pull_request.yml
.github/workflows/yamllint.yml

... because there's no ${BASE_REF} and no range to check.
Stops spurious failures like:
https://github.com/marc-hb/sof-test/runs/2414768508

[SKIP CI] .github: don't run git range checks on mere pushes

---

case-lib/hijack.sh

_Resubmit #383 to new `main` branch_
Does not completely fixes #297 but goes a long way.

hijack.sh: fail if the logger trace is empty

---

case-lib/hijack.sh

One should never die in the "die handler", this means the final status
is not printed and causes a Jenkins timeout.
Fixes commit 18c7e6155053 ("sof-test: use journalctl for log
collection")

func_exit_handler: don't die when KERNEL_CHECKPOINT is missing

---

test-case/check-sof-logger.sh

Hopefully no functional change.
https://sof-ci.01.org/softestpr/PR659/build670/devicetest (and everything else) is all green

check-sof-logger: fix quoting, other shellcheck and rephrase errors

---

case-lib/hijack.sh
case-lib/lib.sh
test-case/verify-kernel-boot-log.sh

tested on several DUTs, works fine.

Add a new test case to check kernel boot log

---

test-case/multiple-pipeline.sh

Having the same -w parameter for both this initial sleep and the test
duration made no sense: fixed by removing the first sleep.
It's not clear what the purpose of this first sleep was, it has been in
multiple-pipeline-capture/playback.sh since the dawn of time (= commit
39cd964ddc776c) For sure this first sleep was helping hide
"uninterruptible state" bug #472 by giving the DSP more time to wake up!

multiple-pipeline: remove initial sleep and clarify second sleep

---

test-case/check-sof-logger.sh

Also change <<END to ::END and print both files always.
<< and >> seem to corrupt the generated HTML and I could not find
anything parsing these anyway as of now.
See discussion in (much larger) PR #666 for more details.

check-sof-logger: change BEG>> to BEG:: to avoid HTML conflict

---

test-case/multiple-pipeline.sh

This reverts commit f93a3c807b2fedbbcdbc876984137e8fca7b2cdb.
This broke multiple-pipeline-playback-50 on sh-tglu-sku0a3e-sdw-01 and
jf-cml-sku0983-sdw-2, see below. Almost all other platforms ran
fine.
Found by Keqiao in daily test run 3577 (thx)
It's not clear what exactly the issue/race is yet (let's discuss in
original PR #543 or in a new bug linked from there) but the top
priority is to fix the tests.
```
2021-04-27 22:35:17 UTC [REMOTE_COMMAND] aplay   -D hw:0,0 -c 2 -r 48000 -f S16_LE /dev/zero -q
2021-04-27 22:35:17 UTC [REMOTE_INFO] Testing: Speaker [hw:0,2]
2021-04-27 22:35:17 UTC [REMOTE_COMMAND] aplay   -D hw:0,2 -c 2 -r 48000 -f S16_LE /dev/zero -q
2021-04-27 22:35:17 UTC [REMOTE_INFO] Testing: HDMI 1 [hw:0,5]
2021-04-27 22:35:17 UTC [REMOTE_COMMAND] aplay   -D hw:0,5 -c 2 -r …
```

Revert "multiple-pipeline: remove initial sleep and clarify second sleep

---

tools/kmod/sof_insert.sh
tools/kmod/sof_remove.sh

All CI tests fail because of the introduction of a new module:
https://sof-ci.01.org/linuxpr/PR2874/build5690/devicetest/
Add it to sof_remove.sh

kmod: sof_remove.sh: add snd_sof_intel_atom

---

test-case/multiple-pipeline.sh

Having the same -w parameter for two different sleeps in the same
iteration made no sense.
It was not clear what the purpose of this first sleep was, it has been in
multiple-pipeline-capture/playback.sh since the dawn of time (= commit
39cd964) For sure this first sleep was helping hide
"uninterruptible state" bug #472 by giving the DSP more time to wake up!
More recently it was found after merging and reverting an earlier
version of this (PR #543 / commit f93a3c8) that this first sleep
was (accidentally?) giving more time for processes to actually
disappeared after being killed at the end of a test round and not
pollute the next test iteration. Make that clearer by moving the first
sleep to the end of the iteration, right after the kills and hardcode to
one second.

multiple-pipeline: simplify sleeps

---

test-case/check-sof-logger.sh

We don't want to test random versions.
For instance some old version was left in /usr/local/bin here:
http://sof-ci.sh.intel.com/#/result/planresultdetail/4007?model=ADLS_RVP_HDA&testcase=check-sof-logger
You can tell it's old version from the TIMESTAMP header missing `(us)` unit.

check-sof-logger: fail when there are multiple sof-logger in PATH

---

tools/kmod/sof_remove.sh

In my example this changes the output from a totally quiet and cryptic:
```
SKIP	snd_usb_audio  	not loaded
SKIP	snd_hda_intel  	not loaded
SKIP	snd_sof_pci_intel_tng  	not loaded
RMMOD	snd_sof_pci_intel_apl
```
to this instead:
```
SKIP	snd_usb_audio  	not loaded
SKIP	snd_hda_intel  	not loaded
SKIP	snd_sof_pci_intel_tng  	not loaded
RMMOD	snd_sof_pci_intel_apl
snd_sof_pci_intel_apl    16384  -1
snd_sof_intel_hda_common    77824  1 snd_sof_pci_intel_apl
snd_sof_pci            20480  2 snd_sof_intel_hda_common,snd_sof_pci_intel_apl
snd_soc_acpi_intel_match    40960  1 snd_sof_pci_intel_apl
snd_soc_acpi           16384  2 snd_soc_acpi_intel_match,snd_sof_intel_hda_common
snd_sof               126976  2 snd_sof_pci,snd_sof_intel_hda_common
snd_soc_core          253952  1 snd_sof …
```

sof_remove.sh: print FAILED and run lsmod when rmmod fails silently

---

case-lib/lib.sh
test-case/check-alsabat.sh
test-case/check-capture.sh
test-case/check-fw-echo-reference.sh
test-case/check-keyword-detection.sh
test-case/check-pause-release-suspend-resume.sh
test-case/check-pause-resume.sh
test-case/check-playback.sh
test-case/check-runtime-pm-double-active.sh
test-case/check-runtime-pm-status.sh
test-case/check-signal-stop-start.sh
test-case/check-smart-amplifier.sh
test-case/check-suspend-resume-with-audio.sh
test-case/check-xrun-injection.sh
test-case/multiple-pause-resume.sh
test-case/multiple-pipeline.sh
test-case/simultaneous-playback-capture.sh
test-case/test-speaker.sh
test-case/volume-basic-test.sh

since zephyr doesnot support sof-logger, so add a function
to disable logger trace for zephyr during the test.
Signed-off-by: Zhang Keqiao <keqiao.zhang@intel.com>

logger: disable sof-logger for zephyr

---

case-lib/config.sh
case-lib/pipeline.sh

Bluetooth is not supported on our linux device and
will cause -EIO when testing BT pipelines.
This patch adds an option to disable the BT test.
Once NO_BT_MODE is true, all BT pipelines will be
filtered out and skip the test.
Signed-off-by: Zhang Keqiao <keqiao.zhang@intel.com>

test: disable the test for Bluetooth pipelines

---

tools/kmod/sof_remove.sh

Remove the snd_intel_dsw_acpi module as well which remained loaded after
a run (tested on tgl-h platform).
Signed-off-by: Peter Ujfalusi <peter.ujfalusi@linux.intel.com>

tools: kmod: sof_remove.sh: Remove snd_intel_sdw_acpi

---

case-lib/hijack.sh

There are bugs that cause DMA drops and the last few lines to get stuck
somewhere. Changing the logger configuration and waiting for 1 second
seems to be enough to nudge the system and force it to DMA a bit more
logs: hopefully all the logs relevant to the current test.
Running this logger configuration command twice makes it very easy to
observe the stuck lines bug: the "ipc" logs corresponding to this -F
command will appear _only once_ at the end of the slogger.txt DMA trace!

hijack.sh: make late logger config changes to nudge stuck DMA traces

---

tools/sof-kernel-log-check.sh

kernel-log-check: revise ignore_str for usb errors.

---

tools/sof-kernel-log-check.sh

This is to fix https://github.com/thesofproject/sof-test/issues/688
filter DMA errors

sof-kernel-log-check: filter DMA errors

---

test-case/check-sof-logger.sh

The web cannot identify file type  *.log,
change it to *.txt.

test-case: check-sof-logger: rename output file

---

case-lib/lib.sh
test-case/check-capture.sh
test-case/check-playback.sh
tools/pactlinfo.py
tools/sof-combinatoric.py
tools/sof-dump-status.py
tools/sof-tplgreader.py
tools/tplgtool.py
tools/wavetool.py

These two patches make check-playback/capture test cases can run on Chrome smoothly. suppose sof-test is downloaded to /usr/local, and other dependencies are installed with [chromebrew](http://skycocker.github.io/chromebrew)

test-case: improve Chrome OS compatibility

---

tools/sof-kernel-log-check.sh

This is to filter out warning shown below
```
kernel: x86/mktme: No known encryption algorithm is supported: 0x4
```

sof-kernel-log-check: filter TME warnings

---

tools/sof-kernel-log-check.sh

This is to fix https://github.com/thesofproject/sof-test/issues/665. filter out irrelevant logs
```
[ 8399.878989] kernel: r8152 3-8.1:1.0 enx34298f909f0b: can't resubmit intr, status -1
```

sof-kernel-log-check: filter r8152 networking warnings

---

test-case/check-sof-logger.sh

Probably the main change is fixing the huge etrace test gaps #321 and
https://github.com/thesofproject/sof/issues/3281
Also fixes DMA trace gaps #297 and #298
I initial tried to preserve some of the existing code but it was just
too bad. PR #161 / commit 7274f490b78 seemed especially bad:
- It tried to ignore a specific `ll drift` error but instead it filtered
out almost every log statement out of... stderr, that does not have show
log statements!! (Just for the record this `ll drift` error has been
downgraded to warning now, see
https://github.com/thesofproject/sof/pull/2686 and
https://github.com/thesofproject/sof/issues/3854)
- That same commit also added code that merely starts the DMA trace with
"there is an error below" (without failing the test) but that's eclipsed
by the entire …

check-sof-logger: rewrite most of it so it can actually find bugs

---

tools/sof-kernel-log-check.sh

Use RegExp for filtering TME warnings .

sof-kernel-log-check:use RE to filter TME warnings

---

test-case/check-sof-logger.sh

... because it's not an error.
Required by https://github.com/thesofproject/sof/pull/4334

check-sof-logger.sh: do not assume FW ABI banner starts with ERROR

---

tools/sof-kernel-log-check.sh

Failing PS2/i8042 driver init has no impact to audio test cases.
Seen on Intel daily test #4567

sof-kernel-log-check: filter out init error from i8042

---

tools/sof-kernel-log-check.sh

fixed https://github.com/thesofproject/sof-test/issues/704
daily 4533 model=ADLS_RVP_HDA testcase=verify-kernel-boot-log
```
[    5.549481] kernel: i915 0000:00:02.0: [drm] *ERROR* AUX A/DDI A/PHY A: did not complete or timeout within 10ms (status 0xad4003ff)
[    5.549505] kernel: i915 0000:00:02.0: [drm] *ERROR* AUX A/DDI A/PHY A: not done (status 0xad4003ff)
```

sof-kernel-log-check: filter out i915 AUX errors

---

test-case/check-sof-logger.sh

2 commits. Main fix:
Killing sudo does NOT kill the sof-logger child! Use timeout as root
instead.
We probably got away with it because of the various "pkill sof-logger"
out there.
Fixes 8732f67 ("check-sof-logger: rewrite most of it so it can
actually find bugs ")

check-sof-logger: fix bug that did not kill/clean sof-logger -t

---

tools/sof-tplgreader.py

If we have two pipelines with id=1 and id=10, current
RE is not able to filter these two pipelines from each
other.
This patch deprecates RE and use string comparison for
pipeline filtering.
v2 by Marc: don't add support for non-lists, see #713 review for
details.

sof-tplgreader: don't use RE for pipeline filtering

---

test-case/check-sof-logger.sh

As we look for the FW ABI banner we must start from a clean state

check-sof-logger: reload drivers first

---

case-lib/lib.sh
test-case/verify-kernel-boot-log.sh

Collect module parameters when kernel boot log is saved. Some of
parameters are very useful to debug potential issue.
This is a output example from CML Helios,
```
---------> Printing module parameters <----------
/sys/module/snd_intel_dspcfg/parameters/dsp_driver = 3
/sys/module/snd_sof/parameters/disable_pause = N
/sys/module/snd_sof/parameters/sof_debug = 0
/sys/module/snd_sof_acpi/parameters/fw_path = (null)
/sys/module/snd_sof_acpi/parameters/sof_acpi_debug = 0
/sys/module/snd_sof_acpi/parameters/tplg_path = (null)
/sys/module/snd_sof_intel_hda_common/parameters/always_enable_dmi_l1 = N
/sys/module/snd_sof_intel_hda_common/parameters/codec_mask = -1
/sys/module/snd_sof_intel_hda_common/parameters/disable_rewinds = N …
```

print module parameter values

---

tools/sof-kernel-log-check.sh

i915 AUX errors are happening in not only adl but also adl-s.
related PR: https://github.com/thesofproject/sof-test/pull/705
Found in internal Dailiy test 4960?model=ADLS_RVP_HDA&testcase=verify-kernel-boot-log

kernel-log-check: add adl-s to ignore i915 AUX errors

---

case-lib/lib.sh
test-case/check-runtime-pm-double-active.sh
test-case/check-runtime-pm-status.sh
test-case/check-sof-logger.sh
test-case/check-xrun-injection.sh

Also  add new skip_test() function

SKIP check-sof-logger if is_zephyr

---

test-case/multiple-pause-resume.sh

@ranj063 reported this problem. Occasionally it timeout too early.
```
2021-06-30 17:20:20 UTC Sub-Test: [INFO] pipeline: Port1 with aplay
2021-06-30 17:20:20 UTC Sub-Test: [INFO] pipeline: Port2 with aplay
2021-06-30 17:20:20 UTC Sub-Test: [INFO] Check expect exit status
2021-06-30 17:20:20 UTC Sub-Test: [INFO] Port1 to command: aplay -D hw:0,1 -r 48000 -c 2 -f S16_LE -vv -i /dev/zero -q
spawn aplay -D hw:0,1 -r 48000 -c 2 -f S16_LE -vv -i /dev/zero -q^M
2021-06-30 17:20:20 UTC Sub-Test: [INFO] Port2 to command: arecord -D hw:0,2 -r 48000 -c 2 -f S16_LE -vv -i /dev/null -q
2021-06-30 17:20:20 UTC Sub-Test: [INFO] wait for expect process finished
===> Fred: only after 5 second, it timeout for 250 second!
2021-06-30 17:20:25 UTC Sub-Test: [ERROR] Still have expect process not finished …
```

multiple-pause-resume: change default values and fix serious loop index bug

---

case-lib/lib.sh

The card name for probe feature is changed to
sof-probe, change it in sof-test accordingly.
Fixes: #725

lib.sh: exclude sof-probe in detecting card number

---

tools/sof-tplgreader.py

Previous fix ce58aeda removes unclear RE for pipeline
filtering, but it also removes the ability to filter
a group of pipelines.
For example, pcm names for HDMI pipelines are HDMIn,
where n is a number, with previous RE, we are able
to filter out all HDMI pipelines with '~pcm:HDMI'.
With the fix ce58aeda, we can only filter out explicit
pipeline, for example HDMI1.
This patch brings group filter feature back, while
keeping the code clear.

sof-tplgreader: improve filter for pipeline group

---

README.md

I got tired of using grep -v and losing color and being afraid of
buffering

[SKIP CI] README.md: add instructions to turn off sudo logs in journalctl

---

case-lib/lib.sh
tools/kmod/sof_remove.sh

Trying to stop the unstoppable thanks to the --global option
Sample ~/SOF/sof-test/tools/kmod/sof_remove.sh output:
```
SKIP	snd_compress  	not loaded
SKIP	snd_pcm  	not loaded
529 /usr/bin/pulseaudio --daemonize=no --log-target=journal
+ systemctl --system list-unit-files --all '*pulse*'
UNIT FILE                           STATE  VENDOR PRESET
pulseaudio-enable-autospawn.service masked enabled
1 unit files listed.
+ systemctl --global list-unit-files --all '*pulse*'
UNIT FILE          STATE   VENDOR PRESET
pulseaudio.service enabled enabled
pulseaudio.socket  enabled enabled
2 unit files listed.
+ systemctl --user list-unit-files --all '*pulse*'
UNIT FILE          STATE  VENDOR PRESET
pulseaudio.service masked enabled
pulseaudio.socket  masked enabled
2 unit files listed.
For joe ONLY:
+ …
```

New systemctl_show_pulseaudio() that catches the sneaky 'gdm' user 

---

tools/sof-kernel-log-check.sh

elan i2c touch pad errors are nothing to do with SOF. Need to ignore them.
fixes: https://github.com/thesofproject/sof-test/issues/735

kernel-log-check: ignore more elan i2c touch pad errors

---

env-check.sh
test-case/check-volume-levels.sh

KERNEL_CHECKPOINT is mandatory to pass the test case.

[SKIP CI] check-volume-levels: fix KERNEL_CHECKPOINT not set error

---

tools/kmod/sof_remove.sh

Add a section for the SOF client drivers and update the names to match
with the known names.
Signed-off-by: Peter Ujfalusi <peter.ujfalusi@linux.intel.com>

sof_remove.sh: Update SOF client driver names

---

tools/sof-kernel-log-check.sh

on EHL platforms , when check suspend resume , 'kernel: i915 0000:00:02.0: [drm] *ERROR* Suspending crtc's failed with -22' error happens and leads testcase to fail .
Since this is irrelevant to audio , filter it so that the testcase can run successfully 

kernel-log-check: filter i915 supsending crtc logs

---

case-lib/lib.sh

Fixes commit 1494965e7f that added support for both relative and
absolute paths.

lib.sh: don't quietly override the user-provided TPLG dirname

---

tools/sof-kernel-log-check.sh

filter irrelevant DMAR false positives such as:
```
[    0.941083] kernel: DMAR: [DMA Read NO_PASID] Request device [0x00:0x02.0] fault addr 0x70a28000 [fault reason 0x0c] non-zero reserved fields in PTE
```
This is unrelated to SOF

sof-kernel-log-check: filter DMAR error

---

test-case/check-alsabat.sh

Most of alsabat test failures are due to wrong alsa settings. To debug
the failure, amixer contents dumps are very useful.
One of example, recently TGLH_0A5E_SDW failed on alsabat test. By the captured wav, it had overflow problem.
5685?model=TGLH_0A5E_SDW&testcase=check-alsabat-headset-playback
After I sshed to the device and checked the settings, there is no alsa setting issue. It might be changed after that. We need the alsa contents dump when it fails.

[SKIP CI] check-alsabat: dump amixer contents when fails

---

tools/sof-kernel-log-check.sh

filter irrelevant USB HUB false positives such as:
```
[  366.568797] kernel: usb 3-8-port4: disabled by hub (EMI?), re-enabling...
```
See also: [linux/drivers/usb/core/hub.c#L5563](https://github.com/thesofproject/linux/blob/b73297355e03ffdff62e3d7a6438934f05c58f54/drivers/usb/core/hub.c#L5563)

sof-kernel-log-check: filter USB HUB error

---

tools/sof-kernel-log-check.sh

Updated ignore_str to filter more asix errors
[Logs that needed to be filtered out ]
```
[ 7430.598174] kernel: asix 3-3.1:1.0 enx000ec65356e1: Failed to enable hardware MII access
[ 7430.599294] kernel: asix 3-3.1:1.0 enx000ec65356e1: Failed to enable hardware MII access
[ 7430.600408] kernel: asix 3-3.1:1.0 enx000ec65356e1: Failed to enable hardware MII access
[ 7430.600411] kernel: asix 3-3.1:1.0 enx000ec65356e1: Failed to write Medium Mode mode to 0x0134: ffffff8f
```
```
kernel: [ 7321.220312] asix 3-12.1:1.0 enx000ec668ad2a: Failed to read reg index 0x0000: -113
kernel: [ 7321.220314] asix 3-12.1:1.0 enx000ec668ad2a: Failed to write reg index 0x0000: -113
kernel: [ 7321.220315] asix 3-12.1:1.0 enx000ec668ad2a: Failed to enable software MII access
```
Since the common string part is …

sof-kernel-log-check: use RE to filter asix errors

---

case-lib/lib.sh

Generic commit extracted from unrelated and parked #741 
Useful considering the SKIP vs N/A confusion

lib.sh: prefix skip messages with SKIP test line

---

case-lib/lib.sh
env-check.sh

jq package will be installed with device setup script. env-check.sh will
provide a warning if jq is not installed.

[SKIP CI] lib.sh: remove temporary jq installation

---

test-case/multiple-pause-resume.sh
test-case/run-all-tests.sh

Faster pause/resume transition is more effective to find bugs. Default
loop/repeat count are slightly increased. For thorough test, use -l/-r
option to specify loop/repeat count.
run-all-test.sh has -l $small_loop to specify loop count so more iteration
can be run.
Made a separate improvement patch from https://github.com/thesofproject/sof-test/pull/723.

multiple-pause-resume: reduce min/max value for faster pause/resume

---

tools/sof-dump-status.py

Yet another green failure. Passing a wrong card number now fails as
expected:
```shell
./tools/sof-dump-status.py  -i 42 >/dev/null
Traceback (most recent call last):
File "./tools/sof-dump-status.py", line 487, in <module>
card_info = sysinfo.proc_card[str(ret_args['id'])]
KeyError: '42'
```

sof-dump-status.py: make -s, -i and -l fail on wrong card numbers

---

tools/sof-kernel-log-check.sh

Filter i915 DRM errors like:
```
[  945.548337] kernel: i915 0000:00:02.0: [drm] *ERROR* Atomic update failure on pipe A (start=184 end=185) time 149 us, min 1073, max 1079, scanline start 1071, end 1081
```
This i915 DRM errors won't affect the audio use-cases.
Need to ignore them.
see also: <https://github.com/thesofproject/linux/blob/57a88a71b411ff44a7568db05226ec2727bf91c1/drivers/gpu/drm/i915/display/intel_crtc.c#L580>
fixes #753 and #764 

sof-kernel-log-check: filter i915 DRM errors

---

.github/workflows/pull_request.yml
python-deps.txt

* Use builtin Python instead of [setup-python](https://github.com/marketplace/actions/setup-python) since we use apt to install packages.
* Move the dependencies data to python-deps.txt, so if someone wants to set up a system, they don't need to look at GitHub Actions to find dependencies. 
See also: <https://github.com/thesofproject/sof-test/pull/755#discussion_r700766961> and <https://github.com/thesofproject/sof-test/pull/755#discussion_r700421012>

[SKIP CI] GitHub Actions: Use builtin Python and move dependencies to python-deps.txt

---

case-lib/hijack.sh

For reasons beyond the scope of this commit, our Jenkins CI does not
know when a test script has finished to run. Instead of checking the
exit status like a normal test runner it waits for a "FAIL" or "PASS" or
"N/A" string to be printed. When the test aborts without printing one of
these, Jenkins falls back on a fairly long timeout - per test.
This unusual approach has been causing issues with `set -e` (#312)
In some relatively rare but possible failures the DSP or the drivers do
not load at all, examples:
https://sof-ci.01.org/sofpr/PR4782/build10387/devicetest/
https://sof-ci.01.org/sofpr/PR4766/build10353/devicetest/
https://sof-ci.01.org/sofpr/PR4768/build10348/devicetest/
In that case the $logFile is not found and many tests abort without
printing FAIL.
This commit prints FAIL when …

hijack.sh: print FAIL on missing logfile to avoid long CI timeout

---

test-case/run-all-tests.sh

Convenient when seeing a failure. Sample output:
```
2021-09-10 22:27:37 UTC Sub-Test: [INFO] Test Result: PASS!
^C
PASS: firmware-presence; speaker; firmware-load;
FAIL: sof-logger;
test end with 1 failed tests
Testing was INTERRUPTED, results are incomplete!
```

run-all-tests.sh: print partial results when interrupted with Ctrl-C

---

README.md
env-check.sh
python-deps.txt
tools/tplgtool.py
tools/tplgtool2.py

I'd like to improve the topology parser to get more info like the widget core, but the legacy code contains too many magic number which is hard to understand and maintain. Here I will rewrite the topology tools with [Construct](https://construct.readthedocs.io) which is a powerful declarative and symmetrical parser and builder for binary data to make the code more maintainable.

Rewrite topology tools with Construct to improve the readability and maintainability

---

test-case/check-sof-logger.sh

Looks like https://github.com/thesofproject/sof/pull/4763 might have
fixed it.

check-sof-logger: disable dma_nudge() workaround for stuck DMA issue 4333

---

test-case/verify-sof-firmware-load.sh

Otherwise this script stops run-all-tests.sh when it fails.

verify-sof-firmware-load: invoke systemctl with --no-pager

---

case-lib/lib.sh
test-case/verify-kernel-boot-log.sh

If device time is not accurate, let this test fail.
All of test devices are supposed to be NTP Synchronized. Power cycling
a device with no internal battery and old coin battery may cause
time out of sync.

verify-kernel-boot-log: check if the device's time is in sync

---

case-lib/hijack.sh

N/A is unusual confusing. Partial fix for #772.

hijack.sh: change "Test Result: N/A" to "Test Result: SKIP"

---

tools/kmod/sof_remove.sh

Found module removing error in TGL Debin/Voxel with I2S RT5682 codec.
RMMOD	snd_soc_core
rmmod: ERROR: Module snd_soc_core is in use by: snd_soc_rt5682s
snd_soc_rt5682s is used by snd_soc_rt5682, so remove it
after snd_soc_rt5682.
Module                  Size  Used by
snd_soc_rt5682s        98304  1 snd_soc_sof_rt5682

sof_remove.sh: remove snd_soc_rt5682s module

---

test-case/run-all-tests.sh

This test step checks with audio level measurement that the
correct volume gain and mute commands are applied to each
audio channel. The test script requires Octave.
Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>

Add volume_levels into run-all-tests.sh

---

test-case/check-sof-logger.sh

The error message with "${data_file}" was kept even when the code was
extended to check the etrace too.
Fixes commit 8732f67c9ecb ("check-sof-logger: rewrite most of it so it
can actually find bugs")

check-sof-logger: fix FAIL message to point at the correct file

---

tools/tplgtool2.py

Hide core info instead of fallback to "core:0" when it is unspecified in
topology, because the default "0" could be misleading for some
components like Buffer which are under the pipeline with the non-0 core.
example for `sof-tgl-nocodec-ci`:

tplgtool2: Hide core info when unspecified in topology

---

README.md
case-lib/logging_ctl.sh
tools/sof-get-default-tplg.sh

\+ 2 other minor fixes
Using root to write inside a regular user directory (sof-test) is not
great. It creates files difficult to remove and it does not work across
network filesystems. Don't change the default location but add a new
SOF_LOGS_BASE feature.

logging: add new SOF_LOGS_BASE feature 

---

case-lib/hijack.sh

Every workaround / hack should have such a reference.

[SKIP CI] hijack.sh: add URL to DMA stuck issue #4333. Pure comment.

---

case-lib/opt.sh

As found by Pierre in fix #791
Until #791 is merged it should fail like this:
```
23:29:31 [ERROR] Duplicate '--loop' option: loop count
23:29:31 [ERROR] Starting func_exit_handler(), exit status=1, FUNCNAME stack:
23:29:31 [ERROR]  die()  @  ./test-case/../case-lib/lib.sh
23:29:31 [ERROR]  _fill_opt_vars()  @  sof-test/case-lib/opt.sh:59
23:29:31 [ERROR]  func_opt_parse_option()  @  sof-test/case-lib/opt.sh:120
23:29:31 [ERROR]  main()  @  ./test-case/multiple-pause-resume.sh:48
```

opt.sh: catch duplicate --long options

---

case-lib/lib.sh

sudo "$loggerCmd" works only with our redefined sudo function. Replace
it with an array-based and properly quoted sudo "${loggerCmd[@]}" that
works with any sudo.

lib.sh: fix sudo "$loggerCmd" quoting

---

test-case/check-keyword-detection.sh

The SOF card number is not always 0, because we set up
a USB sound card for loopback.

keyword-detection: don't use fixed card number

---

case-lib/lib.sh

check-sof-logger was re-enabled for Zephyr in commit 56db25953967 and it
passed the daily tests. Re-enable logging for all tests when using
Zephyr.
Partial revert of 325e57244e2 ("logger: disable sof-logger for zephyr")

lib.sh: re-enable sof-logger for Zephyr

---

case-lib/lib.sh

Some configurations don't support the logger. Others do but do not want
to run it for various reasons.
Supersedes #811, see earlier discussions there.

lib.sh: disable logging with SOF_LOGGING=none env or missing .ldc

---

test-case/check-kmod-load-unload.sh
tools/kmod/sof_insert.sh

This was apparently the only test in run-all-tests.sh that required a PATH change.

check-kmod-load-unload: use TOPDIR, don't rely on PATH 

---

case-lib/lib.sh

Now that the sof-logger is well tested with Zephyr, change the
is_zephyr() test to count the number of "zephyr" strings in the .ldc
dictionary file. The previous test was based on /etc/sof/manifest.txt
which is a CI-only file. This probably removes a dependency on 'jq' too.

lib.sh: switch is_zephyr() to look for zephyr strings in .ldc

---

case-lib/lib.sh

Fixes failures to collect etrace on failure. It goes like this:
```
UTC [INFO] Starting sof-logger '' -l /lib/firmware/intel/sof/sof-apl.ldc
-o sof-test/logs/check-runtime-pm-status/2021-12-02-23:49:42-22493/etrace.txt
error: Unused parameter ''
Usage sof-logger <option(s)> <file(s)>
```
This happens when $logopt is empty.
Fixes recent regression introduced by commit 814b904acfca6 ("lib.sh: fix
sudo "$loggerCmd" quoting")

lib.sh: fix etrace collection on failure (recent regression)

---

tools/kmod/sof_remove.sh

Missing dependency causing errors
RMMOD	snd_sof_intel_hda_common
rmmod: ERROR: Module snd_sof_intel_hda_common is in use by:
snd_sof_pci_intel_skl
SKIP	snd_sof_acpi  	not loaded
RMMOD	snd_sof_pci
rmmod: ERROR: Module snd_sof_pci is in use by:
snd_sof_intel_hda_common snd_sof_pci_intel_skl

kmod: sof_remove.sh: fix SKL/KBL tests

---

case-lib/hijack.sh

Zephyr does not support trace configuration, see
thesofproject/sof#5032
5032 is not closed as "wontfix" yet but we need to urgently stop
polluting many Zephyr test results only because some relatively minor
feature is missing.
Moreover the test failures are very confusing because they happen only
when two tests are run immediately one after the other; quickly enough
for the kernel error 'error: fail in sof_ipc_trace_update_filter -22' to
appear in the results of the _next_ test. Tests are not affected by
their own errors because the filter update happens in the "tearDown"
phase, _after_ the PASS/FAIL decision has been made.

hijack.sh: disable trace filter config "nudge" for Zephyr 

---

case-lib/config.sh
case-lib/lib.sh
test-case/run-all-tests.sh

SOF_TEST_INTERVAL fixes

---

tools/sof-get-default-tplg.sh

Much faster than piping the entire logs to an external grep process;
down from 2+ seconds to 0.5s on my system.
Also makes test duration less variable, which among others makes
SOF_TEST_INTERVAL more deterministic.

sof-get-default-tplg: use faster grep feature provided by journalctl

---

case-lib/lib.sh

grep return code is '2' when files are missing. '2' is also the sof-test
convention for skipping tests.
When using print_modules_params in a test with set -e, this causes the
test to be SKIPped when the driver is not loaded.
Simply ignore all grep errors in this function; it's not the job of a
"print_" function to fail. Missing audio is already caught in many other
places.

print_modules_params: don't SKIP the test when driver is not loaded

---

test-case/verify-kernel-boot-log.sh

Show for how long the system has been up.
Together with #825, this will show whether NTP sync or any other daemon
had enough time to start.
Sample output:
```
System booted at: 2021-12-09 18:28:32
-- Logs begin at Mon 2021-08-30 11:42:24 PDT, end at Thu 2021-12-09 18:37:18 PST. --
Dec 09 18:28:37 up2 kernel: Linux version 9.9.9-rc9softest  (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld ....
Dec 09 18:28:37 up2 kernel: Command line: BOOT_IMAGE=/vmlinuz-9.9.9-rc9softest root=/dev/mapper/ubuntu--vg-root ro
```

verify-kernel-boot-log: add boot time and very start of journalctl

---

case-lib/hijack.sh

sof-logger inconveniently does not allow changing the log level without
reading some logs at the same time. We've always redirected these logs
to /dev/null but Zephyr uses a different etrace format that can cause
errors on stderr and we don't want to discard stderr because we never
want to ignore ALL errors in test code. We can't switch to the DMA trace
either because reading the DMA trace never stops.
So, read the trace from neither the DMA nor the shared memory but from
/dev/null instead.
Keep redirecting output to /dev/null too because we still don't want to
see the banner either.

hijack.sh: read from -i /dev/null when changing the log level

---

test-case/run-all-tests.sh
tools/sof-kernel-log-check.sh

Now that sof-test is using journalctl log levels and that the levels of
this DSP retries have been fixed by
thesofproject/linux#3250, it should not be
required to filter out these messages anymore. This cleanup removes
almost 30 lines of code.
This is a "logical" revert of the addition in d238c48 and of the
many changes after it; most recently 61b077b. See the code reviews
of all these commits for more details.

kernel-log-check: remove filter that ignores DSP boot retries 

---

test-case/check-sof-logger.sh

We can't even start we want to provide feedback right away (thanks to
set -e) and not rely on distant and elusive output post-processing.

check-sof-logger: print stderr output when etrace fails to start

---

case-lib/hijack.sh

This reverts commit 905bd1f33044c86db0d30123a6d4a9930179ff76.
https://github.com/thesofproject/sof/issues/5032 should be fixed now;
let's see that.

Revert "hijack.sh: disable trace filter config "nudge" for Zephyr"

---

tools/kmod/sof_insert.sh
tools/kmod/sof_remove.sh

max98390 is missing on remove
We are also missing a number of codecs on insert, reshuffle the list
so that it uses the same order as for remove - the difference being
that we don't insert common modules automagically loaded by others.
BugLink: https://github.com/thesofproject/sof-test/issues/834

kmod: add missing codecs

---

tools/sof-kernel-log-check.sh

Added a new condition, `tgl` to the file `tools/sof-kernel-log-check.sh` in the `$platform` case block.
Reference PR: https://github.com/thesofproject/sof/pull/5207#issuecomment-1012685601
Reference ticket: https://github.com/thesofproject/sof-test/issues/838

Update error filters for tpm issue.

---

env-check.sh

2 commits. Main one:
Fixes (untested?) commit f9587e0 ("env-check: display optional
octave package dependency") that added the octave checks and misused
the (misnamed) func_check_pkg() function. That function works only for
packages with an executable of the same name.
Add new func_check_dpkg() that runs a dpkg check instead.
Fixes: #780

env-check.sh: fix check for octave packages 

---

tools/sof-kernel-log-check.sh

Ignore 'failed to change power setting` and other boot time
failures. See:
https://sof-ci.sh.intel.com/#/result/planresultdetail/9950?model=TGLU_VOLT_SDW&testcase=verify-kernel-boot-log
Note the failure does not seem fatal, `echo i2c-GDIX0000:00 >
/sys/bus/i2c/drivers/i2c_hid_acpi/bind` still seems to work on the
device reporting the error.

sof-kernel-log-check: ignore i2c_hid_acpi i2c-GDIX0000:00 errors

---

tools/sof-kernel-log-check.sh

As requested in #850.
We unfortunately use a mix of tabs and spaces. Let's try to keep each
file consistent with at least itself.
I have a shortcut in my editor to switch, afraid everyone should have
one too.

sof-kernel-log-check: pure whitespace fixes

---

tools/sof-get-default-tplg.sh

This fixes the confusion between (for instance)
```
/lib/firmware/intel/avs-tplg/sof-hda-generic-idisp.tplg
```
and
```
/lib/firmware/intel/sof-tplg/sof-hda-generic-idisp.tplg
```
The other option was to return `sof-tplg/sof-hda-generic-idisp.tplg` but
this would have required all users of this script to adapt whereas this
change will hopefully go unnoticed.
Also add some error handling, comments and other cleanups.

sof-get-default-tplg.sh: return full /lib/firmware/sof-tplg/*.tplg path

---

tools/kmod/sof_insert.sh

Loading modules that are already loaded is pointless.
Now it is possible to pass module parameters.

sof_insert: load snd-sof-pci/acpi _before_ they're loaded automatically

---

case-lib/lib.sh
test-case/check-kmod-load-unload.sh
test-case/verify-sof-firmware-load.sh

See commit messages.
Fixes #842 and #845. Follows the direction discussed and agreed at the bottom of superseded #855
Thanks to the addition of KERNEL_CHECKPOINT logic, also fixes bug where a very old firmware load was enough to make `check-kmod-load-unload.sh` pass.

Fix check-kmod-load-unload. Make it and verify-sof-firmware-load IPC4-compatible

---

tools/kmod/sof_remove.sh

snd_soc_intel_sof_realtek_common is missing on remove so that we need to add it in modules removed.
Related test failure : see inner daily testresult 10553 ADLP_GMB_I2S check-kmod-load-unload-25
With this commit , the failure was gone

sof_remove: remove module snd_soc_intel_sof_realtek_common

---

test-case/verify-kernel-boot-log.sh

ADL is not "in development" anymore but we still have some errors. Add
reference to internal bug number.

[SKIP CI] verify-kernel-log: change ADL skip_test reason

---

test-case/verify-sof-firmware-load.sh

Fixes commit cd2d7073337332 that now looks for the "firmware boot
complete" message instead of the firmware version(s) but forgot to
update the error message.

verify-sof-firmware-load: fix error message according to new test

---

test-case/verify-sof-firmware-load.sh

verify-sof-firmware-load: fix dmesg.txt collection + better logs + fix -help

---

tools/kmod/sof_insert.sh
tools/kmod/sof_remove.sh

Add missing machine driver and codecs. The 8326 is added for future
support, the driver is not even upstream just yet.

kmod: add support for ES83x6 platforms

---

test-case/multiple-pipeline.sh

Previously, the Echo Reference pipeline has been skipped when running
the parallel pipeline test, but it wasn't skipped when calculating
PIPELINE_COUNT. Therefore, on all pipelines mode, the expected process
count is inconsistent with the actual running process. To solve this
issue, skip the same pipeline when acquiring the pipeline count for
consistency.

multiple-pipeline: skip Echo Reference pipeline when getting count

---

test-case/check-sof-logger.sh

This reverts commit 4b3f84754ddec8051cf3dac6180ef32950c6fdf0.
Looks like we're stuck again, see latest updates in thesofproject/sof#4333

Revert "check-sof-logger: disable dma_nudge() workaround for stuck DMA issue #4333

---

tools/sof-kernel-log-check.sh

Ignores:
```
kernel: I/O error, dev loop0, sector 0 op 0x0:(READ) flags 0x80700 phys_seg 1 prio class 0
```
Happening at boot time or when apt re-installing snapd (restarting it
does not reproduce)
Fixes #874

Ignore snapd dev loop0 I/O error happening at boot time

---

tools/kmod/sof_insert.sh

snd_sof_pci_intel_skl is referenced in sof_remove.sh but not in
sof_insert.sh. Add the missing support

kmod: sof_insert: add missing skl support

---

case-lib/lib.sh

Currently, sof-logger is not supported when running IPC4 mode.
Thus, disable SOF logs collection globally when DUT runs IPC4 mode (this can be telled by system file /sys/module/snd_sof_pci/parameters/ipc_type).
This should be removed after sof-logger support for IPC4 has been provided.
Signed-off-by: Xiaoyun Wu(Iris) <xiaoyun.wu@intel.com>

lib.sh: disable sof-logger when running IPC4 mode

---

tools/sof-kernel-log-check.sh

kernel 5.18-rc1 added a set of harmless NVME errors that we should
filter out until removed upstream.
BugLink: https://github.com/thesofproject/sof-test/issues/888

sof-kernel-log-check: temporarily filter out NVME harmless issues

---

tools/sof-kernel-log-check.sh

Our reviews and CI missed the mistake with missing brackets leading to
the following warning:
grep: character class syntax is [[:space:]], not [:space:]

sof-kernel-log-check: fix regexp used to filter out NVME harmless issues

---

case-lib/hijack.sh

This failure is just too frequent on Zephyr, downgrade it to a SKIP.

Downgrade Zephyr DMA trace corruption 5352 to a SKIP

---

test-case/check-suspend-resume.sh

Various suspend/resume fixes

---

case-lib/hijack.sh

Commit 27ae3281564b ("Downgrade Zephyr DMA trace corruption 5352 to a
SKIP") downgraded sof-logger failures to SKIPs. Unfortunately, it also
downgraded real failures. Check the current exit_status to see if a real
failure was already found and don't downgrade it.
Fixes #901

hijack.sh: don't downgrade real fails together with sof-logger failures

---

case-lib/lib.sh

function grep_firmware_info_in_logs helps us to get information of firmware including its version conveniently.
As for IPC4, the keyword is "firmware version" instead of "Firmware info". So add the keyword for catch fw version under
IPC4 mode.
This will affect the console output of testcase verify-sof-firmware-load.sh and it can help us to tell whether cavs fw or sof fw is actually used.
**its effects**
[dmesg]
```
ubuntu@sh-tglu-rvp-hda-zephyr-02:~/sof-test$ TPLG=/lib/firmware/intel/avs-tplg/cavs-mixin-mixout-hda.tplg MODEL=TGLU_UP_HDA_CAVSIPC4 ~/sof-test/test-case/verify-sof-firmware-load.sh
2022-05-11 11:10:03 UTC [INFO] Checking SOF Firmware load info in kernel log
[    3.671067] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: firmware boot complete
May 11 09:10:45 kernel: …
```

lib.sh: Dump fw version for IPC4

---

test-case/check-suspend-resume.sh

This will help when we have a lot of USB errors like in
https://sof-ci.01.org/softestpr/PR906/build27/devicetest/?model=WHL_UPEXT_HDA_ZEPHYR&testcase=check-suspend-resume-with-playback-5
Example before:
```
$ lsusb  -t
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/6p, 10000M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/12p, 480M
|__ Port 10: Dev 6, If 0, Class=Wireless, Driver=, 12M
|__ Port 10: Dev 6, If 1, Class=Wireless, Driver=, 12M
```
Example after:
```
$ lsusb -tvv
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/6p, 10000M
ID 1d6b:0003 Linux Foundation 3.0 root hub
/sys/bus/usb/devices/  /dev/bus/usb/002/001
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/12p, 480M
ID 1d6b:0002 Linux Foundation 2.0 root hub
/sys/bus/usb/devices/usb1 …
```

check-suspend-resume: lsusb -t  ->  lsusb -tvv

---

case-lib/lib.sh

This is becoming required because Zephyr logging is adding another layer
of complexity, See for instance
https://github.com/thesofproject/sof-test/pull/897 work in progress.

lib.sh: add detailed description of func_lib_start_log_collect() 

---

tools/kmod/sof_insert.sh

Add top mtl pci module.
I should have added this my previous PR, https://github.com/thesofproject/sof-test/pull/896. At that time I addressed only the error I have, sorry about the miss.

kmod: add mtl pci module

---

case-lib/hijack.sh
case-lib/lib.sh

We've experienced a fair number of test failures that seem to point to
storage performance issues:
https://github.com/thesofproject/linux/issues/3387
https://github.com/thesofproject/linux/issues/3669
This (temporary?) addition runs a quick write test after each audio test
to monitor storage sanity.
As a bonus feature the "sync" could help us collect more logs.
On our (slowest) BYT devices the test adds 3s per test; much less on
newer devices.
Sample output:
```
2022-05-24 23:20:41 UTC [INFO] pkill -TERM sof-logger
2022-05-24 23:20:42 UTC [INFO] nlines=1132 /home/mherber2/SOF/sof-test/logs/BOGUS-check-playback/2022-05-24-16:20:35-3288/slogger.txt
+ timeout -s CONT 5 sudo sync
real	0m0.062s
user	0m0.005s
sys	0m0.019s
+ timeout -s CONT 10 dd if=/dev/zero of=/home/mherber2/HD_TEST_DELETE_ME …
```

hijack: add a quick write test to monitor storage perf. after each test

---

test-case/check-sof-logger.sh

This would have caught kernel crash
https://sof-ci.01.org/linuxpr/PR3645/build166/devicetest/?model=CML_RVP_SDW_ZEPHYR&testcase=check-sof-logger
This check is especially important considering check-sof-logger unload
and reloads kernel modules.

check-sof-logger: add missing sof-kernel-log-check.sh

---

case-lib/config.sh
case-lib/pipeline.sh

Previously, if SOF card is not detected from the system,
we will export pipelines from proc file system, this is
good for legacy HDA test, but for SOF test, this causes
false positive because usually under this condition, we
are testing USB sound card or Nvidia HDMI.
This patch adds an option to control the fallback behavior,
It should be set to 'false' for SOF test,  and set to 'true'
for legacy HDA test.

case-lib: add an option to control fallback behavior

---

case-lib/hijack.sh
case-lib/lib.sh
case-lib/logging_ctl.sh

This solves two major and recurring problems:
- Double CI reservations where a surprising number of tests pass anyway and
the rest fails in extremely time consuming ways. Now only one test can
run at a time.
- Missing correlation between journalctl and test start/stop. Inability
to find when tests start and stop.
- Missing correlation between ktime used in dmesg and wallclock
Sample, new journalctl output:
```
May 31 17:58:56 [8007]: /tmp/sof-test-card0.lock already taken by PID 6147! Starting 7976 anyway.
May 31 17:58:56 [8011]: sof-test 7976 starting
May 31 18:00:09 [8361]: /tmp/sof-test-card0.lock already taken by PID 6147! Starting 8329 anyway.
May 31 18:00:09 [8365]: sof-test 8329 starting
May 31 18:00:34 [8533]: sof-test 8502 starting
May 31 18:00:38 [8638]: sof-test 8502 ending
May …
```

Add mutual exclusion and journalctl logging

---

case-lib/lib.sh

There has been a number of test runs failing with a sync duration just
slightly over 5s. I think 5+ seconds is wrong and should not happen but
we have bigger problems right now, let's revisit and lower this back
later.

lib.sh: increase max `sync` duration from 5s to 7s

---

test-case/check-suspend-resume.sh

When the wakeup count gets totally stuck it's possible for the
wakeup_sources to stay completed unchanged. See example at
https://sof-ci.01.org/sofpr/PR5884/build560/devicetest/?model=TGLU_UP_HDA_ZEPHYR&testcase=check-suspend-resume-5
In that case only the header of wakeup_sources gets printed which gives
the wrong impression that wakeup_sources is completely empty! The
`--report-identical-files` diff option avoids that confusion.

check-suspend-resume: diff wakeup_sources with --report-identical-files

---

test-case/check-suspend-resume.sh

This should help identifying suspend/resume issues unrelated to audio
2 commits must be reviewed separately

check-suspend-resume: add new -u option to test without audio

---

.gitignore
kernel_tracing/bpftrace_scripts/hda_irq_source_counts.bt
kernel_tracing/bpftrace_scripts/hda_irq_source_deltas.bt
kernel_tracing/bpftrace_scripts/ipc_tx_time.bt
kernel_tracing/bpftrace_scripts/suspend_resume_time.bt
kernel_tracing/metric_evaluation/conftest.py
kernel_tracing/metric_evaluation/no_dependencies.json
kernel_tracing/metric_evaluation/readme.md
kernel_tracing/metric_evaluation/sample_shell.sh
kernel_tracing/metric_evaluation/sample_spec.json
kernel_tracing/metric_evaluation/simple_bpftrace.bt
kernel_tracing/metric_evaluation/test.py
kernel_tracing/readme.md
python-deps.txt

Signed-off-by: Noah Klayman <noah.klayman@intel.com>
This PR adds some example [bpftrace](https://github.com/iovisor/bpftrace) scripts to track performance and behavior of various SOF functions in the kernel. To run them, you'll need to [install bpftrace](https://github.com/iovisor/bpftrace/blob/master/INSTALL.md), then run the script with `bpftrace [path to script]`. If you want to use the hda_irq scripts, you'll need to be running [this kernel pr](https://github.com/thesofproject/linux/pull/3482).
Example output from `suspend_resume_time.bt`:
```shell
❯ bpftrace ./kernel_tracing/bpftrace_scripts/suspend_resume_time.bt
Attaching 5 probes...
kprobe:sof_resume (runtime) started
kretprobe:sof_resume (runtime) finished, took 132135788 nsecs
kprobe:sof_suspend (system) started …
```

 add bpftrace scripts to track performance and behavior of SOF functions in the kernel

---

case-lib/lib.sh

See failures in daily run 13851.

lib.sh: storage_check: add 'cht' (BSW Cyan) to slow devices

---

tools/kmod/sof_insert.sh
tools/kmod/sof_remove.sh

This depends on PR: https://github.com/thesofproject/sof-test/pull/926

[RFC]: Add i.MX tests for module insert/removal

---

test-case/check-pause-release-suspend-resume.sh

3 commits, check messages.
Note this test seems orphaned, it was notably broken by commit
https://github.com/thesofproject/sof-test/commit/46dadd0c563e6caa0c01c4acec6caf4bdfc30d7f ("Add mutual exclusion and journalctl logging") and no one
noticed (I temporarily disabled https://github.com/thesofproject/sof-test/commit/46dadd0c563e6caa0c01c4acec6caf4bdfc30d7f locally)

check-pause-release-suspend-resume: small fixes

---

case-lib/lib.sh
tools/sof-get-default-tplg.sh

The reason for this is to allow the tests based on journalctl -g "some string" to run on i.MX platforms. At this moment, running
journalctl -q -k -g "loading" results in the following error: Compiled without pattern matching support.

[RFC]: Pipe journalctl command to grep instead of using the -g option

---

kernel_tracing/measure_function_time.py

uses bpftrace under the hood to track avg, min, max, and generate histogram
Sample output:

[SKIP CI] kernel_tracing: add script to track execution time of any function in kernel

---

kernel_tracing/bpftrace_scripts/hda_irq_source_deltas.bt
kernel_tracing/bpftrace_scripts/ipc_tx_time.bt
kernel_tracing/bpftrace_scripts/suspend_resume_time.bt

Removes high-volume printing and captures nsecs at probe entry

[SKIP CI] kernel_tracing/bpftrace_scripts: improve timing accuracy and reduce overhead

---

case-lib/hijack.sh
test-case/check-ipc-flood.sh
tools/sof-kernel-dump.sh

Overriden commands should work exactly like real commands and support
whitespace and special characters exactly like the real command.
I usually disable the sudo() override locally when using `set -x`
to reduce trace noise considerably. The previous difference between the
sudo() override and the built-in sudo() cost me couple hours twice:
- WIP https://github.com/thesofproject/sof-test/pull/897#discussion_r928074591
- Merged commit 232d40ae3e0a73
No more!
Also fix the return value: 2 means SKIP.

Fix hijack.sh sudo() to use an array, support whitespace and behave

---

case-lib/lib.sh
test-case/check-sof-logger.sh

Add function find_logger_error() in case-lib so it can re-used by other
tests later.

check-sof-logger: catch ERROR in firmware traces and fail

---

case-lib/lib.sh

Our EHL system uses eMMC and fails the "fast" storage
check from time to time. See internal issue 280 and
daily results 14411

lib.sh: add EHL to the list of "slow storage" systems

---

tools/kmod/sof_remove.sh

snd_soc_sst_broadwell module is renamed to snd_soc_bdw_rt286 on the kernel side. Add new entry while keeping the old one to not break the compatibility with older kernel versions.

kmod: Add bdw_rt286 module to the removal list

---

case-lib/lib.sh

2 commits. Main one:
Use -w to catch the words 'ERR' and 'ERROR' and avoid unrelated words
like 'ovERRuns' (unless of course they're prefixed with ERROR)
Fixes recent commit https://github.com/thesofproject/sof-test/commit/87aeb4d5eb79e5200581d444b0c19882d8b27bc8 ("check-sof-logger: catch ERROR in
firmware traces and fail")
Add -i: no reason to catch errors only in upper case.
Log the grep commands using set -x

lib.sh: fix recent check_error_in_file() . Exclude BSW

---

case-lib/lib.sh
test-case/check-sof-logger.sh

2 commits, main one:
check-sof-logger.sh: minor message adjustment for cavstool
cavstool does not use stderr for errors but to make the difference
between local logs and remote logs. Adjust the message accordingly.
Fixes commit https://github.com/thesofproject/sof-test/commit/d6c0e76eacbf0d37310ce59a9e78ca2e7d351b8a ("check-sof-logger: add cavstool support")
EDIT: https://sof-ci.01.org/softestpr/PR950/build120/devicetest/ all green.

check-sof-logger.sh: minor message adjustment for cavstool

---

tools/tplgtool2.py

Previously, parsing `cavs-tgl-nocodec.tplg` got stuck because it treat the NHLT table in the manifest private data as a vendor array and didn't catch the unexpected vendor tuple types.
These 2 parts to fix it and improve soundness:
1. parse vendor array for DAPM widgets only
2. raise error for unknown vendor types

tplgtool2: parse vendor array for DAPM widgets only and raise error for unknown vendor types 

---

tools/sof-kernel-log-check.sh

CI detected various of mei_me errors on different platforms
specific mei_me error filters cannot cover so many variants
This patch unifys the filters to skip all of them.
Signed-off-by: Keqiao Zhang <keqiao.zhang@intel.com>

sof-kernel-log-check: unify error filters for mei_me module

---

tools/kmod/sof_remove.sh

With the addition of the AVS drivers in the default config, the kmod insert/remove tests are now broken
RMMOD	snd_hda_ext_core
rmmod: ERROR: Module snd_hda_ext_core is in use by: snd_soc_avs snd_soc_hda_codec
Make sure thse drivers are removed ahead of time.
Link: https://sof-ci.01.org/linuxpr/PR3881/build841/devicetest/

kmod: remove avs drivers

---

test-case/check-sof-logger.sh

The test started failing with recent Zephyr upstream due to combination of use of "asyncio.get_event_loop().run_until_complete(main())" in cavstool.py , which triggers a deprecation warning on Python 3.10 and newer.
Make the cavstool check more robust by checking for multiple lines of text in cavstool output for the tool banner.
Suggested-by: Marc Herbert <marc.herbert@intel.com>

check-sof-logger: fix cavstool banner check

---

case-lib/lib.sh
test-case/check-sof-logger.sh

Add support for "mtrace" debugfs interface implemented by SOF driver when it is used in IPC4 mode. Use this instead of cavstool.py.
BugLink: https://github.com/thesofproject/sof-test/issues/970

check-sof-logger: add support for mtrace log with IPC4

---

case-lib/config.sh
case-lib/pipeline.sh

On some new platform, the DMIC support is not ready at the early stage, add an option to disable the DMIC pipelines.
Signed-off-by: Keqiao Zhang <keqiao.zhang@intel.com>

test: add an option to skip the DMIC pipelines

---

tools/sof-dump-status.py

sof-dump-status.py: add ADL-N PCI DID

---

case-lib/lib.sh

Previously we do a lot of test to get the firmware path, it is not necessary, because we can acquire it simply with journalctl.   Then we can test if the firmware loaded is using zephyr rtos by checking the occurrence of 'zephyr' in the firmware binary as before.
First (maybe the only) step to unlock sof-test for mtl

lib.sh: simplify the check for firmware rtos

---

tools/sof-kernel-log-check.sh

Errors are thrown in suspend-resume tests on initial RPL device, filter out.
Fixes: https://github.com/thesofproject/sof-test/issues/980

sof-kernel-log-check: filter out i2c_hid_acpi issue on RPL

---

test-case/check-alsabat.sh

Lower the default test frequency from 997Hz to 821Hz. Most SOF topologies use 1000Hz tick rate, and test frequency close to this scheduling frequency can mask certain type of errors (like SOF bug
Link: https://github.com/thesofproject/sof/issues/6709
Suggested-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>

check-alsabat.sh: use 821Hz as default test frequency

---

test-case/verify-kernel-boot-log.sh

DISPLAY=:0 xrandr --listmonitors is not reliable anymore, see
- https://github.com/thesofproject/sof-test/discussions/964
Keep it anyway because it works on older Ubuntu and probably many other Linux distributions too.

verify-kernel-boot-log.sh: add grep i915_display_info on failure

---

tools/sof-kernel-log-check.sh

The ISH issues often happened on MTL RVP recently, it's not related to audio, so we can safely filter it out.
Fixes: https://github.com/thesofproject/sof-test/issues/857
Signed-off-by: Yong-an Lu <yongan.lu@intel.com>

sof-kernel-log-check: filter out ISH issues

---

test-case/check-signal-stop-start.sh

When aplay or arecord process is terminated during the test, while loop condition catches the error first then just return the function. In this case it ends up with a false pass.
Removed the process check from while loop. sof-process-state.sh will do it anyway.
issue link: https://github.com/thesofproject/sof-test/issues/988

check-signal-stop-start.sh: report failure when process terminated early

---

test-case/verify-kernel-boot-log.sh

`grep something missing_file` returns 2. When the file is missing this is misinterpreted as SKIP as seen in daily test run 20752. This happens because the grep is the last command in the subshell.
The `grep /sys/kernel/debug/dri/0/i915_display_info` and the including subshell are not part of the test; ignore their exit code and let the rest of the test code decide what the exit value of the test is.
Fixes commit aadd7707cb261

verify-kernel-boot-log.sh: don't SKIP when i915 is missing

---

tools/kmod/sof_remove.sh

We already dealt with an earlier dependency to fix this problem: rmmod: ERROR: Module snd_hda_ext_core is in use by: snd_sof_intel_hda_mlink
However with PR https://github.com/thesofproject/linux/pull/4200 we use this hda_mlink module, which creates another dependency:
rmmod: ERROR: Module snd_sof_intel_hda_mlink is in use by: soundwire_intel
The 'right' order to remove modules seems to be:
soundwire_intel
snd_sof_intel_hda_mlink
snd_hda_ext_core

kmod: fix dependency order

---

test-case/verify-kernel-boot-log.sh

re_enable_ntp_sync will trigger ntp sync immediately, but it may take some time due to network delay. Some delay is required before checking ntp sync again.
@plbossart found the failure.
https://sof-ci.01.org/linuxpr/PR4209/build3362/devicetest/index.html?model=TGLU_RVP_SDW_IPC4ZPH&testcase=verify-kernel-boot-log
@marc-hb left the comment long back ago, I looked down the point.
https://github.com/thesofproject/sof-test/pull/779#discussion_r1115155292

verify-kernel-boot-log.sh: add delay before checking NTP sync

---

case-lib/lib.sh
test-case/check-alsabat.sh
test-case/check-fw-echo-reference.sh

alsabat always returns -2 for "C.UTF-8" locale. Suggest user set locale to "C.utf8" to avoid this issue.
see https://github.com/alsa-project/alsa-utils/issues/192
Signed-off-by: Yong-an Lu <yongan.lu@intel.com>

lib: check locale for alsabat

---

test-case/check-alsabat.sh

The default parameter sigma k is 3.0 when omitted from command line. This patch drops the threshold to half with 1.5 to better detect distortion in playback. Alsabat judges spectral components above the threshold as sine frequencies.
This change should increase the probability fail a test to avoid green failures to happen.
Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>

test-case: check-alsabat.sh: Lower the threshold for detecting tones

---

test-case/check-alsabat.sh

add a -f option to support audio format.

check_alsabat.sh: add format support

---

test-case/check-alsabat.sh

The value 1.5 has caused a false failure possibly due to noise in the test device output. Value 2.1 gives a small relaxation and passes the previously failed capture.
Fixes 92fe8a1c7cf465dc3820f538f09739754c65e08e

Test-case: Relax sigma-k parameter in check-alsabat.sh

---

test-case/check-keyword-detection.sh
tools/sof-tplgreader.py
tools/tplgtool.py

Yongan has a new version of tplgtool2.py, and we are supposed to do a new sof-tplgreader.py based on tplgtool2.py, however, no one has time for it. the old sof-tplgreader.py and tplgtool.py are still used.
So this patch does the improvement based on old python scripts, to make the pipeline filter better for IPC4. 
The main purpose is to filter out wov capture pipeline in normal capturing. so this is needed before adding wov pipeline to ipc4 nocodec topology

Improve topology python scripts for ipc4

---

.github/workflows/pull_request.yml
python-deps.txt

This will upgrade shellcheck and pylint.

[SKIP CI] .github: upgrade runners from Ubuntu 20.04 to 22.04

---

case-lib/hijack.sh

Fixes warning found in
https://github.com/thesofproject/sof-test/actions/runs/4635603962/jobs/8202801248?pr=1018 testing PR #1018
See inline comments. Fixes commit 0ccb4c80d2f8716 ("hijack.sh: more generic way to disable unknown $logfile shellcheck")
Different shellcheck versions may warn about this fake definition differently but life is too short to compare them, just disable both SC2154 and SC2269

hijack.sh: properly disable shellcheck on fake logfile=$logfile 

---

case-lib/hijack.sh

SOF_LOGGING=none means no logger log. This condition must be checked before the other conditions.

hijack: don't collect logger if SOF_LOGGING=none

---

test-case/multiple-pause-resume.sh

Now shellcheck clean before #1025

multiple-pause-resume.sh: fix two minor quote warnings

---

alsa_settings/MTLP_RVP_SDW.sh

Overall amplitude of the captured waveform is about 50%.
tested with https://github.com/thesofproject/linux/pull/4295

alsa_settings: change amixer settings for MTLP_RVP_SDW

---

case-lib/lib.sh
test-case/multiple-pipeline.sh

-f option was introduced to decide whether to fill the pipeline with
playback or capture first. But it causes more confusion. Now still keep
-f option, but to simplify the pipeline mode option.
playback mode : only plyaback pipeline
capture mode : only capture pipelines
all mode : run both playback and capture pipelines
Simple usage example:
* playback pipelines only
multiple-pipeline-playback.sh # playback with default values
multiple-pipeline-playback.sh -c 5 -l 15
or
multiple-pipeline.sh -f p -c 5 -l 15
* capture pipelines only
multiple-pipeline-capture.sh # capture with default values
multiple-pipeline-capture.sh -c 5 -l 15
or
multiple-pipeline.sh -f c -c 5 -l 15
* all pipelines, set pipeline count large enough (SOF CI need to change the command from '-f p' to '-f a') …

multiple-pipeline: simplify testing options with playback/capture/all 

---

case-lib/config.sh
case-lib/lib.sh

This is going to check whether the sof-test can be started after boot/reboot.
If FW LOADING is not a prerequisite for the test, this can be skipped, by defining NO_POLL_FW_LOADING=true
Another benefit with this change, if FW is not loaded it will be failed instead of TIMEOUT.

lib: wait for fw loaded before starting any test

---

tools/sof-kernel-log-check.sh

Filter out new log:
[  971.469391] kernel: tpm tpm0: Operation Canceled
Link: https://github.com/thesofproject/sof-test/issues/986

sof-kernel-log-check: filter out TPM operation cancelled

---

tools/tplgfw-sanity-check.py
tools/tplgtool2.py

With increasing number of processing components, we could sanity check the topology against the firmware rather than having a cryptic IPC failure when the topology requests a component not in the firmware.
This PR reuses the tplgtool2.py for topology parsing
usage: tplgfw_sanity-check.py [-h] [--version] -t T [T ...] -f F [F ...] [-v]
tplgfw-sanity-check.py -t sof-tgl-nocodec.tplg -f basefw.bin
It is for [FEATURE] Allow topologies to manifest and sanity check component IDs https://github.com/thesofproject/sof/issues/3871
two examples:
ipc4 topology + ipc4 fw:
./tplgfw_sanity_check.py  -t  /home/rander/sof-tgl-nocodec.tplg -f /home/rander/sof-tgl.ri 
FW header Container: 
id = u'$AE1' (total 4)
len = 1580
version_major = 1
version_minor = 0
module_entries = 15 
IPC4 supported FW
This FW …

tools: add a tool to do sanity check for topology and firmware

---

test-case/check-capture.sh

Per issue https://github.com/thesofproject/sof-test/issues/729, "Fix all shellcheck warnings".
Prior to this commit there were 13 issues in this file, now there are none.
check-capture.sh was run before and after the fixes, no change in output.
Signed off by Greg Galloway [greg.galloway@intel.com](mailto:greg.galloway@intel.com)

check-capture.sh: fix quoting and "ret=$?" warnings

---

test-case/check-kmod-load-unload-after-playback.sh

Fixes per ticket https://github.com/thesofproject/sof-test/issues/729
Six issues to zero.
Fixed the source reference to match that of other repos.  Fixed a single quote issue (a single quote block contained a variable).
Signed off by Greg Galloway [greg.galloway@intel.com](mailto:greg.galloway@intel.com)

check-kmod-load-unload-after-playback.sh: fix source reference and quote issues.

---

test-case/simultaneous-playback-capture.sh

Fix shellcheck errors per https://github.com/thesofproject/sof-test/issues/729
Corrected a source reference. Fixed various quoting issues.  Corrected exit codes and updated syntax.

Simultaneous playback capture shellcheck fixes

---

test-case/volume-basic-test.sh

SC2207: Prefer mapfile or read -a to split command output (or quote to avoid splitting).
Rewrote line to use the mapfile command.
SC2001: See if you can use ${variable//search/replace} instead. Rewrote volctrl assignment to use built-in string search/replace.
Adjusted quoting on line 22 to display $TPLG.

volume-basic-test.sh: Shellcheck fixes.

---

test-case/verify-kernel-module-load-probe.sh

SC1091 (info): Not following: ./../case-lib/lib.sh: openBinaryFile: does not exist (No such file or directory)
Fixed lib.sh reference to be recognized by shellcheck.
SC2181 (style): Check exit code directly with e.g. 'if ! mycmd;', not indirectly with $?.
Rewrote lsmod/grep conditional to check exit status directly. As previously written, and with set -e, the program flow on a grep failure would never reach the $? -ne 0 check.
Removed unnecessary "exit 0" from end of script.

verify-kernel-module-load-probe.sh: Shellcheck fixes.

---

case-lib/config.sh
case-lib/lib.sh

We don't want to wait for 70s in every test on every platform when the firmware does not load. When multiplied by the number of tests in a plan this can cause a considerable waste of hardware resources.
i915 timeout aside, 10s has proved over a long period to be more than enough.
Fixes: #1059

lib.sh: make MAX_WAIT_FW_LOADING platform dependent

---

test-case/check-kmod-load-unload.sh

We already have a parameter for boot timeouts, let's use it. This enables kmod tests on MTL RVP.
Closes: https://github.com/thesofproject/sof-test/issues/1037

check-kmod-load-unload: remove hard-coded 10s timeout

---

test-case/check-suspend-resume-with-audio.sh

Various shellcheck fixes, including quoting, source references and pgrep.
Work done under ticket https://github.com/thesofproject/sof-test/issues/729

Shellcheck check suspend resume with audio

---

test-case/check-volume-levels.sh

Three instances of...
SC2295 (info): Expansions inside ${..} need to be quoted separately, otherwise they match as patterns.
Added quotes to $search in this line:
`CAP_SWITCH=${tmp#*$search}` -->  `CAP_SWITCH=${tmp#*"$search"}`
Tested/verified on jf-adlp-rvp-nocodec-8

check-volume-levels.sh: Shellcheck fixes.

---

case-lib/hijack.sh
case-lib/lib.sh
test-case/check-sof-logger.sh

3 commits
Preparation for #1075, only one small functional change: counting the number of lines in mtrace.txt

Small log collection refactor to prepare catching fw errors

---

alsa_settings/GLK_BOB_DA7219.sh

Headphone Volume is set too low. 0db is most common setting but I set intentionally 3 db lower for safety.
For Headphone Volume for the device,
34 is -23db
54 is -3db
57 is 0db
Before with 34
After with 54

alsa_settings: increase gain on headphone volume on GLK

---

test-case/verify-tplg-binary.sh

SC2006: Use $(...) notation instead of legacy backticked `...`. 
SC2181: Check exit code directly with e.g. 'if mycmd;', not indirectly with `$?`. 
Rewrote the tplg_path assignment to use `$( )` and to not compare against `$?`
SC2086: Double quote to prevent globbing and word splitting. 
Rewrote some tplg_path references to be double-quoted.

verify-tplg-binary.sh: Shellcheck fixes.

---

test-case/volume-basic-test.sh

This (1) provides some logging (2) avoids `skip_test` if amixer fails

volume-basic-test.sh: catch amixer failures and log all controls

---

tools/sof-kernel-log-check.sh

This patch will ignore CPU the stepping warning after boot.

sof-kernel-log-check.sh: add a filter for Dell TGLH

---

test-case/verify-tplg-binary.sh
tools/tplgtool2.py

3 commits. Main one:
------
verify-tplg-binary.sh: create .png in $LOG_ROOT instead of /tmp
It's better next to the "other" logs. Also means there's a single, usual
place to clean up.
We'd rather not create it at all but it's not optional.

verify-tplg-binary.sh: create .png in $LOG_ROOT instead of /tmp

---

test-case/check-sof-logger.sh

The is_zephyr check looks at the number of 'zephyr' strings in the LDC file while the is_firmware_file_zephyr is doing the same on the actual firmware file.
It has been observed that the is_zephyr function can get the detection wrong and reports false for a zephyr firmware.
Note also that virtually only the check-sof-logger is using the is_zephyr call, all other test cases use the is_firmware_file_zephyr call.

check-sof-logger: Switch to use is_firmware_file_zephyr

---

test-case/test-speaker.sh

The speaker test fails with -t wav internally for other than "-r 48000" because it is not re-sampling the wav "Front center" etc. clips. Using pink noise for non-48 kHz works around this limitation and allows to test with all sample rates. Also the test are not depending on spoken channels names. Channels order can be subjectively checked with the 48 kHz test.

Test-case: test-speaker.sh: Use pink noise for non-48 kHz rates

---

tools/sof_perf_analyzer.py

This patch adds the initial version of SOF mtrace
analyzer. The initial version of the analyzer is
able to output the performance statistics per module, for example:
```
COMP_NAME  COMP_ID     AVG_OF_CPU_AVG   AVG_OF_CPU_PEAK  PEAK_OF_CPU_AVG  PEAK_OF_CPU_PEAK
mixout.2.1  1-0x30000   2.29             3.12             2.30             12.67          
gain.2.1  1-0x60001   2.58             3.38             2.69             9.43           
dai-copier.HDA.Analog.playback  1-0x40001   4.78             4.90             4.79             4.96           
host-copier.0.playback  0-0x40000   4.31             4.47             4.31             4.91           
gain.1.1  0-0x60000   2.55             3.71             2.71             9.52           
mixin.1.1  0-0x20000   3.56             3.65 …
```

tools: add the initial version of trace analyzer

---

case-lib/lib.sh

We need to follow the `/sys/module/snd_sof_pci/parameters/fw_path` flexibility to test the firmware as whole /lib/firmware package and to stop copying files into /etc/sof/

lib.sh: add get_ldc_subdir() that follows /sys/module/snd_sof_pci/parameters/fw_path

---

case-lib/hijack.sh
case-lib/lib.sh
test-case/check-performance.sh

based on https://github.com/thesofproject/sof-test/pull/1064, add a test case for performance check
```
2023-08-16 06:33:37 UTC [INFO] ktime=524 sof-test PID=2513: starting
2023-08-16 06:33:37 UTC [INFO] Starting /usr/local/bin/mtrace-reader.py >& /home/ubuntu/sof-test/logs/check-performance/2023-08-16-06:33:36-7734/mtrace.txt &
2023-08-16 06:33:37 UTC [INFO] /home/ubuntu/sof-test/test-case/check-performance.sh will use topology /usr/lib/firmware/intel/sof-ace-tplg/sof-hda-generic-4ch.tplg to run the test case
2023-08-16 06:33:37 UTC [INFO] Pipeline list to ignore is specified, will ignore 'pcm=HDA Digital' in test case
2023-08-16 06:33:37 UTC [INFO] Run command to get pipeline parameters
2023-08-16 06:33:37 UTC [COMMAND] sof-tplgreader.py …
```

Add test case for sof component performance check

---

test-case/check-performance.sh

The error won't be reported if process exit unexpectedly, add error handling code for this.

test-case: add more error handling for check-performance

---

tools/sof_perf_analyzer.py

Previously, component ID in mtrace and kernel
is different, which makes it hard to find the
component from kernel message with a component
ID from mtrace. After it is fixed in SOF side,
now module_id take the first 16 bits, instance_id
takes next 8 bits. We should do a fix accordingly.
Link: https://github.com/thesofproject/sof/issues/8051

tools: sof_perf_analyzer: fix component ID

---

case-lib/lib.sh
tools/sof_perf_analyzer.py

Two commits:
- support to output csv for performance data in sof_perf_analyzer
- enable the feature in sof-test case
An example of CSV output: [sof_perf.csv](https://github.com/thesofproject/sof-test/files/12519387/sof_perf.csv)

add support to output sof performance data to csv

---

case-lib/lib.sh

Our sof-ci web cannot recognize csv file,
so on opening the test result, the csv file
will be downloaded. Change the file suffix
to txt, so that we can view it in the web.

lib.sh: use txt suffix for csv file

---

tools/tplgtool2.py

This patch adds support to show widget CPC value
int topology graph.

tplgtool2.py: show widget CPC in topology graph

---

case-lib/lib.sh

rt1011 i2c-10EC1011:00 needs about 10 seconds to boot every time on cml-hel-rt5682, see evidence in #1095
```
21:59:16 snd_sof:ipc3_log_header: sof-audio-pci-intel-cnl 0000:00:1f.3: ipc tx: 0x30130000: GLB_TPLG_MSG: PIPE_COMPLETE
21:59:16 snd_sof:sof_ipc3_complete_pipeline: sof-audio-pci-intel-cnl 0000:00:1f.3: tplg: complete pipeline PIPELINE.1.SSP0.OUT id 5
21:59:16 snd_sof:ipc3_log_header: sof-audio-pci-intel-cnl 0000:00:1f.3: ipc tx: 0x30130000: GLB_TPLG_MSG: PIPE_COMPLETE
21:59:16 snd_hda_codec_hdmi ehdaudio0D2: ASoC: sink widget AIF1TX overwritten
21:59:16 snd_hda_codec_hdmi ehdaudio0D2: ASoC: source widget AIF1RX overwritten
21:59:16 rt1011 i2c-10EC1011:00: ADC offset=0x0
21:59:16 rt1011 i2c-10EC1011:00: Gain0 offset=0x1ffeea
21:59:16 rt1011 i2c-10EC1011:00: Gain1 offset=0x1ffed2 …
```

lib.sh: increase MAX_WAIT_FW_LOADING to 13s for CML

---

case-lib/lib.sh
tools/sof_perf_analyzer.py

In CI test, some traces from previous test case will apprear in the mtrace of current test case, this is a know issue.
Previously, we always skip to the first valid trace of this test case, this could raise trouble for developer use of this script.
This patch adds skip-to-first-trace option, for CI test, this option should be set (True), and for developer use, this option should be left as it is (False).

sof_perf_analyzer: add skip-to-first-trace option

---

test-case/check-sof-logger.sh

The DSP boot check reload_drivers() must wait longer than 5 seconds as we have many configurations where DSP boot will take more than 60sec (due to e.g. Intel platforms with i915 hardware present but driver not present in the kernel version under test).
Additionally the test case must check whether DSP did boot up after the timeout expires, and fail the test case if it didn't.

check-sof-logger: fix the DSP boot check

---

case-lib/lib.sh

Outside known issues we want to know when the firmware takes unusually long to load.

start_test(): reduce default MAX_WAIT_FW_LOADING to 3s

---

tools/tplgtool2.py

Make print_pcm_info() show all supported formats of a PCM. The alignment and order of PCM attributes are also adjusted.
Update history:
v2: use fmts = ' '.join(fmt_list[cap_index]) to get all supported formats
follow previous "key=value;"  format for PCM ID and name.
make PCM name right-aligned to the longest PCM name
Example: sof-mtl-max98357a-rt5682-ssp2-ssp0-2ch-pdm1.tplg
Before change:
```
pcm=Headset;id=0;type=duplex;fmt=S16_LE;rate_min=48000;rate_max=48000;ch_min=2;ch_max=2;
pcm=Speakers;id=1;type=playback;fmt=S16_LE;rate_min=48000;rate_max=48000;ch_min=2;ch_max=2;
pcm=Bluetooth;id=2;type=duplex;fmt=S16_LE;rate_min=8000;rate_max=48000;ch_min=1;ch_max=2;
pcm=HDMI1;id=5;type=playback;fmt=S16_LE;rate_min=48000;rate_max=48000;ch_min=2;ch_max=8; …
```

tplgtool2: print all supported formats of PCM and adjust alignment

---

case-lib/hijack.sh
case-lib/lib.sh
test-case/check-sof-logger.sh

Add initial support for handling MIPI Sys-T Cat logging in SOF firmware:
- identify FW that emits logging in Sys-T Cat dictionary format
- use systprint tools to decode logs  ( https://github.com/MIPI-Alliance/public-mipi-sys-t )
- no flag day needed, this PR is compatible with other logging types (so can be merged without dependencies)

Add support for MIPI Sys-T logging

---

test-case/check-sof-logger.sh

The logger test case has a design limitation in that it assumes the SOF DSP to remain powered up between driver reload and start of the logger. This creates a possibility for a race with runtime PM (RPM).
If the DSP goes to runtime suspend during this window, it is not guaranteed that the SOF driver will provide any logs. Some logging mechanisms save the logs that were emitted before suspend (sof-logger/IPC3), but some not (cavstool/IPC3 and mtrace/IPC4).
To limit the window , add a simple ping of all PCM nodes just before logger process is started. This is a crude mechanism but something that works with all variants of SOF. End result is that DSP will be resumed to D0 just before the logger test starts.

check-sof-logger.sh: fix no-log-file failures due to RPM

---

tools/sof_perf_analyzer.py

If kernel message file is not provided, the component_name dict will be empty, in calculating the maximum length of component names, we calls the max function with an empty sequence, which raises below error:
"ValueError: max() arg is an empty sequence"
This patch checks if component_name dict is empty, and on empty, provides a default value.

sof_perf_analyzer: fix exception when kernel message not provided

---

test-case/check-sof-logger.sh

It turns out on some test platforms, the launch of logger processes can take significant amount of time, so the solution to create some DSP activity just before launching the logger processes, is not reliable enough.
Implement alternative solution where the DSP activity is triggered after loggers are started.
Fix tested with a modified mtrace-reader.py that injects arbitrary delays at startup.

check-sof-logger.sh: more robust fix to runtime-PM race

---

tools/sof_perf_analyzer.py

By default, pandas will only show part of the table in printing if the table have a row number greater than display.max_rows, or a column number greater than display.max_columns,
This patch makes sure the whole pandas table is printed by setting display.max_rows and display.max_columns to None in printing context.
Fixes: https://github.com/thesofproject/sof-test/issues/1117

sof_perf_analyzer: fix incomplete pandas table printing

---

case-lib/lib.sh

HTML format is more friendly to CI than csv format. It is easy to read in CI.

lib.sh: generate html instead csv for performance test

---

test-case/verify-kernel-boot-log.sh

We need to catch issues like
https://github.com/thesofproject/sof-test/discussions/998 before they bring the entire system down

verify-kernel-boot-log: add new detect_log_flood()

---

tools/sof_perf_analyzer.py

Previously, module CPC is calculated by multiplying the mean
value of cpu_peak with a margin scalar, after internal technical
discussion, change module CPC to the product of maximum value
of module's cpu_peak and the margin scalar, and change the margin
scalar to 1.1 as aligned.

Change module CPC calculation

---

tools/sof_perf_analyzer.py

In existing code, we parse component name from the line
that contains 'Create widget', and component ID from the
next line, which normally is the ipc tx message:
Create widget host-copier.0.playback instance 0 - pipe 1 - core 0
ipc tx      : 0x40000004|0x15: MOD_INIT_INSTANCE [data size: 84]
However, due to the concurrent nature of linux kernel, the
assumption that `Create widget` message and `ipc tx` message
are always adjacent is wrong. An exception will be raised
if the next line is not the 'ipc tx' message.
The first step to fix the issue is to make a kernel PR to print
all the information we need in a single 'Create widget' line,
thus to avoid the requirement for multiple lines of kernel message, 
see https://github.com/thesofproject/linux/pull/4709.
And next，this patch will parse …

tools: sof_perf_analyzer: fix widget ID parsing error

---

tools/sof-kernel-log-check.sh

Filter out below errors:
[ 8196.630952] kernel: i915 0000:00:02.0: [drm] *ERROR* GT0: GuC initialization failed -ENXIO
[ 8196.630953] kernel: i915 0000:00:02.0: [drm] *ERROR* GT0: Enabling uc failed (-5)
[ 8196.630955] kernel: i915 0000:00:02.0: [drm] *ERROR* GT0: Failed to initialize GPU, declaring it wedged!
Link: https://github.com/thesofproject/linux/issues/4530
cc:
- https://github.com/thesofproject/sof-test/pull/869

sof-kernel-log-check: ignore i915 firmware loading error

---

tools/sof-dump-status.py

Add other PCI device IDs handled by pci-mtl.c.

sof-dump-status: Add ARL and ARL-S PCI IDs

---

tools/sof_perf_analyzer.py

Previously, module CPC is calculated by multiplying the mean value of cpu_peak with a margin scalar, however, abnormal peak cycles are finally proved that it is caused by IRQ, with further team discussion, an agreement was reached to use module average multiplied with a margin as new way for CPC calculation.

tools: sof_perf_analyzer: change module CPC calculation

---

test-case/check-xrun-injection.sh

Previous command line doesn't work on some platforms, it shows that there's no file or directory. This patch refines the commandline to avoid such issue.

check-xrun-injection.sh: refine the xun injection command line

---

case-lib/lib.sh

Useful to check snd_hda_* modules. Especially snd_hda_core module has gpu_bind parameter.

lib.sh: print snd_hda* module params

---

test-case/test-speaker.sh

Unlike other alsa-utils, -f is not used to pass sample format, but instead -F needs to be used. speaker-test also doesn't complain if a sample format is passed to -f, which makes this not so easy to catch (especially as S16_LE works with most PCMs).

test-case: test-speaker.sh: use -F to pass sample format

---

test-case/check-alsabat.sh

This threw me off.
Also add warning that https://manpages.org/alsabat is incomplete and never tells that it is possible to use two separate alsabat instances, nor how to invoke these (answer: omit -P or -C)

check-alsabat.sh: explain that we run two alsabat instances

---

.github/workflows/pull_request.yml

Fixes the following warning showing every time:
> The following actions uses node12 which is deprecated and will be
> forced to run on node16: actions/checkout@v2. For more info:
> https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
Example:
https://github.com/thesofproject/sof-test/actions/runs/7345203885

[SKIP SOF-TEST] .github: upgrade actions/checkout to version 4

---

tools/capture-test.py

Just drop this script on a test device to run it.  No tools to build, no dependencies to install.  Confirmed to run on Python 3.8+ with nothing more than the core libraries and a working libasound.so.2 visible to the runtime linker.
When run without arguments, the tool will record from the capture device for the specified duration, then emit the resulting samples back out the playback device without processing (except potentially to convert the sample format from s32_le to s16_le if needed, and to discard any channels beyond those supported by the playback device).
Passing --chirp-test enables a playback-to-capture latency detector: the tool will emit a short ~6 kHz wave packet via ALSA's mmap interface (which allows measuring and correcting for the buffer latency from the userspace …

[SKIP SOF-TEST] Simple dependency-free ALSA test rig for PCM capture analysis.

---

case-lib/lib.sh

(very different from the initial description)
The --skip-to-first-trace option was added as a precaution to exclude
log pollution from before the start of a test, normally the residue traces are
related to trigger stop IPC, dma put and component reset (as you can see).
There could be 10 ~ 20 lines.
mtrace timestamps used to return to zero on every DSP boot, which --skip-to-first-trace
depends on. After SOF commit 76b0979c6453 ("sync time between host and fw for logging"),
mtrace timestamps still return to zero (briefly) but only on "cold" DSP boots,
not on when booting from IMR. Booting from IMR has now been enabled by default
in most configurations. That combination breaks --skip-to-first-trace.
The only practical short-term solution is to turn off --skip-to-first-trace and take
the risk …

lib.sh: perf_analyze(): drop --skip-to-first-trace

---

case-lib/lib.sh

If sof-test test case is run manually and locally, the output of sof-test is messy, the lines are not aligned left at the beginning of each line, some
lines start in the middle of a line, which makes
the output log hard to follow.
This patch helps to workaround the above issue.
Link: https://github.com/thesofproject/sof-test/issues/1151

lib.sh: Workaround sof-test output alignment issue

---

test-case/test-speaker.sh

The speaker-test "wav" test method supports only 48000Hz and 16bit files. If a topology has a PCM that does not support S16_LE, a different speaker-test method must be used.

test-case: test-speaker.sh: fix test for PCMs that only support 32bit

---

tools/kmod/sof_remove.sh

We need to remove the SoundWire parts before removing hda-sdw-bpt
rmmod: ERROR: Module snd_sof_intel_hda_common is in use by: snd_sof_intel_hda_sdw_bpt
Link: https://sof-ci.01.org/linuxpr/PR4679/build1181/devicetest/index.html?model=MTLP_SDW_AIOC&testcase=check-kmod-load-unload

kmod: fix hda-sdw-bpt dependency

---

tools/sof-kernel-log-check.sh

Newer versions of grep complain about a regexp using a stray backslash in a regexp.
Closes: https://github.com/thesofproject/sof-test/issues/1159

tools/sof-kernel-log-check.sh: remove stray `\`

---

test-case/verify-kernel-boot-log.sh

We started showing part of i915_display_info a long time ago but only when `systemctl is-system-running` failed. Because of recent HDMI issues like https://github.com/thesofproject/linux/issues/4861 and others we want to show more and we want to show it always.

kernel-boot-log.sh: add new show_daemons_session_display()

---

case-lib/lib.sh

First step to remove use of kernel parameters
Link: https://github.com/thesofproject/linux/pull/4902
Link: https://github.com/thesofproject/sof-test/issues/1166

case-lib: is_ipc4: use new debugfs file instead of kernel parameter

---

test-case/test-socwatch.sh

We only use socwatch tool to read the power data for power measurement in this case, we can directly use the latest released version, so there is no need to pre-compile the driver.

test-socwatch.sh: no need to load socwatch module manually

---

case-lib/lib.sh

Apparently debugfs requires more care. Oh well.
Link: https://github.com/thesofproject/sof-test/issues/1171

case-lib/lib.sh: use sudo to access debugfs files

---

README.md
tools/sof-tplgreader.py
tools/tplgtool.py

I was able to test with https://github.com/thesofproject/sof/pull/9017

sof-tplgreader: parse rates from topology file

---

case-lib/hijack.sh
case-lib/lib.sh
test-case/check-kmod-load-unload-after-playback.sh

This is the first step towards fixing:
- #1112 
- #1169

make start_test() optional: part 1

---

case-lib/hijack.sh
case-lib/lib.sh

Final PR at last.
See commit messages.
For a (lot of) context see
- thesofproject/linux#297
... and all the links from there.
cc:
- thesofproject/linux#1046
- https://github.com/thesofproject/sof/issues/4672
- #1173

Catch firmware errors

---

case-lib/hijack.sh
case-lib/lib.sh
test-case/multiple-pipeline.sh

We want to get rid of the .ldc file in Zephyr soon, so change the name of `is_zephyr()` to make it less appealing.
Zero functional change.

Rename is_zephyr() to is_zephyr_ldc(). No functional change.

---

case-lib/lib.sh

Fixes commit 46219fad9ec8 ("case-lib/lib.sh: use sudo to access debugfs files")

lib.sh: need `sudo bash -c ...` to expand `fw_profile/*` as root

---

case-lib/lib.sh

This makes tests fail at the end when mtrace-reader.py could be started, for instance because one is already running (see example below)
Reminder: you can use -s to ignore firmware logs.
```
Traceback (most recent call last):
File "mtrace-reader.py", line 20, in <module>
fd = os.open(MTRACE_FILE, os.O_RDONLY)
OSError: [Errno 16] Device or resource busy: '/sys/kernel/debug/sof/mtrace/core0'
```

lib.sh: catch some mtrace-reader failures to start thanks to "OSError"

---

tools/kmod/sof_remove.sh

Fixes this failure with older kernel like the 6.5 kernels distributed by Ubuntu:
```
ERROR: Module soundwire_intel is in use by: snd_sof_intel_hda_common
```
Fixes commit 65951c4d0 ("kmod: fix hda-sdw-bpt dependency") which unloaded all soundwire drivers earlier as a block. This is not a problem with 6.9-ish kernels where snd_sof_intel_hda_common and soundwire_intel can apparently be unloaded in any order but it is a problem with older kernels.
So, unload `snd_sof_intel_hda_common` before soundwire modules to be compatible with any kernel.
See https://github.com/thesofproject/sof-test/pull/1156 for more info.

sof_remove: unload `snd_sof_intel_hda_common` before `soundwire_intel`

---

test-case/verify-kernel-boot-log.sh

Searching for "(dis)connected" in i915_display_info shows useful connector info.
Also show /sys/class/drm/ and /sys/kernel/debug/dri/0/, this will be useful for DRM_XE, see https://github.com/thesofproject/kconfig/pull/91

verify-kernel-boot-log: add more display information

---

test-case/verify-kernel-boot-log.sh

Fixes commit 7c2ede03c9be ("Explicitly invoke start_test() in every test-case/*.sh") which already did the TODO but _without_ removing _start_test(). We want one or the other, not a strange and unpredictable mix of both!
A future commit will actually replace `start_test()`.

verify-kernel-boot-log.sh hotfix: do not override EXIT handler!

---

case-lib/hijack.sh
test-case/verify-kernel-boot-log.sh

Provide a new, boot_logs.txt file no matter what happens. Note that file now includes user-space logs, not just kernel logs.
Also: fix bug where script times out and does not run when the SOF
firmware is not loaded: no need to define NO_POLL_FW_LOADING anymore.
The trick is to stop calling `start_test()`. verify-kernel-boot-log.sh is not an audio test!
Fixes sof-test issues #1036 and #1112, find more details there.

verify-kernel-boot-log.sh: fix missing boot logs on failure

---

test-case/check-alsabat.sh

amixer settings are always required. good case for reference and bad case for more debugging.

check-alsabat.sh: dump amixer settings always

---

alsa_settings/LNLM_SDW_AIOC.sh

LNL RVP keep toggling between headphone and headset. Overrides to headset only for the test.
Related kernel PR: https://github.com/thesofproject/linux/pull/4969

LNLM_SDW_AIOC.sh: overrides the headset detected_mode

---

test-case/verify-kernel-boot-log.sh

Interleaving could be useful when it's a problem with a sound daemon but tend to turn these off and most of the time it's just making SOF logs harder to read.
Keep boot_log.txt which is useful for all non-audio issues.
Fixes commit c8565e8b210d ("verify-kernel-boot-log.sh: fix missing boot logs on failure")

verify-kernel-boot-log.sh: add "standalone" dmesg.txt back

---

case-lib/hijack.sh

Let's see if we can start paying attention to firmware errors in the stable-v2.2 branch too.
Follow-up to #1075

hijack.sh: fail on stable-v2.2 FW errors too

---

case-lib/lib.sh

i915 does not hang MTL any more, this has been fixed a long time ago.
On the other hand, 70s is a very long time to wait when the firmware fails to load for some reason; this is wasting precious cycles. See recent example in:
https://sof-ci.01.org/linuxpr/PR4995/build3008/devicetest/index.html
https://github.com/thesofproject/sof-test/issues/1112#issuecomment-2116096789

lib.sh: switch MTL back to default MAX_WAIT_FW_LOADING=3 seconds

---

test-case/verify-kernel-boot-log.sh

Protect storage in case this is not run first and immediately after boot as it should. Also makes the logs more relevant and usable: long files can make the user interface unusable, see example in https://github.com/thesofproject/sof/issues/8761
This also gives us --no-pager "for free" in case it was ever needed.
Fixes recent commits c8565e8b210d and 914c5c06e075.

verify-kernel-boot-log.sh: cap boot logs to 6000 max_lines

---

test-case/volume-basic-test.sh
tools/topo_vol_kcontrols.py
tools/tplgtool2.py

4 commits
Until now this test was "screen-scraping" amixer output. This was not
compatible with v2 topologies which means the test was always SKIP for
everything developped on the main branch. Switch to parsing topologies
to extract volume kcontrols.
Fixes: https://github.com/thesofproject/sof-test/issues/1069, see also discussion in earlier attempt https://github.com/thesofproject/sof-test/pull/1068.

volume-basic-test.sh: switch to .tplg parsing to test topologies v2

---

test-case/verify-kernel-boot-log.sh

xrandr can hang! Who could have known? See evidence in:
- https://github.com/thesofproject/linux/pull/5009#issuecomment-2122857477
Don't wait for CI to timeout and kill the whole script so we don't lose precious logs.

verify-kernel-log.sh: guard "xrandr" with a short "timeout"

---

case-lib/lib.sh

2 commits
As usual, @fredoh9 clean up and simplification of the internal, Intel deployment scripts exposed some old bugs that were hidden so far because we have too many fallbacks in this area.

Fix check-sof-logger.sh

---

tools/sof-dump-status.py

Set pci_info['hw_name'] to "PCI device unknown by SOF" and keep going.
Before this commit, any test that invokes sof-dump-status.py for any reason crashes like this when the PCI ID is unknown:
```
Traceback (most recent call last):
File "sof-test/tools/sof-dump-status.py", line 497, in <module>
sysinfo.loadPCI()
File "sof-test/tools/sof-dump-status.py", line 139, in loadPCI
pci_info['hw_name'] = self._pci_ids["0x" + tmp_line[4] + tmp_line[3]]
KeyError: '0xe328'
```
The lack of a known PCI ID does not have to be fatal: there are plenty of use cases where the PCI ID is not needed. This commit makes it possible to run all these test cases even when the PCI ID is unknown.
This could help with #288 too.

sof-dump-status.py: don't crash on unknown Intel audio PCI devices

---

alsa_settings/MTLP_RVP_SDW.sh

MTLP_RVP_SDW uese rt711 and it needs to overwritre the jack detection type.

alsa_settings: MTLP_RVP_SDW.sh: add rt711 GE control

---

tools/sof-fw-boot-test.py

This requires the kernel changes that expose the debugfs entries for executing the different DSP ops and reading the current DSP firmware and power states.
The script takes the firmware name and the path as inputs along with the number of iterations of firmware boot. It takes care of putting the DSP in the D3 state and unloading any existing firmware before starting firmware boot.
This needs the kernel PR for testing: https://github.com/thesofproject/linux/pull/4874

tools: Add a new script for firmware boot stress testing

---

tools/kmod/sof_insert.sh
tools/kmod/sof_remove.sh

rt722_sdca codec is missing in kmod scripts.

kmod: add rt722_sdca codec

---

tools/kmod/sof_remove.sh

snd_soc_sdw_utils module is missing in kmod scripts.
This needs to be merged before https://github.com/thesofproject/linux/pull/5068

kmod: add snd_soc_sdw_utils module

---

tools/kmod/sof_remove.sh

wrong order as shown in
https://sof-ci.01.org/linuxpr/PR5068/build3857/devicetest/index.html?model=CML_RVP_SDW-ipc3&testcase=check-sof-logger

kmod: add snd_soc_sdw_utils module - take2

---

test-case/multiple-pipeline.sh

Sometimes pkill seems to fail terminating aplay and arecord processes. Add a system request to check state of those processes to investigate why they couldn't be killed.

multiple-pipeline: add debugging when pkill fails

---

case-lib/lib.sh

Checking for ldc (log dictionary) file existance as a way to decide whether to enable or disable logging during a test case, is no longer applicable as SOF supports multiple firmware logging solutions that do not use an ldc file.
Remove the check as it no longer makes sense.
Link: https://github.com/thesofproject/sof-test/issues/1216

case-lib: remove check for log ldc file

---

test-case/check-sof-logger.sh

[I haven't completely figured out how this script runs in CI, so this patch is mostly thrown up blind for review.  But this is where the error in CI is coming from, I believe]
Zephyr builds don't produce .ldc files anymore, don't look for them and fail.
Fixes: #1216

check-sof-logger.sh Predicate LDC search on !zephyr

---

case-lib/apause.exp
test-case/check-pause-resume.sh
test-case/multiple-pause-resume.sh

This all started as an effort to solve test failures caused by "MAX"
volume. See #931 and others linked from there for more context.
Another obvious issue was the duplication of `expect` code across two
tests (check-pause-resume.sh and multiple-pause-resume.sh)
After a bit of time actually "testing the tests" I realized the original
author did not really understand `expect` or the problem. So I rewrote
the entire `expect` part. The list of previous issues is a bit too long
not to forget any but here are some:
- The script could get "out of sync" with aplay and report that it was
paused when it was actually resumed! And vice-versa.
- De-duplication; obviously.
- Moving to a separate script also solves the following problems:
- Can be invoked, tested and debugged separately outside any …

Add new Expect script `tools/apause.exp`

---

case-lib/lib.sh

Should finally fix terminal corruption issue #1151.
Commit 834163887828 was a good workaround but it was applied only for Zephyr's mtrace.
- Apply the same workaround for stable-v2.2 sof-logger
- Explain better in the source what causes the corruption
- Change owner of mtrace.txt logs to "ubuntu" instead of root.

lib.sh: workaround "sudo ... &" corruption issue 1151 for stable-v2.2

---

tools/kmod/sof_remove.sh

Remove the remaining ALSA modules to have completely fresh start when
inserting the modules.
This way we can also test module parameters for the core.
Signed-off-by: Peter Ujfalusi <peter.ujfalusi@linux.intel.com>

sof_remove.sh: Remove all ALSA modules

---

tools/kmod/sof_remove.sh

This makes is possible to use this file separately from sof-test, as requested in #1169.

sof_remove.sh: make lib.sh optional

---

case-lib/apause.exp
test-case/check-pause-release-suspend-resume.sh

cc:
- https://github.com/thesofproject/sof-test/pull/931
- https://github.com/thesofproject/linux/issues/5048
- https://github.com/thesofproject/linux/issues/5109
- https://github.com/thesofproject/linux/pull/5041

case-lib/apause.exp: fix error message and comments 

---

test-case/multiple-pause-resume.sh

It has been observed that the expect process has been terminated (pidof returns with no PID) but the child aplay is still running. This only happens with ChainDMA enabled PCMs where the time to stop the stream takes more than 100ms (from trigger stop to PCM close). With the right timing on such PCM the pidof expect will break the wait loop and we progress to the next iteration which - again with right timing and setup - might fail if the aplay is still in a process of closing and the next iteration includes the same PCM.
Add the aplay and arecord commands to the pidof command to make sure that the iteration has been completed before starting a new one. We will still catch timeouts and in that case we  should kill the stuck processes.

multiple-pause-resume.sh: Check for aplay/arecord pid when waiting

---

tools/kmod/sof_insert.sh
tools/kmod/sof_remove.sh

The snd_sof_pci_intel_ptl depends on the LNL module and it blobks removal of snd_sof_pci_intel_lnl.

tools: kmod: Handle snd_sof_pci_intel_ptl

---

case-lib/lib.sh

Add two generic functions fw_reldir() and fw_relfilepath() which search in this order:
1. /sys/kernel/debug/sof/fw_profile/
2. /sys/module/snd_sof_pci/parameters/
3. Kernel logs.
The 3., slower, "legacy" option is kept because it's useful with either old kernels or when the modules have been unloaded.
Start using these two generic functions in `is_firmware_file_zephyr()` and `get_ldc_subdir()`.

Add and start using generic functions fw_reldir() and fw_relfilepath()

---

test-case/check-suspend-resume-with-audio.sh
test-case/check-suspend-resume.sh

check-suspend-resume-with-audio.sh uses check-suspend-resume.sh. process check is in check-suspend-resume-with-audio.sh and check-suspend-resume.sh has the loop. Must check that the process id is available in each loop. TO do so, pass aplay/arecord pid to check-suspend-resume.sh.

check-suspend-resume: check process id in each loop for audio test case

---

case-lib/apause.exp

Always better to "fail fast".
See commit messages.

Catch aplay error messages in apause.exp and exit

---

test-case/check-ipc-flood.sh

Add is_firmware_file_zephyr() and a new SKIP message to stop telling Zephyr users to build a "debug firmware" because it won't change anything for them: IPC4 has no flood command right now, see https://github.com/thesofproject/sof-test/issues/1066
Also clarify the XTOS skip message + other cosmetic improvements.

check-ipc-flood.sh: stop asking Zephyr users to use CONFIG_DEBUG

---

test-case/multiple-pause-resume.sh
test-case/multiple-pipeline.sh

2 commits
Stop polluting test results daily.

multiple pipelines: skip XTOS + NOCODEC configurations

---

tools/tplgtool2.py

Convert the computed value to integer to set the values array size for parsing the enum controls properly.

tools: tplgtool2: Fix array size calculation for enum values

---

tools/tplgtool.py

When parsing a topology with sof-tplgreader.py the output with topology file as command line argument should produce the list of PCMs found in the topology. However when encountering a topology with enum controls, there are numbers printed before the desired PCMs output.
The printing of the 24 array index values (24, 30, 56, ..., 852) is there apparently for debugging the code. It is causing case-lib/pipeline.sh to fail and cause false failures of CI test cases. This patch simply removes the print commands.

Tools: Tplgtool: Remove debug print of array indices

---

case-lib/apause.exp
case-lib/config.sh
case-lib/lib.sh
tools/sof-kernel-log-check.sh

Source additional files /etc/sof/local_config.bash and
sof-test/case-lib/local_config.bash.
This helps solving device-specific issues like https://github.com/thesofproject/sof-test/pull/1233 and many others
before that - for instance git blame the "ignore_str" variable in
sof-kernel-log-check.sh

Add new local_config.bash files to solve device-specific issues

---

tools/kmod/sof_insert.sh
tools/kmod/sof_remove.sh

rt1017-sdca and CirrusLogic missing
The CS42L43 order is inverted, the core calls into the -sdw module

kmod: add more SoundWire codecs

---

test-case/manual/Audio_privacy.md

Added Manual Test case for Audio Privacy (Hard Mute) Function

Manual Test case - Audio Privacy (Hard Mute)

---

test-case/manual/Hi_Fi_Audio_playback.md

Added Manual Test case for High Fidelity Audio Rendering feature

Manual Test case - High Fidelity Audio Rendering

---

test-case/verify-kernel-boot-log.sh

Added Enhancement for "amixer" card selection: support card identification by name

Test-case: Enhance "amixer" card selection

---

tools/kmod/sof_remove.sh

snd_seq_dummy and snd_hrtimer are present while pipewire is enabled in ubuntu 24.04.
Those modules prevent snd_seq and snd_timer from unloading and sof_remove.sh fails.
Failed logs from old version, these errors are not present with this commit applied.
```ini
RMMOD   snd_usb_audio
RMMOD   snd_usbmidi_lib
SKIP    snd_hda_intel   not loaded
RMMOD   snd_sof_pci_intel_tng
RMMOD   snd_sof_pci_intel_skl
RMMOD   snd_sof_pci_intel_apl
RMMOD   snd_sof_pci_intel_tgl
RMMOD   snd_sof_pci_intel_icl
RMMOD   snd_sof_pci_intel_cnl
RMMOD   snd_sof_pci_intel_ptl
RMMOD   snd_sof_pci_intel_lnl
RMMOD   snd_sof_pci_intel_mtl
RMMOD   snd_sof_acpi_intel_byt
RMMOD   snd_sof_acpi_intel_bdw
SKIP    snd_sof_imx8    not loaded
SKIP    snd_sof_imx8m   not loaded
SKIP    snd_soc_catpt   not loaded
SKIP …
```

kmod: remove snd_seq_dummy and snd_hrtimer

---

tools/sof-kernel-log-check.sh

ignore ISH firmware missing error in PTL since it is not impact to audio test cases

sof-kernel-log-check.sh: ignore ISH firmware missing error

---

alsa_settings/PTLH_HDA_AIOC.sh

Add explicit set for capture source to ensure the capture is done from the headset mic. Test cases (like alsabat) expect the HDA codec to be attached to a analog loopback cable.
Also fix a stray '~' character in the script.

alsa_settings: PTLH_HDA_AIOC.sh: fix mic source

---

CODEOWNERS

Add maintainers as code owners explicitly to resolve 'unknown owner' error which appears in forks.

CODEOWNERS: Add maintainers explicitly

---

alsa_settings/PTLP_RVP_SDW.sh

alsa_settings/PTLP_RVP_SDW.sh: Modified alsabat mixer settings with respect to UCM2 file for PTL SDW RT722"

ALSABAT:fix bug: updated alsabat mixer settings

---

tools/sof-ipc-timer.py

The sof-ipc-timer collects IPC message processing times from 'journalctl -k -o short-precise' output if SOF IPC debug is enabled.
The recognized messages are GLB_CREATE_PIPELINE, GLB_DELETE_PIPELINE, MOD_INIT_INSTANCE, MOD_LARGE_CONFIG_SET (only with valid module id), MOD_BIND, MOD_UNBIND, and GLB_SET_PIPELINE_STATE.
Different kind of outputs can be generated with different flags. Adding just -s gives a summary. Giving full FW side log, using FW built with CONFIG_DEBUG_IPC_TIMINGS=y, gives more accurate FW processing times.
With the above flags the output may look like this:
host-copier.2.playback fw init  min 76 us       max 77 us       average 76 us of 10
gain.5.1 fw init        min 49 us       max 51 us       average 49 us of 10
gain.5.1 fw conf        min 23 us       max 23 us …

tools: sof-ipc-timer.py: IPC message processing times from logs

---

test-case/check-audio-equalizer.sh

This change should avoid error: "Kernel check point "KERNEL_CHECKPOINT" is not properly set" in case-lib/lib.sh.

Test-case: check-audio-equalizer: Add kernel checkpoint

---

.github/workflows/yamllint.yml

Upgrade yamllint runner's Ubuntu from 20.04 to 24.04
Ubuntu 20.04 LTS runner is removed at GitHub since 2025-04-15.
see https://github.com/thesofproject/sof-test/actions/runs/14591728967

[SKIP SOF-TEST] .github: upgrade yamllint runner to Ubuntu 24.04

---

README.md
case-lib/lib.sh
env-check.sh
test-case/check-capture.sh
test-case/check-playback.sh
test-case/tinyalsa-wrapper.sh

Added option `SOF_ALSA_TOOL` to specify whether to use the `TinyASLA` or `ALSA` testing tool. For now, it is only for capturing and playback.
The default tool is ALSA.
This PR introduces also a generic wrapper  `tinyalsa-wrapper.sh` to define `SOF_ALSA_TOOL` in environments where setting environment variables directly is not possible. This is useful for frameworks or systems with limited configuration capabilities.

TinyAlsa: Add support for testing using tinycap and tinyplay.

---

case-lib/lib.sh

Set SOF_ALSA_TOOL variable to a default value globally.
Justification:
After tinyalsa support was added ([PR #1260](https://github.com/thesofproject/sof-test/pull/1260)), the use of SOF_ALSA_TOOL is now required for all tests before calling the aplay_opt or arecord_opt functions from lib.sh.

Fix: Set SOF_ALSA_TOOL to default value globally.

---

tools/kmod/sof_remove.sh

snd_soc_sdca is used by snd_soc_core. It should be removed before snd_soc_sdca.

sof_remove.sh: remove snd_soc_sdca before snd_soc_core

---

test-case/latency-metrics.sh

Fix output JSON in case there is no metrics gathered in non-trial mode, e.g. if gawk is missing on the DUT.

test-case: latency-metrics: fix no metrics JSON

---

test-case/check-alsa-conformance.sh

Add ALSA conformance tests from ChromeOS Audio Test package.
The new test case `check-alsa-conformance.sh` executes `alsa_conformnance_test` and compose its results into a JSON file.

[SKIP SOF-TEST] test-case: Add ALSA conformance tests

---

tools/kmod/sof_remove.sh

To fix the rmmod: ERROR: Module snd_hda_codec_generic is in use by: snd_hda_codec_realtek_lib snd_hda_codec_alc269 error

sof_remove: remove snd_hda_codec_alc269 and snd_hda_codec_realtek_lib first

---

tools/kmod/sof_remove.sh

To fix the rmmod: ERROR: Module snd_hda_codec_generic is in use by: snd_hda_codec_realtek_lib snd_hda_codec_alc882 error

sof_remove: remove snd_hda_codec_alc882 before snd_hda_codec_realtek

---

alsa_settings/WCL_HDA_AIOC.state
alsa_settings/WCL_RVP_SDW.state
alsa_settings/WCL_SDW_RT712.state

Create WCL platform ALSA settings state files for:
* WCL_HDA_AIOC
* WCL_SDW_RT712
* WCL_RVP_SDW
The parameters in the state files are explicitly set even if the default values at the appropriate DUT are currently the same.

alsa_settings: WCL platform settings

---

README.md
case-lib/hijack.sh
case-lib/lib.sh
test-case/check-performance.sh
test-case/pipewire-wrapper.sh

Added option to use pipewire instead of ALSA direct mode in tests, that can be turned on by setting TEST_WITH_PIPEWIRE=true. Added pipewire-wrapper, to run in SOF CI.
Currently only test that can run on pipewire is check-perfomance.sh (runs aplay/arecord on one of each types of sinks/sources).

tests: add option to test with pipewire

---

test-case/latency-metrics.sh

This fixes the wrong syntax of the bash built-in `true`.

test-case: latency-metrics.sh: Change `True` to lowercase
