thesofproject/sof-test

test-case/check-alsabat.sh

Add a common script for alsabat test.

test: add alsabat test

---

case-lib/hijack.sh
test-case/check-kmod-load-unload.sh

Now skip type 'sudo env PATH="PATH"' from case command

Feature: add env PATH into hijack sudo function

---

test-case/check-xrun-injection.sh

This script intends to test the ability of XRUN handling for each pipeline.

test: add xrun injection test

---

test-case/verify-ucm-config.sh

Remove the limitation of ucm2 to support ucm2 configurations.

verify-ucm-config :remove limitation of ucm2

---

tools/sof-tplgreader.py

Currenty, we only use the first supported format to run playback and capture test, this limits the test capacity. This patch add multiple formats output in sof-tplgreader.py, thus, enable multiple format support for test cases
I keep the 'fmt' in pipeline_dict, so, there is no influence on exist cases.  for cases want to use multiple format, use 'fmts'.
Example:
with `fmt = $(func_pipeline_parse_value $idx fmt)`, you got "S16_LE"
with  `fmts = $(func_pipeline_parse_value $idx fmts)`, you got "S16LE S24LE S32LE"

tools: add multiple formats output for sof-tplgreader.py

---

test-case/check-pause-resume.sh

1. Fix error 'sleep', tcl not support 'sleep', just support 'after'
2. Add random for the sleep time, it is more like human input
remove "sleep" option for this change
3. remove "duration" option, it option is confluct with "count"
after "count" trigger, target process will been quit
4. fix status check after expect script
5. add dmesg check after expect script

Bugfix: check-pause-resume error expect script

---

CODEOWNERS

Add CODEOWNERS for sof-test

---

README.md
case-lib/hijack.sh
test-case/check-sof-logger.sh
test-case/verify-kernel-module-load-probe.sh
test-case/verify-pcm-list.sh
test-case/verify-sof-firmware-load.sh
tools/sof-get-kernel-line.sh
tools/sof-kernel-dump.sh

1.  tools: add sof-get-kernel-line to catch line NO
this patch will helpful other usage
2. speed up the sof-kernel-dump
the large file still is big problem
3. update document for add new script
4. fix https://github.com/thesofproject/sof-test/issues/48

tools: Update the sof-kernel-dump

---

test-case/check-suspend-resume-with-audio.sh
test-case/multiple-pipeline-capture.sh
test-case/multiple-pipeline-playback.sh
tools/sof-process-state.sh

Add new Test Case for the suspend resume
playback/capture on the backgroud, do the suspend resume

Test Case: Add check suspend resume with audio

---

test-case/check-pause-resume.sh

fix escape '/' for repeat_count in dynamic create expect script
fix issue #49 

check-pause-resume: bugfix in expect script

---

test-case/check-suspend-resume-with-audio.sh
test-case/check-suspend-resume.sh

format parameter of check-suspend-resume & check-suspend-resume-with-audio

test case: sync parameter between suspend-resume & suspend-resume

---

tools/kmod/sof_remove.sh

kmod: sof_remove.sh: update machine driver name

---

test-case/check-ipc-flood.sh

test-case: add ability to loop ipc flood test

---

case-lib/lib.sh
test-case/check-reboot.sh
tools/sof-get-default-tplg.sh

Add new Test Case for the reboot

Test Case: Add check reboot test

---

test-case/manual/jack_detection_boot.md
test-case/manual/jack_detection_idle.md
test-case/manual/jack_detection_playback_capture.md

Adding manual walkthrough instructions for the current three jack detection tests.

Test case/manual/jack detection

---

test-case/multiple-pipeline-capture.sh
test-case/multiple-pipeline-playback.sh
test-case/simultaneous-playback-capture.sh

test-case: add ability to loop for multipipeline test cases

---

test-case/manual/check-pause-release-with-suspend-resume.md

Pause-Release with Suspend-Resume is a manual test for now.

test-case: manual: Pause-Release with Suspend-Resume Test

---

test-case/check-suspend-resume-with-audio.sh

Current meet some DUT catch lost process the error
Add ps command to dump the process status
This change not refer the code logic

test-case: check-suspend-resume-with-audio add more dump

---

tools/tplgtool.py

This patch adds component searching logic, thus, we can
get some type of components connected to a specified
component.
Based on the searching logic above, add a function to find
componnets connected to PCM, for example, PGA and EQ.

tools: add component searching logic for tplgtool

---

case-lib/lib.sh
test-case/check-reboot.sh

1. check-reboot have more parameter, but just handle the loop count
2. new feature lock have the warning when load sub-test,

bugfix of test-case/check-reboot

---

test-case/multiple-pause-resume.sh
tools/sof-combinatoric.py

This case go though the TPLG
do pause resume for the multiple pipeline

test-case: add multiple-pause-resume

---

tools/sof-dump-status.py

Some device use acpi to get power status instead of load from
pci device folder
1. add device id for output to know which platform use acpi device
2. query acpi power status & pci power status
fix issue #83

tools: sof-dump-status to add acpi device power detect

---

test-case/manual/DPMST.md

* Manual walkthrough for DisplayPort Multi-Stream Transport testing

test-case/manual: DPMST test

---

test-case/simultaneous-playback-capture.sh

Need to split both type pipeline into playback and capture
Change both keyword into check duplicate pcm id
Wait patch [sof-test: split both type pipeline into playback and capture](https://github.com/thesofproject/sof-test/pull/80 ) can be merge this PR
Because without that change, this pr couldn't worked

test-case: simultaneous-playback-capture.sh to remove 'both' keyword

---

test-case/verify-pcm-list.sh
tools/sof-dump-status.py

Patch 1:
remove 'both' from sof-dump-status to fix verify-pcm-list issue
Patch 2:
redesign test case, because older style have 'both' in TPLG
/proc/asound/pcm without 'both'
Current without 'both' in sof-tplgreader, can direct compare output
string for 'id','pcm','type'

test-case: verify-pcm-list redesign

---

test-case/check-kmod-load-unload-after-playback.sh
test-case/check-kmod-load-unload.sh

On helios, after module removal, `aplay -l` will report no soundcard found, we need to wait about 10s to resume.  This may be an error, and I report it here: https://github.com/thesofproject/linux/issues/1808. 
we should also check dsp status after module insertion and next check-playback for check-kmod-unload-reload-after-playback.sh
for platform support runtime pm, this is a safe and good practice. impact unknown for platform not support runtime pm.

test-case: check dsp status before/after module removal/insertion

---

case-lib/config.sh
case-lib/pipeline.sh

Includes @lgirdwood 's suggestion for the 'block' to 'ignore' verbiage change in pipeline.sh & config.sh
Additionally has general typo fixes and comment rewording.

WIP: Cleanup/caselib

---

test-case/check-ipc-flood.sh
tools/sof-kernel-log-check.sh

2 commit:
1. fix dmesg will catch system boot up call trace which is not our expect
2. Add more dump refer 'Call Trace' when catch the 'Call Trace'

fix case ipc-flood error

---

tools/sof-boot-once.sh
tools/sof-combinatoric.py
tools/sof-disk-usage.sh
tools/sof-dump-status.py
tools/sof-kernel-dump.sh
tools/sof-tplgreader.py
tools/tplgtool.py

Also includes verbiage change from 'block' to 'ignore' in sof-tplgreader.py and typo in tplgtool.py's snd_soc_tplg_dapm_widget field names

Cleanup/tools: General cleanup of typos, rewording comments 

---

tools/kmod/sof_remove.sh

kmod: fix dependencies with rt5677

---

tools/sof-tplgreader.py

fix setBlock() to setIgnore() and ignore to ignore_lst.

sof-tplgreader: fix unfinished clean up

---

test-case/verify-pcm-list.sh
test-case/verify-tplg-binary.sh

test-case: Fix filed-> field typo

---

test-case/check-runtime-pm-status.sh

- This patch use sof-dump-status.py to check if platform support runtime pm.
- This patch replaces the fixed delay time with a variable delay time to reduce test time.
- Test info improvement.

test-case: refine check-runtime-pm-status.sh

---

test-case/check-runtime-pm-status.sh

aplay/arecord can be used by setting -m option. Add scanning dmesg for
error before switching pipelines.
I submitted two commits in in PR#92. This is first part of it.
https://github.com/thesofproject/sof-test/pull/92
For the new test case i will update on PR#92 if I found better solution.

test-case: add capture pipeline support for runtime pm test

---

test-case/verify-pcm-list.sh

when case failed, add full kernel dump into file
fix issue: #111

test-case: verify-pcm-list to add kernel dump

---

case-lib/hijack.sh
case-lib/lib.sh
case-lib/logging_ctl.sh
case-lib/opt.sh

General typo fixes and comment rewording.
Successor to #97

Cleanup/case lib --- the rest of the subdir

---

test-case/manual/check-muteLED-pulseaudio.md

Add mute LED test cases in manual test.

test-case/manual: mute led via pulseaudio test case

---

tools/sof-combinatoric.py

tools: Comment cleanup in sof-combinatoric.py

---

test-case/check-sof-logger.sh

Previously, we use the file size generated by sof-logger
to test if we have firmware log to export. But after a
logger change, sof-logger errors will output to generated
file, the size of the file is variant due to sof-logger
errors.
grep "errror|Error|ERROR“ from sof-logger's  stderr redirected file.

test-case: handle sof-logger errors in check-sof-logger.sh

---

case-lib/hijack.sh
case-lib/lib.sh

Compare the gains with the risks, remove the sof-lock
Now if meet test-case resource problem, #122 will handle this

case-lib: remove SOF-LOCK file

---

tools/kmod/sof_insert.sh
tools/kmod/sof_remove.sh

Update for machine driver change.

kmod: sof_remove.sh: add snd_soc_max98373 support

---

test-case/manual/check-fail-no-fw.md
test-case/manual/check-fail-no-tplg.md
test-case/manual/regresstion-linux1762-system-hang-when-sof-probe-fail.md

add regression test case for linux#1762 : Ensure system not hang when sof probe fail

test-case: manual: add regression test case for linux#1762

---

case-lib/opt.sh

store current sof-test version information

case-lib: opt.sh add sof-test branch and commit info

---

README.md
case-lib/hijack.sh

Add table for current test-script result for exit
Convert older 'SKIP' to 'N/A'

README: Add test result information

---

tools/tplgtool.py

This feature depends on python graphviz, install it with: `sudo apt install python3-graphviz`
Usage:
` tplgtool.py -d graph -V tplg-name`
This will automatically open your picture viewer, and show the topology graph.
`tplgtool.py -d graph -F fmt -D dir tplg-name`
This will generate topology graph, and store it in specified directory. The default name for generate graph is "tplg-name.png". "-f" controls graph format, -d" controls output directory. check "-h" option for more help.
Example:
Command: `tplgtool.py -d graph -F png -D ~ sof-apl-pcm512x.tplg`
will generate sof-apl-pcm512x.png in user's HOME folder.

tools: add topology graph dump feature in tplgtool.py

---

case-lib/hijack.sh

The tplgtool.py for graph generation is done, and now add the graph generation code in exit function.
If you have some other idea on AT WHAT test stage we should generate tplg graph, please add your comments.

case-lib: add topology graph generation support 

---

test-case/check-reboot.sh

sub-case: verify-tplg-binary.sh need TPLG as parameter to pass
test-case

test-case: check-reboot fix sub-case parameter miss

---

case-lib/lib.sh
test-case/verify-sof-firmware-load.sh

fix issue #175
when test case is sub-case use dmesg to check current status

test-case: refine verify-sof-firmware-load to add dmesg support

---

test-case/multiple-pause-resume.sh

change wait expect finish logic from detect expect at begin
to fix issue #138

test-case: multiple-pause-resume modify wait logic

---

CODEOWNERS

As requested by Liam.
Signed-off-by: Liam Girdwood <liam.r.girdwood@intel.com>

CODEOWNERS += @marc-hb

---

tools/kmod/sof_insert.sh
tools/kmod/sof_remove.sh

kmod: add snd_soc_rt5660 support for EHL

---

tools/sof-dump-status.py

sync with sof-pci-dev.c update
fix issue #185

tools: sof-dump-status update PIC ID for EHL + JSL

---

tools/sof-dump-status.py

tools: sof-dump-status: force setup acpi power status to unsupported

---

test-case/verify-pcm-list.sh

LOOG_ROOT -> LOG_ROOT which is sof-test define store path

test-case: verify-pcm-list: fix typo

---

test-case/check-ipc-flood.sh
test-case/check-pause-resume.sh
test-case/check-suspend-resume-with-audio.sh
test-case/check-suspend-resume.sh
test-case/multiple-pause-resume.sh
test-case/multiple-pipeline-capture.sh
test-case/multiple-pipeline-playback.sh
test-case/simultaneous-playback-capture.sh

As Bin add check for kernel log check return value in https://github.com/thesofproject/sof-test/pull/203, and use a new code style, this patch align code style around all of the repo.

test-case: unify code style for kernel log check function calls

---

test-case/check-alsabat.sh
test-case/check-audio-equalizer.sh
test-case/check-capture.sh
test-case/check-ipc-flood.sh
test-case/check-kmod-load-unload-after-playback.sh
test-case/check-kmod-load-unload.sh
test-case/check-pause-release-suspend-resume.sh
test-case/check-pause-resume.sh
test-case/check-playback.sh
test-case/check-reboot.sh
test-case/check-runtime-pm-double-active.sh
test-case/check-runtime-pm-status.sh
test-case/check-signal-stop-start.sh
test-case/check-sof-logger.sh
test-case/check-suspend-resume-with-audio.sh
test-case/check-suspend-resume.sh
test-case/check-xrun-injection.sh
test-case/multiple-pause-resume.sh
test-case/multiple-pipeline-capture.sh
test-case/multiple-pipeline-playback.sh
test-case/simultaneous-playback-capture.sh
test-case/test-speaker.sh
test-case/verify-firmware-presence.sh
test-case/verify-kernel-module-load-probe.sh
test-case/verify-sof-firmware-load.sh
test-case/verify-tplg-binary.sh
test-case/verify-ucm-config.sh
test-case/volume-basic-test.sh

this patch does an overall cleanup on all test cases.

test-case: change $* to "$@" to pass shellcheck

---

test-case/check-audio-equalizer.sh

Query eq pipelines from topology file. Test iir or fir separately
whichever is available. And base on type of the pipeline, aplay or
arecord is used for the test.
fixes: https://github.com/thesofproject/sof-test/issues/177

test-case: test iir and fir filter independently

---

test-case/check-audio-equalizer.sh
test-case/check-capture.sh
test-case/check-ipc-flood.sh
test-case/check-kmod-load-unload-after-playback.sh
test-case/check-kmod-load-unload.sh
test-case/check-pause-release-suspend-resume.sh
test-case/check-playback.sh
test-case/check-reboot.sh
test-case/check-runtime-pm-double-active.sh
test-case/check-runtime-pm-status.sh
test-case/check-suspend-resume.sh
test-case/multiple-pause-resume.sh
test-case/multiple-pipeline-capture.sh
test-case/multiple-pipeline-playback.sh
test-case/simultaneous-playback-capture.sh
test-case/volume-basic-test.sh

test-case: Add Flag '=====' for the loop count

---

tools/sof-dump-status.py

dump all file of dapm folder to help DEV trace suspend status
fix issue #215 

tools: sof-dump-status: add DAPM dump feature

---

CODEOWNERS

CODEOWNERS -= stripes416

---

README.md
test-case/check-ipc-flood.sh
test-case/check-kmod-load-unload-after-playback.sh
test-case/multiple-pipeline-capture.sh
test-case/multiple-pipeline-playback.sh
test-case/verify-pcm-list.sh
test-case/verify-sof-firmware-load.sh
test-case/volume-basic-test.sh
tools/sof-disk-usage.sh
tools/sof-process-kill.sh
tools/sof-process-state.sh

Visual inspection of all documentation and shell scripts.

Fix typos and grammar in scripts and documentation

---

case-lib/lib.sh
case-lib/pipeline.sh
test-case/check-alsabat.sh
test-case/check-audio-equalizer.sh
test-case/check-capture.sh
test-case/check-ipc-flood.sh
test-case/check-kmod-load-unload-after-playback.sh
test-case/check-kmod-load-unload.sh
test-case/check-pause-release-suspend-resume.sh
test-case/check-pause-resume.sh
test-case/check-playback.sh
test-case/check-reboot.sh
test-case/check-runtime-pm-double-active.sh
test-case/check-runtime-pm-status.sh
test-case/check-signal-stop-start.sh
test-case/check-sof-logger.sh
test-case/check-suspend-resume-with-audio.sh
test-case/check-suspend-resume.sh
test-case/check-xrun-injection.sh
test-case/multiple-pause-resume.sh
test-case/multiple-pipeline-capture.sh
test-case/multiple-pipeline-playback.sh
test-case/simultaneous-playback-capture.sh
test-case/test-speaker.sh
test-case/verify-firmware-presence.sh
test-case/verify-pcm-list.sh
test-case/verify-sof-firmware-load.sh
test-case/verify-tplg-binary.sh
test-case/verify-ucm-config.sh
test-case/volume-basic-test.sh

add die function, and use it to clean up old dloge error message && exit pattern

sof-test: replace dloge/exit pattern with die

---

tools/tplgtool.py

Previously, we use the processed graph link to
draw topology graph. If there is loop in topology
graph, we will be traped into an endless recursion
when traverse the graph.
This patch adds check for loop, and use the raw
widget-contorl-widget denoted link from topology
to draw the graph.

tools: add support for drawing loop in topology graph

---

test-case/verify-firmware-presence.sh

verify-firmware-presence.sh: missing quotes and other warnings

---

tools/kmod/sof_insert.sh
tools/kmod/sof_remove.sh

kmod: add kmod support for snd_soc_max98373_sdw

---

case-lib/hijack.sh
case-lib/lib.sh

Errexit fixes

---

test-case/run-all-tests.sh

The scrupt is to run all test cases.
Signed-off-by: Bard Liao <yung-chuan.liao@linux.intel.com>
@xiulipan @aiChaoSONG I don't know who is the author. Please help to add the author's signed-off-by if you know who he/she is.

test-case: new run-all-tests.sh 

---

test-case/manual/check-pulseaudio-automatic-source-switch.md
test-case/manual/check-pulseaudio-init-values.md
test-case/manual/check-pulseaudio.md

Add more test cases for pulseaudio

test case: manual: pulseaudio test case

---

test-case/manual/regresstion-sof2937-check-peak-capture-volume.md

test-case: manual: add regression test case for sof#2937

---

test-case/manual/check-asrc-tplg.md

Add ASRC verify for manually check first

test-case: manual: check ASRC topology

---

test-case/manual/check-playback-capture-latency-at-the-beginning.md

test-case: manual: check latency at the beginning

---

test-case/manual/jack_detection_suspend.md

test-case: manual: Jack detection while system suspended

---

case-lib/config.sh
test-case/check-runtime-pm-double-active.sh
test-case/check-runtime-pm-status.sh
test-case/check-xrun-injection.sh
test-case/multiple-pause-resume.sh
test-case/multiple-pipeline-capture.sh
test-case/multiple-pipeline-playback.sh

add DMIC16k pipeline test back as it is blocked, and clean up side effect after unblocking DMIC16k pipeline
DMIC16k blocked by: #74

test-case: don't ignore dmic16k pipeline test

---

CODEOWNERS

CODEOWNERS -= Bin-QA

---

test-case/check-fw-echo-reference.sh

add one new test case to check the echo reference on
on supported platforms.

test-case: add echo reference test case

---

CODEOWNERS

We're not that big.
Also try to use new test-maintainers team.

CODEOWNERS: remove 15 lines to simplify

---

env-check.sh

See commit messages.
Only the easiest fixes for now.

env-check.sh: fix 8/22 shellcheck warnings

---

CODEOWNERS

CODEOWNERS: fix thesoftproject/test-maintainers typo

---

env-check.sh

2 commits. The main change is replacing the `sed /etc/group` suggested hack with a `usermod` command. The other commit is just a minor cleanup.

 env-check.sh: replace sed /etc/group hack with usermod command 

---

test-case/check-smart-amplifier.sh
tools/wavetool.py

- add a wavetool for DSM/WOV/EchoReference feature test (used to analyze wave)
- add DSM test case.

test-case: add case for DSM feature test

---

test-case/check-fw-echo-reference.sh

Refine the check-fw-echo-reference.sh script and fix some shellcheck warnings.

test-case: refine the test script and fix the shellcheck warnings

---

tools/wavetool.py

The output of argparse was disguised with two steps:
- it was converted to (slightly more verbose) dictionary for no
particular reason
- that dictionary was passed entirely as is as kwargs to every function,
looking like these functions could be called with changing parameters.
Remove these two steps and make it clear that these values are always
the same global constants.
No other change; no functional change.

wavetool.py: clarify cmd_args. No functional change.

---

test-case/check-keyword-detection.sh

add one new test case to check the keyword detection and use
the wavetool to do the analysis.

test-case: add keyword detection test support

---

tools/wavetool.py

For WoV feature, we designed a special test wave,
which contains three parts:
1. low volume sine wave of 997.0 Hz, which will not
trigger WoV.
2. zero marker of 50ms
3. high volume sine wave of 997.0 Hz, which will
trigger WoV.
To generate the designed wave, run
wavetool.py -g wov -A 0.25 1.0 -D 4. 6. -B S16 -o path
or you can specify frequencies with -F, phases with -P.
The analysis contains below procedures:
1. find zero marker range from recorded wave
2. normalize recorded wave for processing
3. extract low volume sine wave and high volume
sine wave according zero marker range.
4. filter out target frequency in time domain
5. calculate THD+N of two parts
6. compare calculated THD+Ns with predefined threshold,
and give test verdict.

tools: add WoV wave generation and analysis support

---

tools/sof-tplgreader.py

If run general test on echo reference capture pipeline,
there will be errors due to no feed data. So we need
to block this pipeline in general test while keep
echo reference playback pipeline.
This patch enhances the pipeline filtering with block
feature, and makes it possible to block specified pipeline
by keyword.
Usage:
1. default behavior is to dump all pipelines, for example:
sof-tplgreader.py sof-tgl-max98357a-rt5682.tplg
2. specify -f, WOV and ECHO REF capture pipeline will be blocked,
and specified filter keyword still works, for example, below line
will filter out all capture pipelines except WOV and ECHO REF capture:
sof-tplgreader.py -f "type:capture" sof-cml-rt1011-rt5682.tplg
3. specify -b, specified pipelines will be blocked, for example,
below line will block all playback …

tools: enhance pipeline filtering with block feature

---

tools/wavetool.py

tools: fix reference wave parameter assignment error

---

case-lib/lib.sh

case-lib: make sof-*.ldc file path configurable

---

tools/sof-tplgreader.py

This feature is required for pipeline with codec adapter test.

tools: add filter for pipeline with codec adapter

---

test-case/check-smart-amplifier.sh
tools/wavetool.py

- make calculation of THD+N a generic function
- remove reference in DSM wave analysis.
- discard -r option when call wavetool.py in check-smart-amplifier test case.

refine wavetool.py and check-smart-amplifier test case

---

tools/sof-tplgreader.py

check the comments in the code for a reason.

tools: fix a pipeline formats assignment error

---

test-case/check-alsabat.sh
test-case/check-audio-equalizer.sh
test-case/check-kmod-load-unload-after-playback.sh
test-case/check-kmod-load-unload.sh
test-case/check-pause-release-suspend-resume.sh

test-case: add set -e to 5 basic test cases

---

test-case/check-smart-amplifier.sh

Once smart-amplifier test case failed, upload wave file for debug.

test-case: upload wave once smart amp test failed

---

case-lib/hijack.sh
tools/sof-kernel-log-check.sh

a generic form of the authentication failure test

---

test-case/check-playback.sh

Missing quotes for the most part.

check-playback.sh: fix all shellcheck warnings

---

case-lib/opt.sh

Add and rephrase comments. Zero code change.

opt.sh: add and rephrase comments. Zero code change.

---

test-case/run-all-tests.sh

Still a hack but better than nothing at all.
Barely any change to the previous, default values.

run-all-tests: make the test durations somewhat variable

---

tools/sof-dump-status.py

The ACPI support is currently problematic and only works if there is a
PCI device, which is true only on MinnowBoard and Chromebook Cyan used
for SOF CI, but false in general for all other BYT/CHT devices.
There is no reason why ACPI needs to be tied to PCI, devices can be
found in /sys/bus/acpi/devices/ directly.

sof-dump-status: fix ACPI support

---

test-case/test-speaker.sh

test-speaker: add more case description

---

env-check.sh

Simplify and remove duplication, use an array and for loop instead. 450
fewer characters.
Stop parsing files directly, switch to getent system interface instead.
Stop recommending editing file directly, recommend usermod system
interface instead.
Fix the last shellcheck warnings in this file:
In env-check.sh line 107:
```
[[ "$user" ]] && [[ ! $(awk -F ':' '/^adm:/ {print $NF;}' /etc/group|grep "$user") ]] && \
^-- SC2143: Use grep -q instead of comparing output with [ -n .. ].
```
(3 times because of code duplication)

env-check.sh: rewrite complicated and duplicated group membership

---

test-case/check-smart-amplifier.sh
tools/wavetool.py

The tool now support to generate different sine wave to different channel in amplitude, frequency and phase.
- generate wave with different frequency in different channel: `wavetool.py -g sinusoid -F 500 1000 1500 2000 -C 4`
- generate wave with different frequency and amplitude in different channel: `wavetool.py -g sinusoid -A 0.4 0.6 0.8 1.0 -F 500 1000 1500 2000 -C 4`

wavetool: enhance sinusoid generation 

---

test-case/check-alsabat.sh

alsabat cleanups

---

tools/sof-kernel-log-check.sh

Fixes: #374
Signed-off-by: RuiqingX <ruiqingx.zhang@intel.com>

sof-kernel-log-check:ignore i915 false failure(update)

---

test-case/multiple-pause-resume.sh

multiple-pause-resume: better error handling

---

test-case/check-pause-resume.sh

2 commits: 1. shellcheck clean-up, 2. SOF_ALSA_OPTS

check-pause-resume: add support for SOF_ALSA/APLAY/ARECORD_OPTS

---

.github/workflows/pull_request.yml

Seems to achieve 100% parity with .travis.yml

New .github/workflows/pull_request.yml converted from .travis.yml

---

case-lib/opt.sh

Add missing new line.
Remove branch output as we are always using detached mode.
Show current commit logs.

lib: opts: optimize the output in version.txt

---

test-case/multiple-pipeline.sh

This patch adds more comments to multiple-pipeline.sh
to describe how the script runs.
No functonal change.

multiple-pipeline: add more comments

---

test-case/check-alsabat.sh

Add channel and rate options support in alsabat test and
remove use of plughw to run alsabat test at hw level w/o
any conversions done by alsa-lib.

remove plughw in alsabat test

---

tools/tplgtool.py

Previously, the _enum_ctrl_parse() is left unimplemented
because we don't have enum kcontrol in existing topologies.
The new component TDFB is introduced recently, and requires
enum kcontrol to be parsed.
This patch implements the _enum_ctrl_parse function to
support enum kcontrol parsing.

tplgtool: implement enum kcontrol parsing function

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Add two new templates for bug report and feature request.

[skip ci]GitHub: add issue template for bug and feature

---

test-case/check-userspace-paplay.sh
test-case/check-userspace-parecord.sh

The OPT_xxx in sof-test has been updated. Let's update to the latest fmt
for check-userspace-paplay.sh and check-userspace-parecord.sh.
Signed-off-by: Libin Yang <libin.yang@intel.com>

userspace: update to latest opt fmt

---

tools/kmod/sof_remove.sh

https://github.com/thesofproject/linux/pull/2712 adds two new modules
that need to be removed.

kmod: add new modules required by machine drivers

---

tools/sof-dump-status.py

Add Up extreme to the list of community boards
Signed-off-by: Ranjani Sridharan <ranjani.sridharan@linux.intel.com>

sof-dump-status: add Up Extreme to community boards

---

case-lib/lib.sh

From a developer perspective this makes easier to deploy the .ldc
dictionary at the same time than the firmware.

lib.sh: add 2nd .ldc fallback in /lib/firmware/intel/sof/sof-abc.ldc

---

case-lib/lib.sh
test-case/check-sof-logger.sh

check-sof-logger: switch to new find_ldc_file() function

---

tools/kmod/sof_remove.sh

This will be useful in a future "spring cleaning" in a year or two.

kmod: sof_remove: add github URL to date snd_sof_nocodec re-ordering

---

test-case/verify-pcm-list.sh

verify-pcm-list.sh: fix the last shellcheck warnings

---

test-case/check-kmod-load-unload.sh

3 commits, see commit messages.

Fix check-kmod-load-unload.sh green failure. Other cleanups

---

tools/sof-tplgreader.py

Also remove unused imports and add pydocs about data structures. No
functional change.

sof-tplgreader.py: document boolean precedence and other design issues

---

tools/kmod/sof_remove.sh

For some reason (bug?) using /sys/kernel/debug/sof/trace hangs rmmod
forever. Note playing audio is not an issue, for instance speaker-test
-s 1 -l 0 is interrupted when unloading the drivers.
This is especially a problem when invoking sof-logger over ssh where
Ctrl-C interrupts ssh but not the sof-logger
Will hopefully avoid TIMEOUTs like
https://github.com/thesofproject/sof/issues/4443 which was likely
introduced by commit 6a8871fb849a ("check-sof-logger: reload drivers
first")

sof_remove.sh: kill sof-loggers first as they hang rmmod forever

---

tools/kmod/sof_insert.sh

Also add commented out "snd_sof sof_debug=1" example

[SKIP CI] sof_insert.sh: add support for module parameters

---

tools/tplgtool2.py

`Path.glob()` didn't implement for absolute path (will raise NotImplementedError).
Here is a workaround for this limitation from Python.

tplgtool2.py: accept absolute topology file path

---

test-case/check-ipc-flood.sh

Signed-off-by: Peter Ujfalusi <peter.ujfalusi@linux.intel.com>

check-ipc-flood.sh: Add set -e

---

tools/tplgtool2.py

* dotted and blue for virtual widgets.
* dashed and orange for dynamic pipelines.
For example:
* `sof-adl-max98357a-rt5682.tplg` (virtual widgets): ![sof-adl-max98357a-rt5682](https://user-images.githubusercontent.com/87001168/140743381-2f77ad3f-5d3e-4dd3-a2a2-166d0ac55283.png)
* `sof-tgl-nocodec.tplg` (dynamic pipelines): ![sof-tgl-nocodec](https://user-images.githubusercontent.com/87001168/140743410-8bcd02de-7167-454d-9041-c2a6414e3a8b.png)
* `sof-hda-generic-4ch-kwd.tplg` (both dynamic pipelines and virtual widgets): ![sof-hda-generic-4ch-kwd](https://user-images.githubusercontent.com/87001168/140743455-1fc43fc3-a1ab-454b-81a0-3baf18d4cd15.png)

tplgtool2: style for special components in topology

---

test-case/check-sof-logger.sh

Re-enable only for the DMA trace.
\+ fix error handling in run_loggers function

check-sof-logger: partially re-enable for Zephyr 

---

test-case/run-all-tests.sh

run-test-all.sh: cleanup for IPC4

---

case-lib/hijack.sh
test-case/volume-basic-test.sh

Found and reported while testing IPC4 but probably not specific to it.
Fixes https://github.com/thesofproject/sof-test/issues/844
\+ the most obvious shellcheck fixes

volume-basic-test: do not FAIL but SKIP when no PGA control

---

test-case/multiple-pipeline.sh

Known issue https://github.com/thesofproject/sof/issues/3170 has been
polluting the test results for years.
Signed-off-by: Marc Herbert <marc.herbert@intel.com

multiple-pipeline.sh: temporarily disable capture on BDW 

---

test-case/multiple-pause-resume.sh
test-case/multiple-pipeline.sh

Skip the Echo Reference pipeline test in multiple-pause-resume and multiple-pipeline.

skip the test on Echo Reference pipeline 

---

tools/sof-dump-status.py

No code change
Signed-off-by: Marc Herbert <Marc.Herbert@intel.com>

[SKIP CI] sof-dump-status: add comments

---

tools/tplgtool2.py

Conditional import to ensure tplgtool2 compatible with construct 2.8-2.10.
To migrate Ubuntu 20.04 (construct 2.8.16) to 22.04 (construct 2.10.67).
see also:
- https://packages.ubuntu.com/jammy/python3-construct
- https://github.com/construct/construct/blob/master/docs/transition29.rst
- https://github.com/construct/construct/blob/master/docs/transition210.rst

tplgtool2: compatible with construct 2.8-2.10

---

case-lib/config.sh
case-lib/hijack.sh
case-lib/opt.sh

We want to use sof-test in our setup which is based on YOCTO distro. Please let us know if you think sof-test can be multiplatform.

[RFC]: Add initial patches for sof-test i.MX support

---

test-case/verify-kernel-boot-log.sh

While theoritically possible, with Ubuntu 20.04 no service ever caused systemctl --wait to hang forever. With Ubuntu 22.04 our luck has ran out so add a timeout so we don't wait for more than 30s. Also list all non-active services.
Example:
https://sof-ci.01.org/linuxpr/PR3871/build768/devicetest/
```
$ systemctl --user | grep -v active
UNIT                                     LOAD   ACTIVE     SUB       JOB   DESCRIPTION
gnome-initial-setup-first-login.service  loaded activating start     start GNOME Initial Setup
```

verify-kernel-boot-log.sh: add a 30s timeout to systemctl --wait

---

tools/tplgtool2.py

Warning: this is a backwards-incompatible change! The previous behavior is now available ONLY when using `--tplgroot`.
Up to now the user interface made the unusual choice to implement globbing internally instead of relying on the operating system. Maybe for compatibility with ancient .BAT scripts? So before this commit, internal globbing had to be quoted like this to escape the shell globbing, otherwise it would reject too many arguments ("unrecognized extra argument")
```
./tplgtool2.py 'sof-*.tplg'             # old, now INVALID usage
```
This commit adds support for multiple arguments and such quoting is not necessary anymore. HOWEVER, for backwards-compatibility the old behavior is preserved when using `--tplgroot`:
```
./tplgtool2.py --tplgroot . 'sof-*.tplg' # UNCHANGED behavior …
```

tplgtool2.py: support filesystem globbing and multiple arguments

---

alsa_settings/MTLP_RVP_HDA.sh
alsa_settings/MTLP_RVP_SDW.sh
case-lib/lib.sh

Signed-off-by: Keqiao Zhang <keqiao.zhang@intel.com>

alsa_settings: add amixer settings for MTLP_RVP_HDA and MTLP_RVP_SDW

---

tools/kmod/sof_insert.sh
tools/kmod/sof_remove.sh
tools/sof-dump-status.py

small changes for internal tests as well as hda-mlink support introduced in https://github.com/thesofproject/linux/pull/4158 (gated without this PR)

Add LNL support in sof-test

---

tools/tplgtool2.py

It is sometimes hard to draw connection between the nodes in the produced picture and user visible entities, like ALSA mixers and PCMs. The old behavior is behind '-w' or '--without_nodeinfo' flags.
The copier nodes are added with, copier type: AIF_IN, AIF_OUT, DAI_IN or DAI_OUT, and with copier widgets stream name.
I would have wanted to add the PCM names there in the AIF nodes, but unfortunately that info was not in the widgets of the TplgGraph, so I would have to bring it in from the GroupedTplg and somehow find the associated widgets for the PCMs.  I will look into that, but I think this already a good improvement. We could of course also just take care that the streams connected to PCMs would have names that are easily associated with the PCM names.

tplgtool2 add more information to the nodes in the picture

---

alsa_settings/TGLU_RVP_SDW_IPC4ZPH.sh

Set the 'rt711 AMIC Volume' to 0 and turn up the volume of 'rt711 ADC 08 Capture Volume' a bit.

alsa_settings: adjust amixer setting for TGLU_RVP_SDW_IPC4ZPH

---

tools/kmod/sof_insert.sh
tools/kmod/sof_remove.sh

Missing max98363, rt712-sdca, rt712-sdca-dmic

kmod: add new SoundWire codecs

---

tools/kmod/sof_remove.sh

Remove the kernel injector client if it is enabeld and loaded.

kmod: sof_remove: Add snd_sof_ipc_kernel_injector client

---

test-case/test-speaker.sh

Fixed a variety of quoting issues.
[Rewrite and reverse error conditions.](https://github.com/thesofproject/sof-test/commit/c10f5e9fef7461a8c1f32878809dea62a5eb53cb)
Signed off by Greg Galloway greg.galloway@intel.com

Test speaker : catch exit code + shellcheck fixes

---

alsa_settings/MTLP_RVP_SDW.sh

Since we have replaced the USB sound card to UCA222, so need to adjust the alsa settings to adapte to the new one.

alsa_settings: adjust the volume for MTL_RVP_SDW

---

test-case/check-xrun-injection.sh

Various shellcheck quoting issues and other fixes.

Shellcheck check xrun injection

---

case-lib/lib.sh
case-lib/logging_ctl.sh

very small and minor fixes

---

test-case/verify-tplg-binary.sh

The more coverage the merrier.

verify-tplg-binary.sh: parse the topology with tplgtool2.py too

---

tools/tplgtool2.py

Fixes `--show_core` display option issues initially reported by Yong Zhi in #1082
Components that don't have any core ID specified and using a default core were mishandled in several ways:
- Default values did not count in the `is_multicore()` function! So, when using a single CORE_ID=2 the count was wrong and `is_multicore()` wrongly returned false. See #1082
- Default values were never shown even when using `--show_core always`
- It was impossible to show the difference between the default coreID (no value) and the explicit value zero.
Fix all these issues by giving the default value a real status in the code.
A side-effect of this commit is that the `--show_core auto` option gets rid of the "multicore" idea and will now display coreIDs when there is a mix of "default" and "zero". This …

tplgtool2.py: fix --show_core handling of the lack of coreID

---

tools/sof_perf_analyzer.py

This patch adds more statistics for sof
performance data, include minimum value
of cpu_avg and cpu_peak lists, peak to
avg ratio.
```
COMP_NAME,    COMP_ID, CPU_AVG(MIN), CPU_AVG(AVG), CPU_AVG(MAX), CPU_PEAK(MIN), CPU_PEAK(AVG), CPU_PEAK(MAX), PEAK(MAX)/AVG(AVG)
mixout.2.1, 3-0x000003,         2.97,         2.97,         3.01,          3.04,          3.43,         13.35,               4.49
gain.2.1, 3-0x010006,         3.02,         3.03,         3.21,          3.42,          4.26,         12.75,               4.20
dai-copier.HDA.Analog.playback, 3-0x030004,         4.05,         4.06,         4.07,          4.21,          5.82,         14.58,               3.59
host-copier.31.playback, 4-0x040004,         3.71,         3.71,         3.75,          3.90,          4.84,         14.64, …
```

sof_perf_analyzer: Add more statistics

---

python-deps.txt
tools/sof_perf_analyzer.py

Change the underlining python built-in data structure used previously with pandas DataFrame and Series, while keeps the
program behavior unchanged.
Add a feature to output performance statistics to html, which is good for viewing it in CI web page.
You will see how pandas help us to simplify code.

Introduce pandas for performance analysis

---

test-case/verify-kernel-boot-log.sh

Logical revert of 2021 commit e1b364a57388d

verify-kernel-boot-log.sh: re-enable on ADL

---

tools/sof_perf_analyzer.py

Add module CPC calculation support in performance scripts.

audio: perf: add module cpc calculation in performance script

---

tools/kmod/sof_remove.sh

PR #1130 was not good enough...

Update module dependencies: take2

---

test-case/verify-kernel-boot-log.sh

Pure comment change, for details see
- https://github.com/thesofproject/sof-test/discussions/998#discussioncomment-7835621

verify-kernel-boot-log: add minor comment about display crash loop

---

case-lib/lib.sh
test-case/verify-kernel-boot-log.sh
tools/sof-kernel-log-check.sh

I8042 ignore

---

test-case/verify-kernel-boot-log.sh

Add dmic_switch_present() test

---

tools/topo_list_dapms.py
tools/topo_tree_dump.py

Does anyone find these useful? I did...

[SKIP SOF-TEST] Two new, simple topology2 parsing Python scripts

---

tools/kmod/sof_insert.sh
tools/kmod/sof_remove.sh

rt1320 is newly supported by kernel.

Kmod: add rt1320 codec

---

case-lib/lib.sh

The `reboot_wrapper` function prints `Reboot command` to stdout and reboots the platform

Add reboot wrapper function
